/** @noSelfInFile **/

declare function AddFrameText(whichFrame: HFrameHandle | null, text: string): void;
declare function AddressToHandle(i: number): HHandle;
declare function BitwiseAND(bit1: number, bit2: number): number;
declare function BitwiseNOT(i: number): number;
declare function BitwiseOR(bit1: number, bit2: number): number;
declare function BitwiseShiftLeft(bit1: number, bitsToShift: number): number;
declare function BitwiseShiftRight(bit1: number, bitsToShift: number): number;
declare function BitwiseXOR(bit1: number, bit2: number): number;
declare function C2I(c: TCode): number;
declare function CastAbility(whichAbility: HAbility | null): boolean;
declare function CastAbilityGround(whichAbility: HAbility | null, targX: number, targY: number): boolean;
declare function CastAbilityTarget(whichAbility: HAbility | null, target: HWidget | null): boolean;
declare function ClearFrameAllPoints(whichFrame: HFrameHandle | null): void;
declare function ClickFrame(whichFrame: HFrameHandle | null): void;
declare function ClickFrameEx(whichFrame: HFrameHandle | null, isRightClick: boolean): void;
declare function ConvertAbilityBooleanField(i: number): HAbilityBooleanField;
declare function ConvertAbilityBooleanLevelArrayField(i: number): HAbilityBooleanLevelArrayField;
declare function ConvertAbilityBooleanLevelField(i: number): HAbilityBooleanLevelField;
declare function ConvertAbilityIntegerField(i: number): HAbilityIntegerField;
declare function ConvertAbilityIntegerLevelArrayField(i: number): HAbilityIntegerLevelArrayField;
declare function ConvertAbilityIntegerLevelField(i: number): HAbilityIntegerLevelField;
declare function ConvertAbilityRealField(i: number): HAbilityRealField;
declare function ConvertAbilityRealLevelArrayField(i: number): HAbilityRealLevelArrayField;
declare function ConvertAbilityRealLevelField(i: number): HAbilityRealLevelField;
declare function ConvertAbilityStringField(i: number): HAbilityStringField;
declare function ConvertAbilityStringLevelArrayField(i: number): HAbilityStringLevelArrayField;
declare function ConvertAbilityStringLevelField(i: number): HAbilityStringLevelField;
declare function ConvertAnimType(i: number): HAnimType;
declare function ConvertArmorType(i: number): HArmorType;
declare function ConvertColour(alpha: number, red: number, green: number, blue: number): number;
declare function ConvertDefenseType(i: number): HDefenseType;
declare function ConvertFrameEventType(i: number): HFrameEventType;
declare function ConvertFramePointType(i: number): HFramePointType;
declare function ConvertHeroAttribute(i: number): HHeroAttribute;
declare function ConvertItemBooleanField(i: number): HItemBooleanField;
declare function ConvertItemIntegerField(i: number): HItemIntegerField;
declare function ConvertItemRealField(i: number): HItemRealField;
declare function ConvertItemStringField(i: number): HItemStringField;
declare function ConvertMouseButtonType(i: number): HMouseButtonType;
declare function ConvertMoveType(i: number): HMoveType;
declare function ConvertOriginFrameType(i: number): HOriginFrameType;
declare function ConvertOsKeyType(i: number): HOsKeyType;
declare function ConvertPathingFlag(i: number): HPathingFlag;
declare function ConvertPlayerMissileEvent(i: number): HPlayerMissileEvent;
declare function ConvertRegenType(i: number): HRegenType;
declare function ConvertSubAnimType(i: number): HSubAnimType;
declare function ConvertTargetFlag(i: number): HTargetFlag;
declare function ConvertTextAlignType(i: number): HTextAlignType;
declare function ConvertTimeType(i: number): HTimeType;
declare function ConvertUnitBooleanField(i: number): HUnitBooleanField;
declare function ConvertUnitCategory(i: number): HUnitCategory;
declare function ConvertUnitIntegerField(i: number): HUnitIntegerField;
declare function ConvertUnitRealField(i: number): HUnitRealField;
declare function ConvertUnitStringField(i: number): HUnitStringField;
declare function ConvertUnitWeaponBooleanField(i: number): HUnitWeaponBooleanField;
declare function ConvertUnitWeaponIntegerField(i: number): HUnitWeaponIntegerField;
declare function ConvertUnitWeaponRealField(i: number): HUnitWeaponRealField;
declare function ConvertUnitWeaponStringField(i: number): HUnitWeaponStringField;
declare function ConvertVariableType(i: number): HVariableType;
declare function CreateFrame(templateName: string, whichParent: HFrameHandle | null, priority: number, createContext: number): HFrameHandle;
declare function CreateFrameByType(frameType: string, name: string, whichParent: HFrameHandle | null, templateName: string, createContext: number): HFrameHandle;
declare function CreateMissile(missileTypeId: number): HMissile;
declare function CreateMissileEx(owner: HUnit | null, missileTypeId: number, attackIndex: number): HMissile;
declare function CreateSimpleFrame(templateName: string, whichParent: HFrameHandle | null, createContext: number): HFrameHandle;
declare function DestroyFrame(whichFrame: HFrameHandle | null): void;
declare function EnableOperationLimit(enable: boolean): void;
declare function EnableUnitAttack(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitAttackEx(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitInventory(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitInventoryEx(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitMovement(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitMovementEx(whichUnit: HUnit | null, enable: boolean): void;
declare function ExecuteCode(c: TCode): void;
declare function ExecuteFuncEx(funcName: string): void;
declare function ForceCountPlayers(whichForce: HForce | null): number;
declare function ForceHasPlayer(whichForce: HForce | null, whichPlayer: HPlayer | null): boolean;
declare function GetAbilityBackswing(whichAbility: HAbility | null): number;
declare function GetAbilityBaseCooldownById(aid: number, level: number): number;
declare function GetAbilityBaseManaCostById(aid: number, level: number): number;
declare function GetAbilityBaseSpellDetails(whichAbility: HAbility | null): number;
declare function GetAbilityBaseSpellDetailsById(aid: number): number;
declare function GetAbilityBaseTip(whichAbility: HAbility | null, level: number): string;
declare function GetAbilityBaseTipById(aid: number, level: number): string;
declare function GetAbilityBaseTypeId(whichAbility: HAbility | null): number;
declare function GetAbilityBaseUberTip(whichAbility: HAbility | null, level: number): string;
declare function GetAbilityBaseUberTipById(aid: number, level: number): string;
declare function GetAbilityBaseUnTip(whichAbility: HAbility | null, level: number): string;
declare function GetAbilityBaseUnTipById(aid: number, level: number): string;
declare function GetAbilityBaseUnUberTip(whichAbility: HAbility | null, level: number): string;
declare function GetAbilityBaseUnUberTipById(aid: number, level: number): string;
declare function GetAbilityButtonX(whichAbility: HAbility | null): number;
declare function GetAbilityButtonXById(aid: number): number;
declare function GetAbilityButtonY(whichAbility: HAbility | null): number;
declare function GetAbilityButtonYById(aid: number): number;
declare function GetAbilityCastPoint(whichAbility: HAbility | null): number;
declare function GetAbilityCastTime(whichAbility: HAbility | null): number;
declare function GetAbilityCooldown(whichAbility: HAbility | null): number;
declare function GetAbilityCooldownEx(whichAbility: HAbility | null): number;
declare function GetAbilityEffectSound(whichAbility: HAbility | null): string;
declare function GetAbilityEffectSoundById(aid: number): string;
declare function GetAbilityGlobalMessage(whichAbility: HAbility | null): string;
declare function GetAbilityGlobalMessageById(aid: number): string;
declare function GetAbilityGlobalSound(whichAbility: HAbility | null): string;
declare function GetAbilityGlobalSoundById(aid: number): string;
declare function GetAbilityHotkey(whichAbility: HAbility | null): HOsKeyType;
declare function GetAbilityHotkeyById(aid: number): HOsKeyType;
declare function GetAbilityIsMissileHoming(whichAbility: HAbility | null): boolean;
declare function GetAbilityIsMissileHomingById(aid: number): boolean;
declare function GetAbilityLevel(whichAbility: HAbility | null): number;
declare function GetAbilityMissileArc(whichAbility: HAbility | null): number;
declare function GetAbilityMissileArcById(aid: number): number;
declare function GetAbilityMissileSpeed(whichAbility: HAbility | null): number;
declare function GetAbilityMissileSpeedById(aid: number): number;
declare function GetAbilityOrder(whichAbility: HAbility | null): number;
declare function GetAbilityRemainingCooldown(whichAbility: HAbility | null): number;
declare function GetAbilityResearchButtonX(whichAbility: HAbility | null): number;
declare function GetAbilityResearchButtonXById(aid: number): number;
declare function GetAbilityResearchButtonY(whichAbility: HAbility | null): number;
declare function GetAbilityResearchButtonYById(aid: number): number;
declare function GetAbilityResearchHotkey(whichAbility: HAbility | null): HOsKeyType;
declare function GetAbilityResearchHotkeyById(aid: number): HOsKeyType;
declare function GetAbilityTypeId(whichAbility: HAbility | null): number;
declare function GetAbilityUnButtonX(whichAbility: HAbility | null): number;
declare function GetAbilityUnButtonXById(aid: number): number;
declare function GetAbilityUnButtonY(whichAbility: HAbility | null): number;
declare function GetAbilityUnButtonYById(aid: number): number;
declare function GetAbilityUnHotkey(whichAbility: HAbility | null): HOsKeyType;
declare function GetAbilityUnHotkeyById(aid: number): HOsKeyType;
declare function GetAxisZ(x: number, y: number): number;
declare function GetBuffLevel(whichBuff: HBuff | null): number;
declare function GetBuffRemainingDuration(whichBuff: HBuff | null): number;
declare function GetDestructableFacing(whichDestructable: HDestructable | null): number;
declare function GetDestructablePitch(whichDestructable: HDestructable | null): number;
declare function GetDestructablePositionLocation(whichDestructable: HDestructable | null): HLocation;
declare function GetDestructableRoll(whichDestructable: HDestructable | null): number;
declare function GetDestructableScale(whichDestructable: HDestructable | null): number;
declare function GetDestructableTimeScale(whichDestructable: HDestructable | null): number;
declare function GetDestructableVertexColour(whichDestructable: HDestructable | null): number;
declare function GetDestructableYaw(whichDestructable: HDestructable | null): number;
declare function GetEventAttackType(): HAttackType;
declare function GetEventDamageAbilityId(): number;
declare function GetEventDamageFlags(): number;
declare function GetEventDamageTarget(): HUnit;
declare function GetEventDamageType(): HDamageType;
declare function GetEventDamageTypeFlags(): number;
declare function GetEventIsAttack(): boolean;
declare function GetEventIsRanged(): boolean;
declare function GetEventPreDamage(): number;
declare function GetEventWeaponType(): HWeaponType;
declare function GetFirstUnitInSelection(whichPlayer: HPlayer | null): HUnit;
declare function GetFrameAlpha(whichFrame: HFrameHandle | null): number;
declare function GetFrameByName(frameName: string, createContext: number): HFrameHandle;
declare function GetFrameChild(whichFrame: HFrameHandle | null, index: number): HFrameHandle;
declare function GetFrameChildrenCount(whichFrame: HFrameHandle | null): number;
declare function GetFrameHeight(whichFrame: HFrameHandle | null): number;
declare function GetFrameName(whichFrame: HFrameHandle | null): string;
declare function GetFrameParent(whichFrame: HFrameHandle | null): HFrameHandle;
declare function GetFramePriority(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpriteColour(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpriteFacing(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpritePitch(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpriteRoll(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpriteScale(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpriteTimeScale(whichFrame: HFrameHandle | null): number;
declare function GetFrameSpriteYaw(whichFrame: HFrameHandle | null): number;
declare function GetFrameText(whichFrame: HFrameHandle | null): string;
declare function GetFrameTextSizeLimit(whichFrame: HFrameHandle | null): number;
declare function GetFrameValue(whichFrame: HFrameHandle | null): number;
declare function GetFrameWidth(whichFrame: HFrameHandle | null): number;
declare function GetHeroBasePrimaryStat(whichUnit: HUnit | null): HHeroAttribute;
declare function GetHeroBaseProperName(whichUnit: HUnit | null, nameIndex: number): string;
declare function GetHeroExperienceNeeded(whichUnit: HUnit | null, forLevel: number): number;
declare function GetHeroMaxLevelExperienceNeeded(whichUnit: HUnit | null): number;
declare function GetItemAbility(whichItem: HItem | null, abilityId: number): HAbility;
declare function GetItemAbilityByIndex(whichItem: HItem | null, abilityIndex: number): HAbility;
declare function GetItemBaseCharges(whichItem: HItem | null): number;
declare function GetItemBaseChargesById(itemId: number): number;
declare function GetItemBaseClassification(whichItem: HItem | null): number;
declare function GetItemBaseClassificationById(itemId: number): number;
declare function GetItemBaseCooldownId(whichItem: HItem | null): number;
declare function GetItemBaseCooldownIdById(itemId: number): number;
declare function GetItemBaseDescription(whichItem: HItem | null): string;
declare function GetItemBaseDescriptionById(itemId: number): string;
declare function GetItemBaseGoldCost(whichItem: HItem | null): number;
declare function GetItemBaseGoldCostById(itemId: number): number;
declare function GetItemBaseHotkey(whichItem: HItem | null): HOsKeyType;
declare function GetItemBaseHotkeyById(itemId: number): HOsKeyType;
declare function GetItemBaseIcon(whichItem: HItem | null): string;
declare function GetItemBaseIconById(itemId: number): string;
declare function GetItemBaseIsDroppable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsDroppableById(itemId: number): boolean;
declare function GetItemBaseIsDroppableOnDeath(whichItem: HItem | null): boolean;
declare function GetItemBaseIsDroppableOnDeathById(itemId: number): boolean;
declare function GetItemBaseIsIgnoreCooldown(whichItem: HItem | null): boolean;
declare function GetItemBaseIsIgnoreCooldownById(itemId: number): boolean;
declare function GetItemBaseIsMorph(whichItem: HItem | null): boolean;
declare function GetItemBaseIsMorphById(itemId: number): boolean;
declare function GetItemBaseIsPawnable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPawnableById(itemId: number): boolean;
declare function GetItemBaseIsPerishable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPerishableById(itemId: number): boolean;
declare function GetItemBaseIsPickRandom(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPickRandomById(itemId: number): boolean;
declare function GetItemBaseIsPowerUp(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPowerUpById(itemId: number): boolean;
declare function GetItemBaseIsSellable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsSellableById(itemId: number): boolean;
declare function GetItemBaseIsUsable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsUsableById(itemId: number): boolean;
declare function GetItemBaseLevel(whichItem: HItem | null): number;
declare function GetItemBaseLevelById(itemId: number): number;
declare function GetItemBaseLumberCost(whichItem: HItem | null): number;
declare function GetItemBaseLumberCostById(itemId: number): number;
declare function GetItemBaseName(whichItem: HItem | null): string;
declare function GetItemBaseNameById(itemId: number): string;
declare function GetItemBaseOldLevel(whichItem: HItem | null): number;
declare function GetItemBaseOldLevelById(itemId: number): number;
declare function GetItemBasePriority(whichItem: HItem | null): number;
declare function GetItemBasePriorityById(itemId: number): number;
declare function GetItemBaseStockMaximum(whichItem: HItem | null): number;
declare function GetItemBaseStockMaximumById(itemId: number): number;
declare function GetItemBaseStockReplenishInterval(whichItem: HItem | null): number;
declare function GetItemBaseStockReplenishIntervalById(itemId: number): number;
declare function GetItemBaseStockStartDelay(whichItem: HItem | null): number;
declare function GetItemBaseStockStartDelayById(itemId: number): number;
declare function GetItemBaseTip(whichItem: HItem | null): string;
declare function GetItemBaseTipById(itemId: number): string;
declare function GetItemBaseUberTip(whichItem: HItem | null): string;
declare function GetItemBaseUberTipById(itemId: number): string;
declare function GetItemCooldown(whichItem: HItem | null): number;
declare function GetItemFacing(whichItem: HItem | null): number;
declare function GetItemLife(whichItem: HItem | null): number;
declare function GetItemMaxLife(whichItem: HItem | null): number;
declare function GetItemPitch(whichItem: HItem | null): number;
declare function GetItemRemainingCooldown(whichItem: HItem | null): number;
declare function GetItemRoll(whichItem: HItem | null): number;
declare function GetItemScale(whichItem: HItem | null): number;
declare function GetItemTimeScale(whichItem: HItem | null): number;
declare function GetItemVertexColour(whichItem: HItem | null): number;
declare function GetItemYaw(whichItem: HItem | null): number;
declare function GetLocalTime(whichTimeType: HTimeType | null): number;
declare function GetMissileArc(whichMissile: HMissile | null): number;
declare function GetMissileAttackType(whichMissile: HMissile | null): HAttackType;
declare function GetMissileColour(whichMissile: HMissile | null): number;
declare function GetMissileDamage(whichMissile: HMissile | null): number;
declare function GetMissileDamageFlags(whichMissile: HMissile | null): number;
declare function GetMissileDamageType(whichMissile: HMissile | null): HDamageType;
declare function GetMissileFacing(whichMissile: HMissile | null): number;
declare function GetMissileHeight(whichMissile: HMissile | null): number;
declare function GetMissilePitch(whichMissile: HMissile | null): number;
declare function GetMissilePositionLocation(whichMissile: HMissile | null): HLocation;
declare function GetMissileRoll(whichMissile: HMissile | null): number;
declare function GetMissileScale(whichMissile: HMissile | null): number;
declare function GetMissileSource(whichMissile: HMissile | null): HUnit;
declare function GetMissileSpeed(whichMissile: HMissile | null): number;
declare function GetMissileTarget(whichMissile: HMissile | null): HWidget;
declare function GetMissileTargetDestructable(whichMissile: HMissile | null): HDestructable;
declare function GetMissileTargetItem(whichMissile: HMissile | null): HItem;
declare function GetMissileTargetUnit(whichMissile: HMissile | null): HUnit;
declare function GetMissileTimeScale(whichMissile: HMissile | null): number;
declare function GetMissileWeaponType(whichMissile: HMissile | null): HWeaponType;
declare function GetMissileX(whichMissile: HMissile | null): number;
declare function GetMissileY(whichMissile: HMissile | null): number;
declare function GetMissileYaw(whichMissile: HMissile | null): number;
declare function GetMissileZ(whichMissile: HMissile | null): number;
declare function GetMouseScreenPixelX(): number;
declare function GetMouseScreenPixelY(): number;
declare function GetMouseScreenX(): number;
declare function GetMouseScreenY(): number;
declare function GetMouseWorldX(): number;
declare function GetMouseWorldY(): number;
declare function GetMouseWorldZ(): number;
declare function GetOriginFrame(whichType: HOriginFrameType | null, index: number): HFrameHandle;
declare function GetSpecialEffectColour(whichEffect: HEffect | null): number;
declare function GetSpecialEffectFacing(whichEffect: HEffect | null): number;
declare function GetSpecialEffectHeight(whichEffect: HEffect | null): number;
declare function GetSpecialEffectPitch(whichEffect: HEffect | null): number;
declare function GetSpecialEffectPositionLocation(whichEffect: HEffect | null): HLocation;
declare function GetSpecialEffectRoll(whichEffect: HEffect | null): number;
declare function GetSpecialEffectScale(whichEffect: HEffect | null): number;
declare function GetSpecialEffectTimeScale(whichEffect: HEffect | null): number;
declare function GetSpecialEffectX(whichEffect: HEffect | null): number;
declare function GetSpecialEffectY(whichEffect: HEffect | null): number;
declare function GetSpecialEffectYaw(whichEffect: HEffect | null): number;
declare function GetSpecialEffectZ(whichEffect: HEffect | null): number;
declare function GetSyncSavedChildKey(): number;
declare function GetSyncSavedHashtable(): HHashTable;
declare function GetSyncSavedParentKey(): number;
declare function GetSyncSavedVariableType(): HVariableType;
declare function GetSyncedBoolean(): boolean;
declare function GetSyncedHandle(): HHandle;
declare function GetSyncedInteger(): number;
declare function GetSyncedReal(): number;
declare function GetSyncedString(): string;
declare function GetSyncedVariableName(): string;
declare function GetSyncedVariableType(): HVariableType;
declare function GetSystemTime(whichTimeType: HTimeType | null): number;
declare function GetTrackableColour(whichTrackable: HTrackable | null): number;
declare function GetTrackableFacing(whichTrackable: HTrackable | null): number;
declare function GetTrackableHeight(whichTrackable: HTrackable | null): number;
declare function GetTrackablePitch(whichTrackable: HTrackable | null): number;
declare function GetTrackablePositionLocation(whichTrackable: HTrackable | null): HLocation;
declare function GetTrackableRoll(whichTrackable: HTrackable | null): number;
declare function GetTrackableScale(whichTrackable: HTrackable | null): number;
declare function GetTrackableTimeScale(whichTrackable: HTrackable | null): number;
declare function GetTrackableX(whichTrackable: HTrackable | null): number;
declare function GetTrackableY(whichTrackable: HTrackable | null): number;
declare function GetTrackableYaw(whichTrackable: HTrackable | null): number;
declare function GetTrackableZ(whichTrackable: HTrackable | null): number;
declare function GetTriggerFrame(): HFrameHandle;
declare function GetTriggerFrameBoolean(): boolean;
declare function GetTriggerFrameEvent(): HFrameEventType;
declare function GetTriggerFrameInteger(): number;
declare function GetTriggerFrameReal(): number;
declare function GetTriggerFrameString(): string;
declare function GetTriggerFrameVariableType(): HVariableType;
declare function GetTriggerMissile(): HMissile;
declare function GetTriggerMissileSource(): HUnit;
declare function GetTriggerMissileTarget(): HWidget;
declare function GetTriggerMissileTargetDestructable(): HDestructable;
declare function GetTriggerMissileTargetItem(): HItem;
declare function GetTriggerMissileTargetUnit(): HUnit;
declare function GetTriggerPlayerIsKeyDown(): boolean;
declare function GetTriggerPlayerKey(): HOsKeyType;
declare function GetTriggerPlayerMetaKey(): number;
declare function GetTriggerPlayerMouseButton(): HMouseButtonType;
declare function GetTriggerPlayerMouseScreenX(): number;
declare function GetTriggerPlayerMouseScreenY(): number;
declare function GetTriggerPlayerMouseWorldX(): number;
declare function GetTriggerPlayerMouseWorldY(): number;
declare function GetTriggerPlayerMouseWorldZ(): number;
declare function GetTriggerSyncData(): string;
declare function GetTriggerSyncPrefix(): string;
declare function GetUnitAbility(whichUnit: HUnit | null, aid: number): HAbility;
declare function GetUnitAbilityByIndex(whichUnit: HUnit | null, index: number): HAbility;
declare function GetUnitArmour(whichUnit: HUnit | null): number;
declare function GetUnitArmourType(whichUnit: HUnit | null): HDefenseType;
declare function GetUnitAttackCooldownByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitAttackRangeByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitAttackSpeed(whichUnit: HUnit | null): number;
declare function GetUnitAttackTypeByIndex(whichUnit: HUnit | null, atttackIndex: number): HAttackType;
declare function GetUnitAttacksEnabledIndex(whichUnit: HUnit | null): number;
declare function GetUnitBackswingPointByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitBaseAwakenTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseAwakenTipById(unitTypeId: number): string;
declare function GetUnitBaseColour(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourA(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourAById(unitTypeId: number): number;
declare function GetUnitBaseColourB(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourBById(unitTypeId: number): number;
declare function GetUnitBaseColourById(unitTypeId: number): number;
declare function GetUnitBaseColourG(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourGById(unitTypeId: number): number;
declare function GetUnitBaseColourR(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourRById(unitTypeId: number): number;
declare function GetUnitBaseDamageByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitBaseDaySight(whichUnit: HUnit | null): number;
declare function GetUnitBaseDaySightById(unitTypeId: number): number;
declare function GetUnitBaseDescription(whichUnit: HUnit | null): string;
declare function GetUnitBaseDescriptionById(unitTypeId: number): string;
declare function GetUnitBaseGoldCost(whichUnit: HUnit | null): number;
declare function GetUnitBaseGoldCostById(unitTypeId: number): number;
declare function GetUnitBaseHotkey(whichUnit: HUnit | null): HOsKeyType;
declare function GetUnitBaseHotkeyById(unitTypeId: number): HOsKeyType;
declare function GetUnitBaseIcon(whichUnit: HUnit | null): string;
declare function GetUnitBaseIconById(unitTypeId: number): string;
declare function GetUnitBaseMissileArcById(unitTypeId: number, attackIndex: number): number;
declare function GetUnitBaseMissileArt(whichUnit: HUnit | null, attackIndex: number): string;
declare function GetUnitBaseMissileArtById(unitTypeId: number, attackIndex: number): string;
declare function GetUnitBaseMissileSpeed(whichUnit: HUnit | null, attackIndex: number): number;
declare function GetUnitBaseMissileSpeedById(unitTypeId: number, attackIndex: number): number;
declare function GetUnitBaseModel(whichUnit: HUnit | null): string;
declare function GetUnitBaseModelById(unitTypeId: number): string;
declare function GetUnitBaseName(whichUnit: HUnit | null): string;
declare function GetUnitBaseNameById(unitTypeId: number): string;
declare function GetUnitBaseNightSight(whichUnit: HUnit | null): number;
declare function GetUnitBaseNightSightById(unitTypeId: number): number;
declare function GetUnitBasePortrait(whichUnit: HUnit | null): string;
declare function GetUnitBasePortraitById(unitTypeId: number): string;
declare function GetUnitBasePrimaryStatById(unitTypeId: number): HHeroAttribute;
declare function GetUnitBaseProperNameById(unitTypeId: number, properNameIndex: number): string;
declare function GetUnitBaseReviveTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseReviveTipById(unitTypeId: number): string;
declare function GetUnitBaseSelectionScale(whichUnit: HUnit | null): number;
declare function GetUnitBaseSelectionScaleById(unitTypeId: number): number;
declare function GetUnitBaseShadowTex(whichUnit: HUnit | null): string;
declare function GetUnitBaseShadowTexById(unitTypeId: number): string;
declare function GetUnitBaseTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseTipById(unitTypeId: number): string;
declare function GetUnitBaseUberTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseUberTipById(unitTypeId: number): string;
declare function GetUnitBonusDamageByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitBonusMoveSpeedPercent(whichUnit: HUnit | null): number;
declare function GetUnitBuff(whichUnit: HUnit | null, buffId: number): HBuff;
declare function GetUnitBuffLevel(whichUnit: HUnit | null, buffId: number): number;
declare function GetUnitCurrentLife(whichUnit: HUnit | null): number;
declare function GetUnitCurrentMana(whichUnit: HUnit | null): number;
declare function GetUnitCurrentResources(whichUnit: HUnit | null): number;
declare function GetUnitCurrentSight(whichUnit: HUnit | null): number;
declare function GetUnitDamageDicesByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitDamageDicesSideByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitDamagePointByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitDamageReduction(whichUnit: HUnit | null): number;
declare function GetUnitEluneMagicResist(whichUnit: HUnit | null): number;
declare function GetUnitItemSlots(whichUnit: HUnit | null): number;
declare function GetUnitLifeRegen(whichUnit: HUnit | null): number;
declare function GetUnitLocustFlag(whichUnit: HUnit | null): number;
declare function GetUnitMagicResistByType(whichUnit: HUnit | null, resistType: number): number;
declare function GetUnitManaRegen(whichUnit: HUnit | null): number;
declare function GetUnitMaxLife(whichUnit: HUnit | null): number;
declare function GetUnitMaxMana(whichUnit: HUnit | null): number;
declare function GetUnitMinimapX(whichUnit: HUnit | null): number;
declare function GetUnitMinimapY(whichUnit: HUnit | null): number;
declare function GetUnitMoveAIType(whichUnit: HUnit | null): number;
declare function GetUnitMoveType(whichUnit: HUnit | null): number;
declare function GetUnitNextAttackTimeStampByIndex(whichUnit: HUnit | null, attackIndex: number): number;
declare function GetUnitPrimaryStat(whichUnit: HUnit | null): HHeroAttribute;
declare function GetUnitRunicMagicResist(whichUnit: HUnit | null): number;
declare function GetUnitSelected(whichPlayer: HPlayer | null): HUnit;
declare function GetUnitSelectedCountByPlayer(whichPlayer: HPlayer | null): number;
declare function GetUnitStunCounter(whichUnit: HUnit | null): number;
declare function GetUnitTimeScale(whichUnit: HUnit | null): number;
declare function GetUnitTotalMagicResist(whichUnit: HUnit | null): number;
declare function GetUnitTotalMoveSpeed(whichUnit: HUnit | null): number;
declare function GetUnitUnderCursor(): HUnit;
declare function GetUnitUnitBaseMoveSpeed(whichUnit: HUnit | null): number;
declare function GetUnitVertexColour(whichUnit: HUnit | null): number;
declare function GetUnitWeaponSoundByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitWeaponTypeByIndex(whichUnit: HUnit | null, atttackIndex: number): HWeaponType;
declare function GetWidgetFacing(whichWidget: HWidget | null): number;
declare function GetWidgetPitch(whichWidget: HWidget | null): number;
declare function GetWidgetPositionLocation(whichWidget: HWidget | null): HLocation;
declare function GetWidgetRoll(whichWidget: HWidget | null): number;
declare function GetWidgetScale(whichWidget: HWidget | null): number;
declare function GetWidgetTimeScale(whichWidget: HWidget | null): number;
declare function GetWidgetVertexColour(whichWidget: HWidget | null): number;
declare function GetWidgetYaw(whichWidget: HWidget | null): number;
declare function GroupAddGroupEx(destGroup: HGroup | null, sourceGroup: HGroup | null): number;
declare function GroupContainsUnit(whichGroup: HGroup | null, whichUnit: HUnit | null): boolean;
declare function GroupForEachUnit(whichGroup: HGroup | null): HUnit;
declare function GroupGetCount(whichGroup: HGroup | null): number;
declare function GroupGetUnitByIndex(whichGroup: HGroup | null, index: number): HUnit;
declare function GroupRemoveGroupEx(destGroup: HGroup | null, sourceGroup: HGroup | null): number;
declare function HandleToAIDifficulty(h: HHandle | null): HAIDifficulty;
declare function HandleToAbility(h: HHandle | null): HAbility;
declare function HandleToAddress(h: HHandle | null): number;
declare function HandleToAgent(h: HHandle | null): HAgent;
declare function HandleToAlliancetype(h: HHandle | null): HAllianceType;
declare function HandleToAnimType(h: HHandle | null): HAnimType;
declare function HandleToAttacktype(h: HHandle | null): HAttackType;
declare function HandleToBlendmode(h: HHandle | null): HBlendMode;
declare function HandleToBoolexpr(h: HHandle | null): HBoolExpr;
declare function HandleToBuff(h: HHandle | null): HBuff;
declare function HandleToButton(h: HHandle | null): HButton;
declare function HandleToCamerafield(h: HHandle | null): HCameraField;
declare function HandleToCamerasetup(h: HHandle | null): HCameraSetup;
declare function HandleToConditionfunc(h: HHandle | null): HConditionFunc;
declare function HandleToDamagetype(h: HHandle | null): HDamageType;
declare function HandleToDefeatcondition(h: HHandle | null): HDefeatCondition;
declare function HandleToDestructable(h: HHandle | null): HDestructable;
declare function HandleToDialog(h: HHandle | null): HDialog;
declare function HandleToDialogevent(h: HHandle | null): HDialogEvent;
declare function HandleToEffect(h: HHandle | null): HEffect;
declare function HandleToEffecttype(h: HHandle | null): HEffectType;
declare function HandleToEvent(h: HHandle | null): HEvent;
declare function HandleToEventid(h: HHandle | null): HEventId;
declare function HandleToFGamestate(h: HHandle | null): HFGameState;
declare function HandleToFilterfunc(h: HHandle | null): HFilterFunc;
declare function HandleToFogmodifier(h: HHandle | null): HFogModifier;
declare function HandleToFogstate(h: HHandle | null): HFogState;
declare function HandleToForce(h: HHandle | null): HForce;
declare function HandleToGamecache(h: HHandle | null): HGameCache;
declare function HandleToGamedifficulty(h: HHandle | null): HGameDifficulty;
declare function HandleToGameevent(h: HHandle | null): HGameEvent;
declare function HandleToGamespeed(h: HHandle | null): HGameSpeed;
declare function HandleToGamestate(h: HHandle | null): HGameState;
declare function HandleToGametype(h: HHandle | null): HGameType;
declare function HandleToGroup(h: HHandle | null): HGroup;
declare function HandleToHashtable(h: HHandle | null): HHashTable;
declare function HandleToIGamestate(h: HHandle | null): HIGameState;
declare function HandleToImage(h: HHandle | null): HImage;
declare function HandleToItem(h: HHandle | null): HItem;
declare function HandleToItempool(h: HHandle | null): HItemPool;
declare function HandleToItemtype(h: HHandle | null): HItemType;
declare function HandleToLeaderboard(h: HHandle | null): HLeaderBoard;
declare function HandleToLightning(h: HHandle | null): HLightning;
declare function HandleToLimitop(h: HHandle | null): HLimitop;
declare function HandleToLocation(h: HHandle | null): HLocation;
declare function HandleToMapcontrol(h: HHandle | null): HMapControl;
declare function HandleToMapdensity(h: HHandle | null): HMapDensity;
declare function HandleToMapflag(h: HHandle | null): HMapFlag;
declare function HandleToMapsetting(h: HHandle | null): HMapSetting;
declare function HandleToMapvisibility(h: HHandle | null): HMapVisibility;
declare function HandleToMultiboard(h: HHandle | null): HMultiBoard;
declare function HandleToMultiboarditem(h: HHandle | null): HMultiBoardItem;
declare function HandleToPathingtype(h: HHandle | null): HPathingType;
declare function HandleToPlacement(h: HHandle | null): HPlacement;
declare function HandleToPlayercolor(h: HHandle | null): HPlayerColor;
declare function HandleToPlayerevent(h: HHandle | null): HPlayerEvent;
declare function HandleToPlayergameresult(h: HHandle | null): HPlayerGameResult;
declare function HandleToPlayerscore(h: HHandle | null): HPlayerScore;
declare function HandleToPlayerslotstate(h: HHandle | null): HPlayerSlotState;
declare function HandleToPlayerstate(h: HHandle | null): HPlayerState;
declare function HandleToPlayerunitevent(h: HHandle | null): HPlayerunitEvent;
declare function HandleToQuest(h: HHandle | null): HQuest;
declare function HandleToQuestitem(h: HHandle | null): HQuestItem;
declare function HandleToRace(h: HHandle | null): HRace;
declare function HandleToRacepreference(h: HHandle | null): HRacePreference;
declare function HandleToRaritycontrol(h: HHandle | null): HRarityControl;
declare function HandleToRect(h: HHandle | null): HRect;
declare function HandleToRegion(h: HHandle | null): HRegion;
declare function HandleToSound(h: HHandle | null): HSound;
declare function HandleToSoundtype(h: HHandle | null): HSoundType;
declare function HandleToStartlocprio(h: HHandle | null): HStartLocPrio;
declare function HandleToSubAnimType(h: HHandle | null): HSubAnimType;
declare function HandleToTerraindeformation(h: HHandle | null): HTerrainDeformation;
declare function HandleToTexmapflags(h: HHandle | null): HTexMapFlags;
declare function HandleToTexttag(h: HHandle | null): HTextTag;
declare function HandleToTimer(h: HHandle | null): HTimer;
declare function HandleToTimerdialog(h: HHandle | null): HTimerDialog;
declare function HandleToTrackable(h: HHandle | null): HTrackable;
declare function HandleToTrigger(h: HHandle | null): HTrigger;
declare function HandleToTriggeraction(h: HHandle | null): HTriggerAction;
declare function HandleToTriggercondition(h: HHandle | null): HTriggerCondition;
declare function HandleToUbersplat(h: HHandle | null): HUberSplat;
declare function HandleToUnit(h: HHandle | null): HUnit;
declare function HandleToUnitevent(h: HHandle | null): HUnitEvent;
declare function HandleToUnitpool(h: HHandle | null): HUnitPool;
declare function HandleToUnitstate(h: HHandle | null): HUnitState;
declare function HandleToUnittype(h: HHandle | null): HUnitType;
declare function HandleToVersion(h: HHandle | null): HVersion;
declare function HandleToVolumegroup(h: HHandle | null): HVolumeGroup;
declare function HandleToWeapontype(h: HHandle | null): HWeaponType;
declare function HandleToWeathereffect(h: HHandle | null): HWeatherEffect;
declare function HandleToWidget(h: HHandle | null): HWidget;
declare function HandleToWidgetevent(h: HHandle | null): HwidgEtevent;
declare function I2C(i: number): TCode;
declare function Id2String(i: number): string;
declare function IntToHex(i: number): string;
declare function IntegerToHandle(i: number): HHandle;
declare function IsAbilityEnabled(whichAbility: HAbility | null): boolean;
declare function IsAbilityEnabledEx(whichAbility: HAbility | null): boolean;
declare function IsAbilityOnCooldown(whichAbility: HAbility | null): boolean;
declare function IsAbilityUsable(whichAbility: HAbility | null): boolean;
declare function IsAbilityVisible(whichAbility: HAbility | null): boolean;
declare function IsFrameEnabled(whichFrame: HFrameHandle | null): boolean;
declare function IsFrameVisible(whichFrame: HFrameHandle | null): boolean;
declare function IsMissileVisible(whichMissile: HMissile | null): boolean;
declare function IsOperationLimitEnabled(): boolean;
declare function IsSpecialEffectVisible(whichEffect: HEffect | null): boolean;
declare function IsTrackableVisible(whichTrackable: HTrackable | null): boolean;
declare function IsUnitAbilityVisible(whichUnit: HUnit | null, abilityId: number): boolean;
declare function IsUnitAlive(whichUnit: HUnit | null): boolean;
declare function IsUnitAttackEnabled(whichUnit: HUnit | null): boolean;
declare function IsUnitAttackEnabledEx(whichUnit: HUnit | null): boolean;
declare function IsUnitDead(whichUnit: HUnit | null): boolean;
declare function IsUnitGatherer(whichUnit: HUnit | null): boolean;
declare function IsUnitHero(whichUnit: HUnit | null): boolean;
declare function IsUnitInventoryEnabled(whichUnit: HUnit | null): boolean;
declare function IsUnitInventoryEnabledEx(whichUnit: HUnit | null): boolean;
declare function IsUnitInvulnerable(whichUnit: HUnit | null): boolean;
declare function IsUnitMovementEnabled(whichUnit: HUnit | null): boolean;
declare function IsUnitMovementEnabledEx(whichUnit: HUnit | null): boolean;
declare function IsUnitMoving(whichUnit: HUnit | null): boolean;
declare function IsUnitSelectable(whichUnit: HUnit | null): boolean;
declare function IsUnitShop(whichUnit: HUnit | null): boolean;
declare function IsUnitStateNormal(whichUnit: HUnit | null, additionalCheck: boolean): boolean;
declare function IsUnitStunned(whichUnit: HUnit | null): boolean;
declare function IsUnitTower(whichUnit: HUnit | null): boolean;
declare function IsWidgetInvulnerable(whichWidget: HWidget | null): boolean;
declare function IsWidgetVisible(whichWidget: HWidget | null): boolean;
declare function KillMissile(whichMissile: HMissile | null): void;
declare function LaunchMissile(whichMissile: HMissile | null): void;
declare function LaunchTargetMissile(whichMissile: HMissile | null, whichWidget: HWidget | null): void;
declare function LoadFrameHandle(table: HHashTable | null, parentKey: number, childKey: number): HFrameHandle;
declare function LoadMissileHandle(whichHashtable: HHashTable | null, parentKey: number, childKey: number): HMissile;
declare function LoadTOCFile(TOCFile: string): boolean;
declare function MathIntegerAbs(i: number): number;
declare function MathIntegerLn(i: number): number;
declare function MathIntegerLog(i: number): number;
declare function MathRealAbs(r: number): number;
declare function MathRealCeil(r: number): number;
declare function MathRealFloor(r: number): number;
declare function MathRealLn(r: number): number;
declare function MathRealLog(r: number): number;
declare function MathRealRound(r: number): number;
declare function MathRound(r: number): number;
declare function MorphUnitToTypeId(whichUnit: HUnit | null, uid: number): void;
declare function MorphUnitToTypeIdEx(whichUnit: HUnit | null, uid: number, unitFlags: number, updateHealthState: boolean, updateManaState: boolean, healthStateId: number, manaStateId: number, updateScale: boolean, replaceAbilities: boolean, whichAbility: HAbility | null, resetBuildingAnimation: boolean): void;
declare function PauseUnitEx(whichUnit: HUnit | null, flag: boolean): void;
declare function QueueDestructableAnimationByIndex(whichDestructable: HDestructable | null, animIndex: number): void;
declare function QueueFrameSpriteAnimation(whichFrame: HFrameHandle | null, animationName: string): void;
declare function QueueFrameSpriteAnimationByIndex(whichFrame: HFrameHandle | null, animIndex: number): void;
declare function QueueItemAnimation(whichItem: HItem | null, animation: string): void;
declare function QueueItemAnimationByIndex(whichItem: HItem | null, animIndex: number): void;
declare function QueueMissileAnimation(whichMissile: HMissile | null, animation: string): void;
declare function QueueMissileAnimationByIndex(whichMissile: HMissile | null, animIndex: number): void;
declare function QueueSpecialEffectAnimation(whichEffect: HEffect | null, animation: string): void;
declare function QueueSpecialEffectAnimationByIndex(whichEffect: HEffect | null, animIndex: number): void;
declare function QueueTrackableAnimation(whichTrackable: HTrackable | null, animation: string): void;
declare function QueueTrackableAnimationByIndex(whichTrackable: HTrackable | null, animIndex: number): void;
declare function QueueWidgetAnimation(whichWidget: HWidget | null, animation: string): void;
declare function QueueWidgetAnimationByIndex(whichWidget: HWidget | null, animIndex: number): void;
declare function RedrawUnit(whichUnit: HUnit | null): void;
declare function RefreshBuff(whichBuff: HBuff | null): boolean;
declare function ResetMissileMatrix(whichMissile: HMissile | null): void;
declare function ResetSpecialEffectetMatrix(whichEffect: HEffect | null): void;
declare function ResetTrackableetMatrix(whichTrackable: HTrackable | null): void;
declare function SaveFrameHandle(table: HHashTable | null, parentKey: number, childKey: number, whichFrame: HFrameHandle | null): boolean;
declare function SaveMissileHandle(whichHashtable: HHashTable | null, parentKey: number, childKey: number, whichMissile: HMissile | null): boolean;
declare function SendSyncData(prefix: string, data: string): boolean;
declare function SetAbilityBackswing(whichAbility: HAbility | null, backswing: number): void;
declare function SetAbilityBaseCooldownById(aid: number, level: number, cooldown: number): void;
declare function SetAbilityBaseManaCostById(aid: number, level: number, manaCost: number): void;
declare function SetAbilityBaseSpellDetails(whichAbility: HAbility | null, level: number): void;
declare function SetAbilityBaseSpellDetailsById(aid: number, level: number): void;
declare function SetAbilityBaseTip(whichAbility: HAbility | null, level: number, text: string): void;
declare function SetAbilityBaseTipById(aid: number, level: number, text: string): void;
declare function SetAbilityBaseUberTip(whichAbility: HAbility | null, level: number, text: string): void;
declare function SetAbilityBaseUberTipById(aid: number, level: number, text: string): void;
declare function SetAbilityBaseUnTip(whichAbility: HAbility | null, level: number, text: string): void;
declare function SetAbilityBaseUnTipById(aid: number, level: number, text: string): void;
declare function SetAbilityBaseUnUberTip(whichAbility: HAbility | null, level: number, text: string): void;
declare function SetAbilityBaseUnUberTipById(aid: number, level: number, text: string): void;
declare function SetAbilityButtonX(whichAbility: HAbility | null, positionX: number): void;
declare function SetAbilityButtonXById(aid: number, positionX: number): void;
declare function SetAbilityButtonY(whichAbility: HAbility | null, positionY: number): void;
declare function SetAbilityButtonYById(aid: number, positionY: number): void;
declare function SetAbilityCastPoint(whichAbility: HAbility | null, castPoint: number): void;
declare function SetAbilityCastTime(whichAbility: HAbility | null, castTime: number): void;
declare function SetAbilityCooldown(whichAbility: HAbility | null, cooldown: number): void;
declare function SetAbilityEffectSound(whichAbility: HAbility | null, text: string): void;
declare function SetAbilityEffectSoundById(aid: number, text: string): void;
declare function SetAbilityEnabled(whichAbility: HAbility | null, enable: boolean): void;
declare function SetAbilityEnabledEx(whichAbility: HAbility | null, enable: boolean): void;
declare function SetAbilityGlobalMessage(whichAbility: HAbility | null, text: string): void;
declare function SetAbilityGlobalMessageById(aid: number, text: string): void;
declare function SetAbilityGlobalSound(whichAbility: HAbility | null, text: string): void;
declare function SetAbilityGlobalSoundById(aid: number, text: string): void;
declare function SetAbilityHotkey(whichAbility: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityHotkeyById(aid: number, whichKey: HOsKeyType | null): void;
declare function SetAbilityHotkeyByIdEx(aid: number, whichKey: HOsKeyType | null): void;
declare function SetAbilityHotkeyEx(whichAbility: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityIsMissileHoming(whichAbility: HAbility | null, ishoming: boolean): void;
declare function SetAbilityIsMissileHomingById(aid: number, ishoming: boolean): void;
declare function SetAbilityMissileArc(whichAbility: HAbility | null, missileArc: number): void;
declare function SetAbilityMissileArcById(aid: number, missileArc: number): void;
declare function SetAbilityMissileSpeed(whichAbility: HAbility | null, missileSpeed: number): void;
declare function SetAbilityMissileSpeedById(aid: number, missileSpeed: number): void;
declare function SetAbilityResearchButtonX(whichAbility: HAbility | null, positionX: number): void;
declare function SetAbilityResearchButtonXById(aid: number, positionX: number): void;
declare function SetAbilityResearchButtonY(whichAbility: HAbility | null, positionY: number): void;
declare function SetAbilityResearchButtonYById(aid: number, positionY: number): void;
declare function SetAbilityResearchHotkey(whichAbility: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityResearchHotkeyById(aid: number, whichKey: HOsKeyType | null): void;
declare function SetAbilityUnButtonX(whichAbility: HAbility | null, positionX: number): void;
declare function SetAbilityUnButtonXById(aid: number, positionX: number): void;
declare function SetAbilityUnButtonY(whichAbility: HAbility | null, positionY: number): void;
declare function SetAbilityUnButtonYById(aid: number, positionY: number): void;
declare function SetAbilityUnHotkey(whichAbility: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityUnHotkeyById(aid: number, whichKey: HOsKeyType | null): void;
declare function SetBuffRemainingDuration(whichBuff: HBuff | null, duration: number): boolean;
declare function SetDestructableAnimationByIndex(whichDestructable: HDestructable | null, animIndex: number): void;
declare function SetDestructableAnimationWithRarity(whichDestructable: HDestructable | null, animation: string, rarity: HRarityControl | null): void;
declare function SetDestructableAnimationWithRarityByIndex(whichDestructable: HDestructable | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetDestructableFacing(whichDestructable: HDestructable | null, facing: number, isInstant: boolean): void;
declare function SetDestructableMaterialTexture(whichDestructable: HDestructable | null, textureName: string, materialId: number, textureIndex: number): void;
declare function SetDestructableModel(whichDestructable: HDestructable | null, modelFile: string): void;
declare function SetDestructableModelEx(whichDestructable: HDestructable | null, modelFile: string, playerId: number): void;
declare function SetDestructableOrientation(whichDestructable: HDestructable | null, yaw: number, pitch: number, roll: number): void;
declare function SetDestructablePitch(whichDestructable: HDestructable | null, pitch: number): void;
declare function SetDestructablePosition(whichDestructable: HDestructable | null, x: number, y: number): void;
declare function SetDestructablePositionLocation(whichDestructable: HDestructable | null, whichLocation: HLocation | null): void;
declare function SetDestructableReplaceableTexture(whichDestructable: HDestructable | null, textureName: string, textureIndex: number): void;
declare function SetDestructableRoll(whichDestructable: HDestructable | null, roll: number): void;
declare function SetDestructableScale(whichDestructable: HDestructable | null, scale: number): void;
declare function SetDestructableSpaceRotation(whichDestructable: HDestructable | null, yaw: number, pitch: number, roll: number, eulerOrder: number): void;
declare function SetDestructableTexture(whichDestructable: HDestructable | null, textureName: string, textureIndex: number): void;
declare function SetDestructableTimeScale(whichDestructable: HDestructable | null, timeScale: number): void;
declare function SetDestructableVertexColour(whichDestructable: HDestructable | null, red: number, green: number, blue: number, alpha: number): void;
declare function SetDestructableX(whichDestructable: HDestructable | null, x: number): void;
declare function SetDestructableY(whichDestructable: HDestructable | null, y: number): void;
declare function SetDestructableYaw(whichDestructable: HDestructable | null, yaw: number): void;
declare function SetEventAttackType(attackType: HAttackType | null): boolean;
declare function SetEventDamage(damage: number): void;
declare function SetEventDamageFlags(flags: number): boolean;
declare function SetEventDamageType(damageType: HDamageType | null): boolean;
declare function SetEventDamageTypeFlags(damageFlags: number): boolean;
declare function SetEventWeaponType(weaponType: HWeaponType | null): boolean;
declare function SetFrameAbsolutePoint(whichFrame: HFrameHandle | null, point: HFramePointType | null, x: number, y: number): void;
declare function SetFrameAllPoints(whichFrame: HFrameHandle | null, relativeFrame: HFrameHandle | null): void;
declare function SetFrameAlpha(whichFrame: HFrameHandle | null, alpha: number): void;
declare function SetFrameEnabled(whichFrame: HFrameHandle | null, enabled: boolean): void;
declare function SetFrameFocus(whichFrame: HFrameHandle | null, isFocus: boolean): void;
declare function SetFrameFont(whichFrame: HFrameHandle | null, fontName: string, size: number, flags: number): void;
declare function SetFrameMinMaxValues(whichFrame: HFrameHandle | null, minVal: number, maxVal: number): void;
declare function SetFrameModel(whichFrame: HFrameHandle | null, model: string, cameraIndex: number): void;
declare function SetFrameMouseCaged(whichFrame: HFrameHandle | null, enable: boolean): void;
declare function SetFrameParent(whichFrame: HFrameHandle | null, whichParent: HFrameHandle | null): void;
declare function SetFramePriority(whichFrame: HFrameHandle | null, priority: number): void;
declare function SetFrameRelativePoint(whichFrame: HFrameHandle | null, point: HFramePointType | null, relativeFrame: HFrameHandle | null, relativePoint: HFramePointType | null, x: number, y: number): void;
declare function SetFrameScale(whichFrame: HFrameHandle | null, scale: number): void;
declare function SetFrameSize(whichFrame: HFrameHandle | null, width: number, height: number): void;
declare function SetFrameSpriteAlpha(whichFrame: HFrameHandle | null, alpha: number): boolean;
declare function SetFrameSpriteAnimation(whichFrame: HFrameHandle | null, animationName: string): void;
declare function SetFrameSpriteAnimationByIndex(whichFrame: HFrameHandle | null, animIndex: number): void;
declare function SetFrameSpriteAnimationWithRarity(whichFrame: HFrameHandle | null, animationName: string, rarity: HRarityControl | null): void;
declare function SetFrameSpriteAnimationWithRarityByIndex(whichFrame: HFrameHandle | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetFrameSpriteColour(whichFrame: HFrameHandle | null, colour: number): boolean;
declare function SetFrameSpriteFacing(whichFrame: HFrameHandle | null, facing: number): boolean;
declare function SetFrameSpriteModel(whichFrame: HFrameHandle | null, modelName: string): void;
declare function SetFrameSpriteModelEx(whichFrame: HFrameHandle | null, modelName: string, playerColour: number): void;
declare function SetFrameSpriteOrientation(whichFrame: HFrameHandle | null, yaw: number, pitch: number, roll: number): void;
declare function SetFrameSpriteOrientationEx(whichFrame: HFrameHandle | null, yaw: number, pitch: number, roll: number, eulerOrder: number): boolean;
declare function SetFrameSpritePitch(whichFrame: HFrameHandle | null, pitch: number): boolean;
declare function SetFrameSpriteRoll(whichFrame: HFrameHandle | null, roll: number): boolean;
declare function SetFrameSpriteScale(whichFrame: HFrameHandle | null, scale: number): void;
declare function SetFrameSpriteTimeScale(whichFrame: HFrameHandle | null, timescale: number): void;
declare function SetFrameSpriteVertexColour(whichFrame: HFrameHandle | null, red: number, green: number, blue: number, alpha: number): boolean;
declare function SetFrameSpriteYaw(whichFrame: HFrameHandle | null, yaw: number): boolean;
declare function SetFrameStepSize(whichFrame: HFrameHandle | null, stepSize: number): void;
declare function SetFrameText(whichFrame: HFrameHandle | null, text: string): void;
declare function SetFrameTextAlignment(whichFrame: HFrameHandle | null, verticalAlign: HTextAlignType | null, horizontalAlign: HTextAlignType | null): void;
declare function SetFrameTextColour(whichFrame: HFrameHandle | null, colour: number): void;
declare function SetFrameTextSizeLimit(whichFrame: HFrameHandle | null, textSize: number): void;
declare function SetFrameTexture(whichFrame: HFrameHandle | null, textureFile: string, flag: number, blend: boolean): void;
declare function SetFrameTooltip(whichFrame: HFrameHandle | null, tooltipFrame: HFrameHandle | null): void;
declare function SetFrameValue(whichFrame: HFrameHandle | null, value: number): void;
declare function SetFrameVertexColour(whichFrame: HFrameHandle | null, colour: number): void;
declare function SetFrameVertexColourEx(whichFrame: HFrameHandle | null, alpha: number, red: number, blue: number, green: number): void;
declare function SetHeroBasePrimaryStat(whichUnit: HUnit | null, whichHeroAttribute: HHeroAttribute | null): void;
declare function SetHeroBaseProperName(whichUnit: HUnit | null, nameIndex: number, properName: string): void;
declare function SetItemAnimation(whichItem: HItem | null, animation: string): void;
declare function SetItemAnimationByIndex(whichItem: HItem | null, animIndex: number): void;
declare function SetItemAnimationWithRarity(whichItem: HItem | null, animation: string, rarity: HRarityControl | null): void;
declare function SetItemAnimationWithRarityByIndex(whichItem: HItem | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetItemBaseCharges(whichItem: HItem | null, charges: number): void;
declare function SetItemBaseChargesById(itemId: number, charges: number): void;
declare function SetItemBaseClassification(whichItem: HItem | null, classifictaionId: number): void;
declare function SetItemBaseClassificationById(itemId: number, classifictaionId: number): void;
declare function SetItemBaseCooldownId(whichItem: HItem | null, cooldownId: number): void;
declare function SetItemBaseCooldownIdById(itemId: number, cooldownId: number): void;
declare function SetItemBaseDescription(whichItem: HItem | null, name: string): void;
declare function SetItemBaseDescriptionById(itemId: number, name: string): void;
declare function SetItemBaseGoldCost(whichItem: HItem | null, goldcost: number): void;
declare function SetItemBaseGoldCostById(itemId: number, goldcost: number): void;
declare function SetItemBaseHotkey(whichItem: HItem | null, whichKey: HOsKeyType | null): void;
declare function SetItemBaseHotkeyById(itemId: number, whichKey: HOsKeyType | null): void;
declare function SetItemBaseIcon(whichItem: HItem | null, path: string): void;
declare function SetItemBaseIconById(itemId: number, path: string): void;
declare function SetItemBaseIsDroppable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsDroppableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsDroppableOnDeath(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsDroppableOnDeathById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsIgnoreCooldown(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsIgnoreCooldownById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsMorph(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsMorphById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPawnable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPawnableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPerishable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPerishableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPickRandom(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPickRandomById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPowerUp(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPowerUpById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsSellable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsSellableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsUsable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsUsableById(itemId: number, flag: boolean): void;
declare function SetItemBaseLevel(whichItem: HItem | null, level: number): void;
declare function SetItemBaseLevelById(itemId: number, level: number): void;
declare function SetItemBaseLumberCost(whichItem: HItem | null, lumbercost: number): void;
declare function SetItemBaseLumberCostById(itemId: number, lumbercost: number): void;
declare function SetItemBaseName(whichItem: HItem | null, name: string): void;
declare function SetItemBaseNameById(itemId: number, name: string): void;
declare function SetItemBaseOldLevel(whichItem: HItem | null, oldlevel: number): void;
declare function SetItemBaseOldLevelById(itemId: number, oldlevel: number): void;
declare function SetItemBasePriority(whichItem: HItem | null, priority: number): void;
declare function SetItemBasePriorityById(itemId: number, priority: number): void;
declare function SetItemBaseStockMaximum(whichItem: HItem | null, stockMax: number): void;
declare function SetItemBaseStockMaximumById(itemId: number, stockMax: number): void;
declare function SetItemBaseStockReplenishInterval(whichItem: HItem | null, replenishInterval: number): void;
declare function SetItemBaseStockReplenishIntervalById(itemId: number, replenishInterval: number): void;
declare function SetItemBaseStockStartDelay(whichItem: HItem | null, stockStartDelay: number): void;
declare function SetItemBaseStockStartDelayById(itemId: number, stockStartDelay: number): void;
declare function SetItemBaseTip(whichItem: HItem | null, tip: string): void;
declare function SetItemBaseTipById(itemId: number, tip: string): void;
declare function SetItemBaseUberTip(whichItem: HItem | null, tip: string): void;
declare function SetItemBaseUberTipById(itemId: number, tip: string): void;
declare function SetItemCooldown(whichItem: HItem | null, cooldown: number): void;
declare function SetItemFacing(whichItem: HItem | null, facing: number, isInstant: boolean): void;
declare function SetItemLife(whichItem: HItem | null, life: number): void;
declare function SetItemMaterialTexture(whichItem: HItem | null, textureName: string, materialId: number, textureIndex: number): void;
declare function SetItemMaxLife(whichItem: HItem | null, maxLife: number): void;
declare function SetItemModel(whichItem: HItem | null, modelFile: string): void;
declare function SetItemModelEx(whichItem: HItem | null, modelFile: string, playerColourId: number): void;
declare function SetItemOrientation(whichItem: HItem | null, yaw: number, pitch: number, roll: number): void;
declare function SetItemPitch(whichItem: HItem | null, pitch: number): void;
declare function SetItemRemainingCooldown(whichItem: HItem | null, cooldown: number): void;
declare function SetItemReplaceableTexture(whichItem: HItem | null, textureName: string, textureIndex: number): void;
declare function SetItemRoll(whichItem: HItem | null, roll: number): void;
declare function SetItemScale(whichItem: HItem | null, scale: number): void;
declare function SetItemSpaceRotation(whichItem: HItem | null, yaw: number, pitch: number, roll: number, eulerOrder: number): void;
declare function SetItemTexture(whichItem: HItem | null, textureName: string, textureIndex: number): void;
declare function SetItemTimeScale(whichItem: HItem | null, timeScale: number): void;
declare function SetItemVertexColour(whichItem: HItem | null, red: number, green: number, blue: number, alpha: number): void;
declare function SetItemYaw(whichItem: HItem | null, yaw: number): void;
declare function SetMissileAlpha(whichMissile: HMissile | null, alpha: number): boolean;
declare function SetMissileAnimation(whichMissile: HMissile | null, animation: string): void;
declare function SetMissileAnimationByIndex(whichMissile: HMissile | null, animIndex: number): void;
declare function SetMissileAnimationWithRarity(whichMissile: HMissile | null, animation: string, rarity: HRarityControl | null): void;
declare function SetMissileAnimationWithRarityByIndex(whichMissile: HMissile | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetMissileArc(whichMissile: HMissile | null, arc: number): void;
declare function SetMissileAttackType(whichMissile: HMissile | null, whichAttackType: HAttackType | null): void;
declare function SetMissileColour(whichMissile: HMissile | null, colour: number): boolean;
declare function SetMissileDamage(whichMissile: HMissile | null, damage: number): void;
declare function SetMissileDamageFlags(whichMissile: HMissile | null, flags: number): void;
declare function SetMissileDamageType(whichMissile: HMissile | null, whichDamageType: HDamageType | null): void;
declare function SetMissileFacing(whichMissile: HMissile | null, facing: number): boolean;
declare function SetMissileHeight(whichMissile: HMissile | null, height: number): void;
declare function SetMissileModel(whichMissile: HMissile | null, modelName: string): void;
declare function SetMissileModelEx(whichMissile: HMissile | null, modelName: string, playerColour: number): void;
declare function SetMissileOrientation(whichMissile: HMissile | null, yaw: number, pitch: number, roll: number): void;
declare function SetMissileOrientationEx(whichMissile: HMissile | null, yaw: number, pitch: number, roll: number, eulerOrder: number): boolean;
declare function SetMissilePitch(whichMissile: HMissile | null, pitch: number): boolean;
declare function SetMissilePosition(whichMissile: HMissile | null, x: number, y: number): void;
declare function SetMissilePositionLocation(whichMissile: HMissile | null, loc: HLocation | null): void;
declare function SetMissilePositionWithZ(whichMissile: HMissile | null, x: number, y: number, z: number): void;
declare function SetMissileRoll(whichMissile: HMissile | null, roll: number): boolean;
declare function SetMissileScale(whichMissile: HMissile | null, scale: number): void;
declare function SetMissileSource(whichMissile: HMissile | null, whichUnit: HUnit | null): void;
declare function SetMissileSpeed(whichMissile: HMissile | null, speed: number): void;
declare function SetMissileTarget(whichMissile: HMissile | null, whichWidget: HWidget | null): void;
declare function SetMissileTimeScale(whichMissile: HMissile | null, timescale: number): void;
declare function SetMissileUnitData(whichMissile: HMissile | null, owner: HUnit | null, attackIndex: number): void;
declare function SetMissileVertexColour(whichMissile: HMissile | null, red: number, green: number, blue: number, alpha: number): boolean;
declare function SetMissileVisible(whichMissile: HMissile | null, visibility: boolean): void;
declare function SetMissileWeaponType(whichMissile: HMissile | null, whichWeaponType: HWeaponType | null): void;
declare function SetMissileX(whichMissile: HMissile | null, x: number): void;
declare function SetMissileY(whichMissile: HMissile | null, y: number): void;
declare function SetMissileYaw(whichMissile: HMissile | null, yaw: number): boolean;
declare function SetMissileZ(whichMissile: HMissile | null, z: number): void;
declare function SetMouseScreenPixelPosition(x: number, y: number): void;
declare function SetMouseScreenPixelX(x: number): void;
declare function SetMouseScreenPixelY(y: number): void;
declare function SetMouseScreenPosition(x: number, y: number): void;
declare function SetMouseScreenX(x: number): void;
declare function SetMouseScreenY(y: number): void;
declare function SetSpecialEffectAlpha(whichEffect: HEffect | null, alpha: number): boolean;
declare function SetSpecialEffectAnimation(whichEffect: HEffect | null, animation: string): void;
declare function SetSpecialEffectAnimationByIndex(whichEffect: HEffect | null, animIndex: number): void;
declare function SetSpecialEffectAnimationWithRarity(whichEffect: HEffect | null, animation: string, rarity: HRarityControl | null): void;
declare function SetSpecialEffectAnimationWithRarityByIndex(whichEffect: HEffect | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetSpecialEffectColour(whichEffect: HEffect | null, colour: number): boolean;
declare function SetSpecialEffectFacing(whichEffect: HEffect | null, facing: number): boolean;
declare function SetSpecialEffectHeight(whichEffect: HEffect | null, height: number): void;
declare function SetSpecialEffectModel(whichEffect: HEffect | null, modelName: string): void;
declare function SetSpecialEffectModelEx(whichEffect: HEffect | null, modelName: string, playerColour: number): void;
declare function SetSpecialEffectOrientation(whichEffect: HEffect | null, yaw: number, pitch: number, roll: number): void;
declare function SetSpecialEffectOrientationEx(whichEffect: HEffect | null, yaw: number, pitch: number, roll: number, eulerOrder: number): boolean;
declare function SetSpecialEffectPitch(whichEffect: HEffect | null, pitch: number): boolean;
declare function SetSpecialEffectPosition(whichEffect: HEffect | null, x: number, y: number): void;
declare function SetSpecialEffectPositionEx(whichEffect: HEffect | null, x: number, y: number, z: number): void;
declare function SetSpecialEffectPositionLocation(whichEffect: HEffect | null, loc: HLocation | null): void;
declare function SetSpecialEffectRoll(whichEffect: HEffect | null, roll: number): boolean;
declare function SetSpecialEffectScale(whichEffect: HEffect | null, scale: number): void;
declare function SetSpecialEffectTimeScale(whichEffect: HEffect | null, timescale: number): void;
declare function SetSpecialEffectVertexColour(whichEffect: HEffect | null, red: number, green: number, blue: number, alpha: number): boolean;
declare function SetSpecialEffectVisibility(whichEffect: HEffect | null, visibility: boolean): void;
declare function SetSpecialEffectX(whichEffect: HEffect | null, x: number): void;
declare function SetSpecialEffectY(whichEffect: HEffect | null, y: number): void;
declare function SetSpecialEffectYaw(whichEffect: HEffect | null, yaw: number): boolean;
declare function SetSpecialEffectZ(whichEffect: HEffect | null, z: number): void;
declare function SetTrackableAlpha(whichTrackable: HTrackable | null, alpha: number): boolean;
declare function SetTrackableAnimation(whichTrackable: HTrackable | null, animation: string): void;
declare function SetTrackableAnimationByIndex(whichTrackable: HTrackable | null, animIndex: number): void;
declare function SetTrackableAnimationWithRarity(whichTrackable: HTrackable | null, animation: string, rarity: HRarityControl | null): void;
declare function SetTrackableAnimationWithRarityByIndex(whichTrackable: HTrackable | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetTrackableColour(whichTrackable: HTrackable | null, colour: number): boolean;
declare function SetTrackableFacing(whichTrackable: HTrackable | null, facing: number): boolean;
declare function SetTrackableHeight(whichTrackable: HTrackable | null, height: number): void;
declare function SetTrackableModel(whichTrackable: HTrackable | null, modelName: string): void;
declare function SetTrackableModelEx(whichTrackable: HTrackable | null, modelName: string, playerColour: number): void;
declare function SetTrackableOrientation(whichTrackable: HTrackable | null, yaw: number, pitch: number, roll: number): void;
declare function SetTrackableOrientationEx(whichTrackable: HTrackable | null, yaw: number, pitch: number, roll: number, eulerOrder: number): boolean;
declare function SetTrackablePitch(whichTrackable: HTrackable | null, pitch: number): boolean;
declare function SetTrackablePosition(whichTrackable: HTrackable | null, x: number, y: number): void;
declare function SetTrackablePositionEx(whichTrackable: HTrackable | null, x: number, y: number, z: number): void;
declare function SetTrackablePositionLocation(whichTrackable: HTrackable | null, loc: HLocation | null): void;
declare function SetTrackableRoll(whichTrackable: HTrackable | null, roll: number): boolean;
declare function SetTrackableScale(whichTrackable: HTrackable | null, scale: number): void;
declare function SetTrackableTimeScale(whichTrackable: HTrackable | null, timescale: number): void;
declare function SetTrackableVertexColour(whichTrackable: HTrackable | null, red: number, green: number, blue: number, alpha: number): boolean;
declare function SetTrackableVisibility(whichTrackable: HTrackable | null, visibility: boolean): void;
declare function SetTrackableX(whichTrackable: HTrackable | null, x: number): void;
declare function SetTrackableY(whichTrackable: HTrackable | null, y: number): void;
declare function SetTrackableYaw(whichTrackable: HTrackable | null, yaw: number): boolean;
declare function SetTrackableZ(whichTrackable: HTrackable | null, z: number): void;
declare function SetUnitArmour(whichUnit: HUnit | null, armour: number): void;
declare function SetUnitArmourType(whichUnit: HUnit | null, whichArmour: HDefenseType | null): void;
declare function SetUnitAttackCooldownByIndex(whichUnit: HUnit | null, atttackIndex: number, attackCooldown: number): void;
declare function SetUnitAttackRangeByIndex(whichUnit: HUnit | null, atttackIndex: number, range: number): void;
declare function SetUnitAttackSpeed(whichUnit: HUnit | null, attackSpeed: number): void;
declare function SetUnitAttackState(whichUnit: HUnit | null, atttackIndex: number, attackState: number): number;
declare function SetUnitAttackTypeByIndex(whichUnit: HUnit | null, atttackIndex: number, whichAttackType: HAttackType | null): void;
declare function SetUnitBackswingPointByIndex(whichUnit: HUnit | null, atttackIndex: number, backswing: number): void;
declare function SetUnitBaseAwakenTip(whichUnit: HUnit | null, awakenTip: string): void;
declare function SetUnitBaseAwakenTipById(unitTypeId: number, awakenTip: string): void;
declare function SetUnitBaseColour(whichUnit: HUnit | null, colour: number): void;
declare function SetUnitBaseColourA(whichUnit: HUnit | null, alpha: number): void;
declare function SetUnitBaseColourAById(unitTypeId: number, colourA: number): void;
declare function SetUnitBaseColourB(whichUnit: HUnit | null, blue: number): void;
declare function SetUnitBaseColourBById(unitTypeId: number, colourB: number): void;
declare function SetUnitBaseColourById(unitTypeId: number, colour: number): void;
declare function SetUnitBaseColourG(whichUnit: HUnit | null, green: number): void;
declare function SetUnitBaseColourGById(unitTypeId: number, colourG: number): void;
declare function SetUnitBaseColourR(whichUnit: HUnit | null, red: number): void;
declare function SetUnitBaseColourRById(unitTypeId: number, colourR: number): void;
declare function SetUnitBaseDamageByIndex(whichUnit: HUnit | null, atttackIndex: number, damage: number): void;
declare function SetUnitBaseDaySight(whichUnit: HUnit | null, dsight: number): void;
declare function SetUnitBaseDaySightById(unitTypeId: number, daySight: number): void;
declare function SetUnitBaseDescription(whichUnit: HUnit | null, name: string): void;
declare function SetUnitBaseDescriptionById(unitTypeId: number, name: string): void;
declare function SetUnitBaseGoldCost(whichUnit: HUnit | null, goldCost: number): void;
declare function SetUnitBaseGoldCostById(unitTypeId: number, goldCost: number): void;
declare function SetUnitBaseHotkey(whichUnit: HUnit | null, whichKey: HOsKeyType | null): void;
declare function SetUnitBaseHotkeyById(unitTypeId: number, whichKey: HOsKeyType | null): void;
declare function SetUnitBaseIcon(whichUnit: HUnit | null, name: string): void;
declare function SetUnitBaseIconById(unitTypeId: number, name: string): void;
declare function SetUnitBaseMissileArcById(unitTypeId: number, attackIndex: number, realValue: number): void;
declare function SetUnitBaseMissileArt(whichUnit: HUnit | null, attackIndex: number, missleArt: string): void;
declare function SetUnitBaseMissileArtById(unitTypeId: number, attackIndex: number, missleArt: string): void;
declare function SetUnitBaseMissileSpeed(whichUnit: HUnit | null, attackIndex: number, missleSpeed: number): void;
declare function SetUnitBaseMissileSpeedById(unitTypeId: number, attackIndex: number, realValue: number): void;
declare function SetUnitBaseModel(whichUnit: HUnit | null, model: string): void;
declare function SetUnitBaseModelById(unitTypeId: number, modelName: string): void;
declare function SetUnitBaseName(whichUnit: HUnit | null, name: string): void;
declare function SetUnitBaseNameById(unitTypeId: number, name: string): void;
declare function SetUnitBaseNightSight(whichUnit: HUnit | null, nsight: number): void;
declare function SetUnitBaseNightSightById(unitTypeId: number, nightSight: number): void;
declare function SetUnitBasePortrait(whichUnit: HUnit | null, portrait: string): void;
declare function SetUnitBasePortraitById(unitTypeId: number, portraitName: string): void;
declare function SetUnitBasePrimaryStatById(unitTypeId: number, whichHeroAttribute: HHeroAttribute | null): void;
declare function SetUnitBaseProperNameById(unitTypeId: number, properNameIndex: number, properName: string): void;
declare function SetUnitBaseReviveTip(whichUnit: HUnit | null, revivetip: string): void;
declare function SetUnitBaseReviveTipById(unitTypeId: number, reviveTip: string): void;
declare function SetUnitBaseSelectionScale(whichUnit: HUnit | null, selectionScale: number): void;
declare function SetUnitBaseSelectionScaleById(unitTypeId: number, realValue: number): void;
declare function SetUnitBaseShadowTex(whichUnit: HUnit | null, shadowTexture: string): void;
declare function SetUnitBaseShadowTexById(unitTypeId: number, shadowTexture: string): void;
declare function SetUnitBaseTip(whichUnit: HUnit | null, tip: string): void;
declare function SetUnitBaseTipById(unitTypeId: number, tip: string): void;
declare function SetUnitBaseUberTip(whichUnit: HUnit | null, ubertip: string): void;
declare function SetUnitBaseUberTipById(unitTypeId: number, uberTip: string): void;
declare function SetUnitBonusDamageByIndex(whichUnit: HUnit | null, atttackIndex: number, bonusDamage: number): void;
declare function SetUnitBonusMoveSpeedPercent(whichUnit: HUnit | null, bonusMoveSpeedPercent: number): void;
declare function SetUnitControl(whichUnit: HUnit | null, flagValue: number, isSetFlagValue: boolean, ismove: boolean, isattack: boolean, isinventory: boolean): void;
declare function SetUnitCurrentLife(whichUnit: HUnit | null, life: number): void;
declare function SetUnitCurrentMana(whichUnit: HUnit | null, mana: number): void;
declare function SetUnitCurrentSight(whichUnit: HUnit | null, realValue: number): void;
declare function SetUnitDamageDicesByIndex(whichUnit: HUnit | null, atttackIndex: number, dices: number): void;
declare function SetUnitDamageDicesSideByIndex(whichUnit: HUnit | null, atttackIndex: number, dicesSides: number): void;
declare function SetUnitDamagePointByIndex(whichUnit: HUnit | null, atttackIndex: number, damagePoint: number): void;
declare function SetUnitFacingEx(whichUnit: HUnit | null, facing: number, isInstant: boolean): void;
declare function SetUnitFacingInstant(whichUnit: HUnit | null, facing: number): void;
declare function SetUnitItemSlots(whichUnit: HUnit | null, itemSlots: number): void;
declare function SetUnitLifeRegen(whichUnit: HUnit | null, lifeRegen: number): void;
declare function SetUnitLocustFlag(whichUnit: HUnit | null, flag: number, mode: number): void;
declare function SetUnitManaRegen(whichUnit: HUnit | null, manaRegen: number): void;
declare function SetUnitMaterialTexture(whichUnit: HUnit | null, textureName: string, materialId: number, textureIndex: number): void;
declare function SetUnitMaxLife(whichUnit: HUnit | null, maxLife: number): void;
declare function SetUnitMaxMana(whichUnit: HUnit | null, maxMana: number): void;
declare function SetUnitModel(whichUnit: HUnit | null, modelName: string): void;
declare function SetUnitModelEx(whichUnit: HUnit | null, modelName: string, playercolourId: number): void;
declare function SetUnitMoveAIType(whichUnit: HUnit | null, moveAIType: number): void;
declare function SetUnitMoveType(whichUnit: HUnit | null, moveType: number): void;
declare function SetUnitMoveTypeByIndex(whichUnit: HUnit | null, moveIndex: number): void;
declare function SetUnitNextAttackTimeStampByIndex(whichUnit: HUnit | null, attackIndex: number, time: number): void;
declare function SetUnitPrimaryStat(whichUnit: HUnit | null, whichHeroAttribute: HHeroAttribute | null): void;
declare function SetUnitReplaceableTexture(whichUnit: HUnit | null, textureName: string, textureIndex: number): void;
declare function SetUnitSelectable(whichUnit: HUnit | null, selectable: boolean): void;
declare function SetUnitStunCounter(whichUnit: HUnit | null, stunCounter: number): void;
declare function SetUnitStunned(whichUnit: HUnit | null, state: boolean): void;
declare function SetUnitTexture(whichUnit: HUnit | null, textureName: string, textureIndex: number): void;
declare function SetUnitTruesightImmuneState(whichUnit: HUnit | null, state: boolean): void;
declare function SetUnitTypeId(whichUnit: HUnit | null, newId: number): void;
declare function SetUnitUnitBaseMoveSpeed(whichUnit: HUnit | null, baseMoveSpeed: number): void;
declare function SetUnitWeaponSoundByIndex(whichUnit: HUnit | null, atttackIndex: number, weaponSound: number): void;
declare function SetUnitWeaponTypeByIndex(whichUnit: HUnit | null, atttackIndex: number, whichWeaponType: HWeaponType | null): void;
declare function SetWidgetAnimation(whichWidget: HWidget | null, animation: string): void;
declare function SetWidgetAnimationByIndex(whichWidget: HWidget | null, animIndex: number): void;
declare function SetWidgetAnimationWithRarity(whichWidget: HWidget | null, animation: string, rarity: HRarityControl | null): void;
declare function SetWidgetAnimationWithRarityByIndex(whichWidget: HWidget | null, animIndex: number, rarity: HRarityControl | null): void;
declare function SetWidgetFacing(whichWidget: HWidget | null, facing: number, isInstant: boolean): void;
declare function SetWidgetInvulnerable(whichWidget: HWidget | null, invulnerable: boolean): void;
declare function SetWidgetMaterialTexture(whichWidget: HWidget | null, textureName: string, materialId: number, textureIndex: number): void;
declare function SetWidgetModel(whichWidget: HWidget | null, modelFile: string): void;
declare function SetWidgetModelEx(whichWidget: HWidget | null, modelFile: string, playerId: number): void;
declare function SetWidgetOrientation(whichWidget: HWidget | null, yaw: number, pitch: number, roll: number): void;
declare function SetWidgetPitch(whichWidget: HWidget | null, pitch: number): void;
declare function SetWidgetPosition(whichWidget: HWidget | null, x: number, y: number): void;
declare function SetWidgetPositionLocation(whichWidget: HWidget | null, whichLocation: HLocation | null): void;
declare function SetWidgetReplaceableTexture(whichWidget: HWidget | null, textureName: string, textureIndex: number): void;
declare function SetWidgetRoll(whichWidget: HWidget | null, roll: number): void;
declare function SetWidgetScale(whichWidget: HWidget | null, scale: number): void;
declare function SetWidgetSpaceRotation(whichWidget: HWidget | null, yaw: number, pitch: number, roll: number, eulerOrder: number): void;
declare function SetWidgetTexture(whichWidget: HWidget | null, textureName: string, textureIndex: number): void;
declare function SetWidgetTimeScale(whichWidget: HWidget | null, timeScale: number): void;
declare function SetWidgetVertexColour(whichWidget: HWidget | null, red: number, green: number, blue: number, alpha: number): void;
declare function SetWidgetVisible(whichWidget: HWidget | null, visible: boolean): void;
declare function SetWidgetX(whichWidget: HWidget | null, x: number): void;
declare function SetWidgetY(whichWidget: HWidget | null, y: number): void;
declare function SetWidgetYaw(whichWidget: HWidget | null, yaw: number): void;
declare function ShowAbility(whichAbility: HAbility | null, show: boolean): void;
declare function ShowFrame(whichFrame: HFrameHandle | null, isShow: boolean): void;
declare function ShowUnitAbility(whichUnit: HUnit | null, abilityId: number, show: boolean): void;
declare function SilenceAbility(whichAbility: HAbility | null, hide: boolean, disable: boolean): void;
declare function StartAbilityCooldown(whichAbility: HAbility | null, cooldown: number): boolean;
declare function StartItemCooldown(whichUnit: HUnit | null, whichItem: HItem | null, cooldown: number): void;
declare function String2Id(idString: string): number;
declare function StringContains(s: string, whichString: string, caseSensitive: boolean): boolean;
declare function StringFind(s: string, whichString: string, caseSensitive: boolean): number;
declare function StringFindFirstNotOf(s: string, whichString: string, caseSensitive: boolean): number;
declare function StringFindFirstOf(s: string, whichString: string, caseSensitive: boolean): number;
declare function StringFindLastNotOf(s: string, whichString: string, caseSensitive: boolean): number;
declare function StringFindLastOf(s: string, whichString: string, caseSensitive: boolean): number;
declare function SyncBoolean(variableName: string): void;
declare function SyncHandle(variableName: string): void;
declare function SyncInteger(variableName: string): void;
declare function SyncReal(variableName: string): void;
declare function SyncSavedBoolean(table: HHashTable | null, parentKey: number, childKey: number): void;
declare function SyncSavedHandle(table: HHashTable | null, parentKey: number, childKey: number): void;
declare function SyncSavedInteger(table: HHashTable | null, parentKey: number, childKey: number): void;
declare function SyncSavedReal(table: HHashTable | null, parentKey: number, childKey: number): void;
declare function SyncSavedString(table: HHashTable | null, parentKey: number, childKey: number): void;
declare function SyncString(variableName: string): void;
declare function TriggerRegisterFrameEvent(whichTrigger: HTrigger | null, whichFrame: HFrameHandle | null, frameEvent: HFrameEventType | null): HEvent;
declare function TriggerRegisterPlayerHashtableDataSyncEvent(whichTrigger: HTrigger | null, whichPlayer: HPlayer | null, whichHashtable: HHashTable | null): HEvent;
declare function TriggerRegisterPlayerKeyEvent(whichTrigger: HTrigger | null, whichPlayer: HPlayer | null, whichKey: HOsKeyType | null, whichMetaKey: number, isKeyDown: boolean): HEvent;
declare function TriggerRegisterPlayerMissileEvent(whichTrigger: HTrigger | null, whichPlayer: HPlayer | null, whichMissileEvent: HPlayerMissileEvent | null): HEvent;
declare function TriggerRegisterPlayerSyncEvent(whichTrigger: HTrigger | null, whichPlayer: HPlayer | null, prefix: string, fromServer: boolean): HEvent;
declare function TriggerRegisterPlayerVariableSyncEvent(whichTrigger: HTrigger | null, whichPlayer: HPlayer | null, variableName: string): HEvent;
declare function UnitAddAbilityEx(whichUnit: HUnit | null, abilityId: number, checkForDuplicates: boolean): boolean;
declare function UnitAddExtraAttackByIndex(whichUnit: HUnit | null, atttackIndex: number): boolean;
declare function UnitApplySilence(whichUnit: HUnit | null, state: boolean): void;
declare function UnitApplyUpdates(whichUnit: HUnit | null): number;
declare function UnitCancelCurrentAttackByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function UnitDisableAbilities(whichUnit: HUnit | null, state: boolean): void;
declare function UnitRemoveAbilityEx(whichUnit: HUnit | null, abilityId: number, removeDuplicates: boolean): boolean;
declare function UnitResetAttackCooldownByIndex(whichUnit: HUnit | null, atttackIndex: number): boolean;
declare function UnitUnapplyUpdates(whichUnit: HUnit | null): number;
declare function UnsilenceAbility(whichAbility: HAbility | null, show: boolean, enable: boolean): void;
declare function UpdateUnitInfoBar(whichUnit: HUnit | null): number;
