/** @noSelfInFile **/

declare function AddFrameText(whichFrame: HFrameHandle | null, text: string): void;
declare function AddressToHandle(i: number): HHandle;
declare function CastAbility(abil: HAbility | null): boolean;
declare function CastAbilityGround(abil: HAbility | null, source: HUnit | null, targX: number, targY: number): boolean;
declare function CastAbilityTarget(abil: HAbility | null, target: HUnit | null): boolean;
declare function ClearFrameAllPoints(whichFrame: HFrameHandle | null): void;
declare function ClickFrame(whichFrame: HFrameHandle | null): void;
declare function ClickFrameEx(whichFrame: HFrameHandle | null, isRightClick: boolean): void;
declare function ConvertAnimType(i: number): HAnimType;
declare function ConvertArmorType(i: number): HArmorType;
declare function ConvertColour(alpha: number, red: number, green: number, blue: number): number;
declare function ConvertDefenseType(i: number): HDefenseType;
declare function ConvertFrameEventType(i: number): HFrameEventType;
declare function ConvertFramePointType(i: number): HFramePointType;
declare function ConvertHeroAttribute(i: number): HHeroAttribute;
declare function ConvertMoveType(i: number): HMoveType;
declare function ConvertOriginFrameType(i: number): HOriginFrameType;
declare function ConvertOsKeyType(i: number): HOsKeyType;
declare function ConvertPathingFlag(i: number): HPathingFlag;
declare function ConvertRegenType(i: number): HRegenType;
declare function ConvertSubAnimType(i: number): HSubAnimType;
declare function ConvertTargetFlag(i: number): HTargetFlag;
declare function ConvertTextAlignType(i: number): HTextAlignType;
declare function ConvertUnitCategory(i: number): HUnitCategory;
declare function CreateFrame(templateName: string, whichParent: HFrameHandle | null, priority: number, createContext: number): HFrameHandle;
declare function CreateFrameByType(frameType: string, name: string, whichParent: HFrameHandle | null, templateName: string, createContext: number): HFrameHandle;
declare function CreateSimpleFrame(templateName: string, whichParent: HFrameHandle | null, createContext: number): HFrameHandle;
declare function DestroyFrame(whichFrame: HFrameHandle | null): void;
declare function EnableUnitAttack(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitAttackEx(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitInventory(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitInventoryEx(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitMovement(whichUnit: HUnit | null, enable: boolean): void;
declare function EnableUnitMovementEx(whichUnit: HUnit | null, enable: boolean): void;
declare function ForceCountPlayers(whichForce: HForce | null): number;
declare function ForceHasPlayer(whichForce: HForce | null, whichPlayer: HPlayer | null): boolean;
declare function GetAbilityBackswing(abil: HAbility | null): number;
declare function GetAbilityBaseCooldownById(aid: number, level: number): number;
declare function GetAbilityBaseManaCostById(aid: number, level: number): number;
declare function GetAbilityBaseSpellDetails(abil: HAbility | null): number;
declare function GetAbilityBaseSpellDetailsById(aid: number): number;
declare function GetAbilityBaseTip(abil: HAbility | null, level: number): string;
declare function GetAbilityBaseTipById(aid: number, level: number): string;
declare function GetAbilityBaseTypeId(abil: HAbility | null): number;
declare function GetAbilityBaseUberTip(abil: HAbility | null, level: number): string;
declare function GetAbilityBaseUberTipById(aid: number, level: number): string;
declare function GetAbilityBaseUnTip(abil: HAbility | null, level: number): string;
declare function GetAbilityBaseUnTipById(aid: number, level: number): string;
declare function GetAbilityBaseUnUberTip(abil: HAbility | null, level: number): string;
declare function GetAbilityBaseUnUberTipById(aid: number, level: number): string;
declare function GetAbilityButtonX(abil: HAbility | null): number;
declare function GetAbilityButtonXById(aid: number): number;
declare function GetAbilityButtonY(abil: HAbility | null): number;
declare function GetAbilityButtonYById(aid: number): number;
declare function GetAbilityCastPoint(abil: HAbility | null): number;
declare function GetAbilityCastTime(abil: HAbility | null): number;
declare function GetAbilityCooldown(abil: HAbility | null): number;
declare function GetAbilityCooldownEx(abil: HAbility | null): number;
declare function GetAbilityEffectSound(abil: HAbility | null): string;
declare function GetAbilityEffectSoundById(aid: number): string;
declare function GetAbilityGlobalMessage(abil: HAbility | null): string;
declare function GetAbilityGlobalMessageById(aid: number): string;
declare function GetAbilityGlobalSound(abil: HAbility | null): string;
declare function GetAbilityGlobalSoundById(aid: number): string;
declare function GetAbilityHotkey(abil: HAbility | null): HOsKeyType;
declare function GetAbilityHotkeyById(aid: number): HOsKeyType;
declare function GetAbilityIsMissileHoming(abil: HAbility | null): boolean;
declare function GetAbilityIsMissileHomingById(aid: number): boolean;
declare function GetAbilityLevel(abil: HAbility | null): number;
declare function GetAbilityMissileArc(abil: HAbility | null): number;
declare function GetAbilityMissileArcById(aid: number): number;
declare function GetAbilityMissileSpeed(abil: HAbility | null): number;
declare function GetAbilityMissileSpeedById(aid: number): number;
declare function GetAbilityOrder(abil: HAbility | null): number;
declare function GetAbilityRemainingCooldown(abil: HAbility | null): number;
declare function GetAbilityResearchButtonX(abil: HAbility | null): number;
declare function GetAbilityResearchButtonXById(aid: number): number;
declare function GetAbilityResearchButtonY(abil: HAbility | null): number;
declare function GetAbilityResearchButtonYById(aid: number): number;
declare function GetAbilityResearchHotkey(abil: HAbility | null): HOsKeyType;
declare function GetAbilityResearchHotkeyById(aid: number): HOsKeyType;
declare function GetAbilityTypeId(abil: HAbility | null): number;
declare function GetAbilityUnButtonX(abil: HAbility | null): number;
declare function GetAbilityUnButtonXById(aid: number): number;
declare function GetAbilityUnButtonY(abil: HAbility | null): number;
declare function GetAbilityUnButtonYById(aid: number): number;
declare function GetAbilityUnHotkey(abil: HAbility | null): HOsKeyType;
declare function GetAbilityUnHotkeyById(aid: number): HOsKeyType;
declare function GetBuffLevel(whichBuff: HBuff | null): number;
declare function GetBuffRemainingDuration(whichBuff: HBuff | null): number;
declare function GetEventAttackType(): HAttackType;
declare function GetEventDamageAbilityId(): number;
declare function GetEventDamageFlags(): number;
declare function GetEventDamageTarget(): HUnit;
declare function GetEventDamageType(): HDamageType;
declare function GetEventDamageTypeFlags(): number;
declare function GetEventIsAttack(): boolean;
declare function GetEventIsRanged(): boolean;
declare function GetEventWeaponType(): HWeaponType;
declare function GetFirstUnitInSelection(whichPlayer: HPlayer | null): HUnit;
declare function GetFrameAlpha(whichFrame: HFrameHandle | null): number;
declare function GetFrameByName(frameName: string, createContext: number): HFrameHandle;
declare function GetFrameChild(whichFrame: HFrameHandle | null, index: number): HFrameHandle;
declare function GetFrameChildrenCount(whichFrame: HFrameHandle | null): number;
declare function GetFrameHeight(whichFrame: HFrameHandle | null): number;
declare function GetFrameName(whichFrame: HFrameHandle | null): string;
declare function GetFrameParent(whichFrame: HFrameHandle | null): HFrameHandle;
declare function GetFrameText(whichFrame: HFrameHandle | null): string;
declare function GetFrameTextSizeLimit(whichFrame: HFrameHandle | null): number;
declare function GetFrameValue(whichFrame: HFrameHandle | null): number;
declare function GetFrameWidth(whichFrame: HFrameHandle | null): number;
declare function GetHeroBasePrimaryStat(whichUnit: HUnit | null): number;
declare function GetHeroBaseProperName(whichUnit: HUnit | null, nameIndex: number): string;
declare function GetHeroExperienceNeeded(whichUnit: HUnit | null, forLevel: number): number;
declare function GetHeroMaxLevelExperienceNeeded(whichUnit: HUnit | null): number;
declare function GetItemAbility(whichItem: HItem | null, abilityId: number): HAbility;
declare function GetItemAbilityByIndex(whichItem: HItem | null, abilityIndex: number): HAbility;
declare function GetItemBaseCharges(whichItem: HItem | null): number;
declare function GetItemBaseChargesById(itemId: number): number;
declare function GetItemBaseClassification(whichItem: HItem | null): number;
declare function GetItemBaseClassificationById(itemId: number): number;
declare function GetItemBaseCooldownId(whichItem: HItem | null): number;
declare function GetItemBaseCooldownIdById(itemId: number): number;
declare function GetItemBaseGoldCost(whichItem: HItem | null): number;
declare function GetItemBaseGoldCostById(itemId: number): number;
declare function GetItemBaseHotkey(whichItem: HItem | null): HOsKeyType;
declare function GetItemBaseHotkeyById(itemId: number): HOsKeyType;
declare function GetItemBaseIconPath(whichItem: HItem | null): string;
declare function GetItemBaseIconPathById(itemId: number): string;
declare function GetItemBaseIsDroppable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsDroppableById(itemId: number): boolean;
declare function GetItemBaseIsDroppableOnDeath(whichItem: HItem | null): boolean;
declare function GetItemBaseIsDroppableOnDeathById(itemId: number): boolean;
declare function GetItemBaseIsIgnoreCooldown(whichItem: HItem | null): boolean;
declare function GetItemBaseIsIgnoreCooldownById(itemId: number): boolean;
declare function GetItemBaseIsMorph(whichItem: HItem | null): boolean;
declare function GetItemBaseIsMorphById(itemId: number): boolean;
declare function GetItemBaseIsPawnable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPawnableById(itemId: number): boolean;
declare function GetItemBaseIsPerishable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPerishableById(itemId: number): boolean;
declare function GetItemBaseIsPickRandom(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPickRandomById(itemId: number): boolean;
declare function GetItemBaseIsPowerUp(whichItem: HItem | null): boolean;
declare function GetItemBaseIsPowerUpById(itemId: number): boolean;
declare function GetItemBaseIsSellable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsSellableById(itemId: number): boolean;
declare function GetItemBaseIsUsable(whichItem: HItem | null): boolean;
declare function GetItemBaseIsUsableById(itemId: number): boolean;
declare function GetItemBaseLevel(whichItem: HItem | null): number;
declare function GetItemBaseLevelById(itemId: number): number;
declare function GetItemBaseLumberCost(whichItem: HItem | null): number;
declare function GetItemBaseLumberCostById(itemId: number): number;
declare function GetItemBaseName(whichItem: HItem | null): string;
declare function GetItemBaseNameById(itemId: number): string;
declare function GetItemBaseOldLevel(whichItem: HItem | null): number;
declare function GetItemBaseOldLevelById(itemId: number): number;
declare function GetItemBasePriority(whichItem: HItem | null): number;
declare function GetItemBasePriorityById(itemId: number): number;
declare function GetItemBaseStockMaximum(whichItem: HItem | null): number;
declare function GetItemBaseStockMaximumById(itemId: number): number;
declare function GetItemBaseStockReplenishInterval(whichItem: HItem | null): number;
declare function GetItemBaseStockReplenishIntervalById(itemId: number): number;
declare function GetItemBaseStockStartDelay(whichItem: HItem | null): number;
declare function GetItemBaseStockStartDelayById(itemId: number): number;
declare function GetItemBaseTip(whichItem: HItem | null): string;
declare function GetItemBaseTipById(itemId: number): string;
declare function GetItemBaseUberTip(whichItem: HItem | null): string;
declare function GetItemBaseUberTipById(itemId: number): string;
declare function GetItemCooldown(whichItem: HItem | null): number;
declare function GetItemFacing(whichItem: HItem | null): number;
declare function GetItemLife(whichItem: HItem | null): number;
declare function GetItemMaxLife(whichItem: HItem | null): number;
declare function GetItemPitch(whichItem: HItem | null): number;
declare function GetItemRemainingCooldown(whichItem: HItem | null): number;
declare function GetItemRoll(whichItem: HItem | null): number;
declare function GetItemScale(whichItem: HItem | null): number;
declare function GetItemTimeScale(whichItem: HItem | null): number;
declare function GetItemVertexColour(whichItem: HItem | null): number;
declare function GetItemYaw(whichItem: HItem | null): number;
declare function GetOriginFrame(whichType: HOriginFrameType | null, index: number): HFrameHandle;
declare function GetSpecialEffectColour(whichEffect: HEffect | null): number;
declare function GetSpecialEffectFacing(whichEffect: HEffect | null): number;
declare function GetSpecialEffectHeight(whichEffect: HEffect | null): number;
declare function GetSpecialEffectPitch(whichEffect: HEffect | null): number;
declare function GetSpecialEffectPositionLocation(whichEffect: HEffect | null): HLocation;
declare function GetSpecialEffectRoll(whichEffect: HEffect | null): number;
declare function GetSpecialEffectScale(whichEffect: HEffect | null): number;
declare function GetSpecialEffectTimeScale(whichEffect: HEffect | null): number;
declare function GetSpecialEffectX(whichEffect: HEffect | null): number;
declare function GetSpecialEffectY(whichEffect: HEffect | null): number;
declare function GetSpecialEffectYaw(whichEffect: HEffect | null): number;
declare function GetSpecialEffectZ(whichEffect: HEffect | null): number;
declare function GetTrackableColour(whichTrackable: HTrackable | null): number;
declare function GetTrackableFacing(whichTrackable: HTrackable | null): number;
declare function GetTrackableHeight(whichTrackable: HTrackable | null): number;
declare function GetTrackablePitch(whichTrackable: HTrackable | null): number;
declare function GetTrackablePositionLocation(whichTrackable: HTrackable | null): HLocation;
declare function GetTrackableRoll(whichTrackable: HTrackable | null): number;
declare function GetTrackableScale(whichTrackable: HTrackable | null): number;
declare function GetTrackableTimeScale(whichTrackable: HTrackable | null): number;
declare function GetTrackableX(whichTrackable: HTrackable | null): number;
declare function GetTrackableY(whichTrackable: HTrackable | null): number;
declare function GetTrackableYaw(whichTrackable: HTrackable | null): number;
declare function GetTrackableZ(whichTrackable: HTrackable | null): number;
declare function GetTriggerFrame(): HFrameHandle;
declare function GetTriggerFrameEvent(): HFrameEventType;
declare function GetUnitAbility(whichUnit: HUnit | null, aid: number): HAbility;
declare function GetUnitAbilityByIndex(whichUnit: HUnit | null, index: number): HAbility;
declare function GetUnitArmour(whichUnit: HUnit | null): number;
declare function GetUnitArmourType(whichUnit: HUnit | null): number;
declare function GetUnitAttackCooldownByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitAttackRangeByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitAttackSpeed(whichUnit: HUnit | null): number;
declare function GetUnitAttackTypeByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitAttacksEnabledIndex(whichUnit: HUnit | null): number;
declare function GetUnitBackswingPointByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitBaseAwakenTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseAwakenTipById(unitTypeId: number): string;
declare function GetUnitBaseColour(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourA(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourAById(unitTypeId: number): number;
declare function GetUnitBaseColourB(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourBById(unitTypeId: number): number;
declare function GetUnitBaseColourById(unitTypeId: number): number;
declare function GetUnitBaseColourG(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourGById(unitTypeId: number): number;
declare function GetUnitBaseColourR(whichUnit: HUnit | null): number;
declare function GetUnitBaseColourRById(unitTypeId: number): number;
declare function GetUnitBaseDamageByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitBaseDaySight(whichUnit: HUnit | null): number;
declare function GetUnitBaseDaySightById(unitTypeId: number): number;
declare function GetUnitBaseGoldCost(whichUnit: HUnit | null): number;
declare function GetUnitBaseGoldCostById(unitTypeId: number): number;
declare function GetUnitBaseHotkey(whichUnit: HUnit | null): HOsKeyType;
declare function GetUnitBaseHotkeyById(unitTypeId: number): HOsKeyType;
declare function GetUnitBaseMissileArcById(unitTypeId: number, attackIndex: number): number;
declare function GetUnitBaseMissileArt(whichUnit: HUnit | null, attackIndex: number): string;
declare function GetUnitBaseMissileArtById(unitTypeId: number, attackIndex: number): string;
declare function GetUnitBaseMissileSpeed(whichUnit: HUnit | null, attackIndex: number): number;
declare function GetUnitBaseMissileSpeedById(unitTypeId: number, attackIndex: number): number;
declare function GetUnitBaseModel(whichUnit: HUnit | null): string;
declare function GetUnitBaseModelById(unitTypeId: number): string;
declare function GetUnitBaseName(whichUnit: HUnit | null): string;
declare function GetUnitBaseNameById(unitTypeId: number): string;
declare function GetUnitBaseNightSight(whichUnit: HUnit | null): number;
declare function GetUnitBaseNightSightById(unitTypeId: number): number;
declare function GetUnitBasePortrait(whichUnit: HUnit | null): string;
declare function GetUnitBasePortraitById(unitTypeId: number): string;
declare function GetUnitBasePrimaryStatById(unitTypeId: number): number;
declare function GetUnitBaseProperNameById(unitTypeId: number, properNameIndex: number): string;
declare function GetUnitBaseReviveTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseReviveTipById(unitTypeId: number): string;
declare function GetUnitBaseSelectionScale(whichUnit: HUnit | null): number;
declare function GetUnitBaseSelectionScaleById(unitTypeId: number): number;
declare function GetUnitBaseShadowTex(whichUnit: HUnit | null): string;
declare function GetUnitBaseShadowTexById(unitTypeId: number): string;
declare function GetUnitBaseTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseTipById(unitTypeId: number): string;
declare function GetUnitBaseUberTip(whichUnit: HUnit | null): string;
declare function GetUnitBaseUberTipById(unitTypeId: number): string;
declare function GetUnitBonusDamageByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitBonusMoveSpeedPercent(whichUnit: HUnit | null): number;
declare function GetUnitBuff(whichUnit: HUnit | null, buffId: number): HBuff;
declare function GetUnitBuffLevel(whichUnit: HUnit | null, buffId: number): number;
declare function GetUnitCurrentLife(whichUnit: HUnit | null): number;
declare function GetUnitCurrentMana(whichUnit: HUnit | null): number;
declare function GetUnitCurrentResources(whichUnit: HUnit | null): number;
declare function GetUnitCurrentSight(whichUnit: HUnit | null): number;
declare function GetUnitDamageDicesByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitDamageDicesSideByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitDamagePointByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitEluneMagicResist(whichUnit: HUnit | null): number;
declare function GetUnitItemSlots(whichUnit: HUnit | null): number;
declare function GetUnitLifeRegen(whichUnit: HUnit | null): number;
declare function GetUnitLocustFlag(whichUnit: HUnit | null): number;
declare function GetUnitMagicResistByType(whichUnit: HUnit | null, resistType: number): number;
declare function GetUnitManaRegen(whichUnit: HUnit | null): number;
declare function GetUnitMaxLife(whichUnit: HUnit | null): number;
declare function GetUnitMaxMana(whichUnit: HUnit | null): number;
declare function GetUnitMinimapX(whichUnit: HUnit | null): number;
declare function GetUnitMinimapY(whichUnit: HUnit | null): number;
declare function GetUnitMoveAIType(whichUnit: HUnit | null): number;
declare function GetUnitMoveType(whichUnit: HUnit | null): number;
declare function GetUnitNextAttackTimeStampByIndex(whichUnit: HUnit | null, attackIndex: number): number;
declare function GetUnitPrimaryStat(whichUnit: HUnit | null): number;
declare function GetUnitRunicMagicResist(whichUnit: HUnit | null): number;
declare function GetUnitSelected(whichPlayer: HPlayer | null): HUnit;
declare function GetUnitSelectedCountByPlayer(whichPlayer: HPlayer | null): number;
declare function GetUnitStunCounter(whichUnit: HUnit | null): number;
declare function GetUnitTimeScale(whichUnit: HUnit | null): number;
declare function GetUnitTotalMagicResist(whichUnit: HUnit | null): number;
declare function GetUnitTotalMoveSpeed(whichUnit: HUnit | null): number;
declare function GetUnitUnderCursor(): HUnit;
declare function GetUnitUnitBaseMoveSpeed(whichUnit: HUnit | null): number;
declare function GetUnitVertexColour(whichUnit: HUnit | null): number;
declare function GetUnitWeaponSoundByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GetUnitWeaponTypeByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function GroupAddGroupEx(destGroup: HGroup | null, sourceGroup: HGroup | null): boolean;
declare function GroupContainsUnit(whichGroup: HGroup | null, whichUnit: HUnit | null): boolean;
declare function GroupForEachUnit(whichGroup: HGroup | null): HUnit;
declare function GroupGetCount(whichGroup: HGroup | null): number;
declare function GroupGetUnitByIndex(whichGroup: HGroup | null, index: number): HUnit;
declare function GroupRemoveGroupEx(destGroup: HGroup | null, sourceGroup: HGroup | null): boolean;
declare function HandleToAIDifficulty(h: HHandle | null): HAIDifficulty;
declare function HandleToAbility(h: HHandle | null): HAbility;
declare function HandleToAddress(h: HHandle | null): number;
declare function HandleToAgent(h: HHandle | null): HAgent;
declare function HandleToAlliancetype(h: HHandle | null): HAllianceType;
declare function HandleToAnimType(h: HHandle | null): HAnimType;
declare function HandleToAttacktype(h: HHandle | null): HAttackType;
declare function HandleToBlendmode(h: HHandle | null): HBlendMode;
declare function HandleToBoolexpr(h: HHandle | null): HBoolExpr;
declare function HandleToBuff(h: HHandle | null): HBuff;
declare function HandleToButton(h: HHandle | null): HButton;
declare function HandleToCamerafield(h: HHandle | null): HCameraField;
declare function HandleToCamerasetup(h: HHandle | null): HCameraSetup;
declare function HandleToConditionfunc(h: HHandle | null): HConditionFunc;
declare function HandleToDamagetype(h: HHandle | null): HDamageType;
declare function HandleToDefeatcondition(h: HHandle | null): HDefeatCondition;
declare function HandleToDestructable(h: HHandle | null): HDestructable;
declare function HandleToDialog(h: HHandle | null): HDialog;
declare function HandleToDialogevent(h: HHandle | null): HDialogEvent;
declare function HandleToEffect(h: HHandle | null): HEffect;
declare function HandleToEffecttype(h: HHandle | null): HEffectType;
declare function HandleToEvent(h: HHandle | null): HEvent;
declare function HandleToEventid(h: HHandle | null): HEventId;
declare function HandleToFGamestate(h: HHandle | null): HFGameState;
declare function HandleToFilterfunc(h: HHandle | null): HFilterFunc;
declare function HandleToFogmodifier(h: HHandle | null): HFogModifier;
declare function HandleToFogstate(h: HHandle | null): HFogState;
declare function HandleToForce(h: HHandle | null): HForce;
declare function HandleToGamecache(h: HHandle | null): HGameCache;
declare function HandleToGamedifficulty(h: HHandle | null): HGameDifficulty;
declare function HandleToGameevent(h: HHandle | null): HGameEvent;
declare function HandleToGamespeed(h: HHandle | null): HGameSpeed;
declare function HandleToGamestate(h: HHandle | null): HGameState;
declare function HandleToGametype(h: HHandle | null): HGameType;
declare function HandleToGroup(h: HHandle | null): HGroup;
declare function HandleToHashtable(h: HHandle | null): HHashTable;
declare function HandleToIGamestate(h: HHandle | null): HIGameState;
declare function HandleToImage(h: HHandle | null): HImage;
declare function HandleToItem(h: HHandle | null): HItem;
declare function HandleToItempool(h: HHandle | null): HItemPool;
declare function HandleToItemtype(h: HHandle | null): HItemType;
declare function HandleToLeaderboard(h: HHandle | null): HLeaderBoard;
declare function HandleToLightning(h: HHandle | null): HLightning;
declare function HandleToLimitop(h: HHandle | null): HLimitop;
declare function HandleToLocation(h: HHandle | null): HLocation;
declare function HandleToMapcontrol(h: HHandle | null): HMapControl;
declare function HandleToMapdensity(h: HHandle | null): HMapDensity;
declare function HandleToMapflag(h: HHandle | null): HMapFlag;
declare function HandleToMapsetting(h: HHandle | null): HMapSetting;
declare function HandleToMapvisibility(h: HHandle | null): HMapVisibility;
declare function HandleToMultiboard(h: HHandle | null): HMultiBoard;
declare function HandleToMultiboarditem(h: HHandle | null): HMultiBoardItem;
declare function HandleToPathingtype(h: HHandle | null): HPathingType;
declare function HandleToPlacement(h: HHandle | null): HPlacement;
declare function HandleToPlayercolor(h: HHandle | null): HPlayerColor;
declare function HandleToPlayerevent(h: HHandle | null): HPlayerEvent;
declare function HandleToPlayergameresult(h: HHandle | null): HPlayerGameResult;
declare function HandleToPlayerscore(h: HHandle | null): HPlayerScore;
declare function HandleToPlayerslotstate(h: HHandle | null): HPlayerSlotState;
declare function HandleToPlayerstate(h: HHandle | null): HPlayerState;
declare function HandleToPlayerunitevent(h: HHandle | null): HPlayerunitEvent;
declare function HandleToQuest(h: HHandle | null): HQuest;
declare function HandleToQuestitem(h: HHandle | null): HQuestItem;
declare function HandleToRace(h: HHandle | null): HRace;
declare function HandleToRacepreference(h: HHandle | null): HRacePreference;
declare function HandleToRaritycontrol(h: HHandle | null): HRarityControl;
declare function HandleToRect(h: HHandle | null): HRect;
declare function HandleToRegion(h: HHandle | null): HRegion;
declare function HandleToSound(h: HHandle | null): HSound;
declare function HandleToSoundtype(h: HHandle | null): HSoundType;
declare function HandleToStartlocprio(h: HHandle | null): HStartLocPrio;
declare function HandleToSubAnimType(h: HHandle | null): HSubAnimType;
declare function HandleToTerraindeformation(h: HHandle | null): HTerrainDeformation;
declare function HandleToTexmapflags(h: HHandle | null): HTexMapFlags;
declare function HandleToTexttag(h: HHandle | null): HTextTag;
declare function HandleToTimer(h: HHandle | null): HTimer;
declare function HandleToTimerdialog(h: HHandle | null): HTimerDialog;
declare function HandleToTrackable(h: HHandle | null): HTrackable;
declare function HandleToTrigger(h: HHandle | null): HTrigger;
declare function HandleToTriggeraction(h: HHandle | null): HTriggerAction;
declare function HandleToTriggercondition(h: HHandle | null): HTriggerCondition;
declare function HandleToUbersplat(h: HHandle | null): HUberSplat;
declare function HandleToUnit(h: HHandle | null): HUnit;
declare function HandleToUnitevent(h: HHandle | null): HUnitEvent;
declare function HandleToUnitpool(h: HHandle | null): HUnitPool;
declare function HandleToUnitstate(h: HHandle | null): HUnitState;
declare function HandleToUnittype(h: HHandle | null): HUnitType;
declare function HandleToVersion(h: HHandle | null): HVersion;
declare function HandleToVolumegroup(h: HHandle | null): HVolumeGroup;
declare function HandleToWeapontype(h: HHandle | null): HWeaponType;
declare function HandleToWeathereffect(h: HHandle | null): HWeatherEffect;
declare function HandleToWidget(h: HHandle | null): HWidget;
declare function HandleToWidgetevent(h: HHandle | null): HwidgEtevent;
declare function IntToHex(i: number): string;
declare function IntegerToHandle(i: number): HHandle;
declare function IsAbilityEnabled(abil: HAbility | null): boolean;
declare function IsAbilityEnabledEx(abil: HAbility | null): boolean;
declare function IsAbilityOnCooldown(abil: HAbility | null): boolean;
declare function IsAbilityShown(abil: HAbility | null): boolean;
declare function IsAbilityUsable(abil: HAbility | null): boolean;
declare function IsFrameEnabled(whichFrame: HFrameHandle | null): boolean;
declare function IsFrameVisible(whichFrame: HFrameHandle | null): boolean;
declare function IsSpecialEffectVisible(whichEffect: HEffect | null): boolean;
declare function IsTrackableVisible(whichTrackable: HTrackable | null): boolean;
declare function IsUnitAttackEnabled(whichUnit: HUnit | null): boolean;
declare function IsUnitAttackEnabledEx(whichUnit: HUnit | null): boolean;
declare function IsUnitDead(whichUnit: HUnit | null): boolean;
declare function IsUnitGatherer(whichUnit: HUnit | null): boolean;
declare function IsUnitHero(whichUnit: HUnit | null): boolean;
declare function IsUnitInventoryEnabled(whichUnit: HUnit | null): boolean;
declare function IsUnitInventoryEnabledEx(whichUnit: HUnit | null): boolean;
declare function IsUnitInvulnerable(whichUnit: HUnit | null): boolean;
declare function IsUnitMovementEnabled(whichUnit: HUnit | null): boolean;
declare function IsUnitMovementEnabledEx(whichUnit: HUnit | null): boolean;
declare function IsUnitMoving(whichUnit: HUnit | null): boolean;
declare function IsUnitSelectable(whichUnit: HUnit | null): boolean;
declare function IsUnitShop(whichUnit: HUnit | null): boolean;
declare function IsUnitStateNormal(whichUnit: HUnit | null, additionalCheck: boolean): boolean;
declare function IsUnitStunned(whichUnit: HUnit | null): boolean;
declare function IsUnitTower(whichUnit: HUnit | null): boolean;
declare function LoadTOCFile(TOCFile: string): boolean;
declare function MorphUnitToTypeId(whichUnit: HUnit | null, uid: number): void;
declare function MorphUnitToTypeIdEx(whichUnit: HUnit | null, uid: number, unitFlags: number, updateHealthState: boolean, updateManaState: boolean, healthStateId: number, manaStateId: number, updateScale: boolean, replaceAbilities: boolean, whichAbility: HAbility | null, resetBuildingAnimation: boolean): void;
declare function QueueItemAnimation(whichItem: HItem | null, animation: string): void;
declare function QueueItemAnimationByIndex(whichItem: HItem | null, animIndex: number): void;
declare function QueueSpecialEffectAnimation(whichEffect: HEffect | null, animation: string): void;
declare function QueueSpecialEffectAnimationByIndex(whichEffect: HEffect | null, animIndex: number): void;
declare function QueueTrackableAnimation(whichTrackable: HTrackable | null, animation: string): void;
declare function QueueTrackableAnimationByIndex(whichTrackable: HTrackable | null, animIndex: number): void;
declare function RedrawUnit(whichUnit: HUnit | null): void;
declare function RefreshBuff(whichBuff: HBuff | null): boolean;
declare function ResetSpecialEffectetMatrix(whichEffect: HEffect | null): void;
declare function ResetTrackableetMatrix(whichTrackable: HTrackable | null): void;
declare function SetAbilityBackswing(abil: HAbility | null, backswing: number): number;
declare function SetAbilityBaseCooldownById(aid: number, level: number, cooldown: number): number;
declare function SetAbilityBaseManaCostById(aid: number, level: number, manaCost: number): number;
declare function SetAbilityBaseSpellDetails(abil: HAbility | null, level: number): number;
declare function SetAbilityBaseSpellDetailsById(aid: number, level: number): number;
declare function SetAbilityBaseTip(abil: HAbility | null, level: number, text: string): number;
declare function SetAbilityBaseTipById(aid: number, level: number, text: string): number;
declare function SetAbilityBaseUberTip(abil: HAbility | null, level: number, text: string): number;
declare function SetAbilityBaseUberTipById(aid: number, level: number, text: string): number;
declare function SetAbilityBaseUnTip(abil: HAbility | null, level: number, text: string): number;
declare function SetAbilityBaseUnTipById(aid: number, level: number, text: string): number;
declare function SetAbilityBaseUnUberTip(abil: HAbility | null, level: number, text: string): number;
declare function SetAbilityBaseUnUberTipById(aid: number, level: number, text: string): number;
declare function SetAbilityButtonX(abil: HAbility | null, positionX: number): number;
declare function SetAbilityButtonXById(aid: number, positionX: number): number;
declare function SetAbilityButtonY(abil: HAbility | null, positionY: number): number;
declare function SetAbilityButtonYById(aid: number, positionY: number): number;
declare function SetAbilityCastPoint(abil: HAbility | null, castPoint: number): number;
declare function SetAbilityCastTime(abil: HAbility | null, castTime: number): number;
declare function SetAbilityCooldown(abil: HAbility | null, cooldown: number): number;
declare function SetAbilityEffectSound(abil: HAbility | null, text: string): number;
declare function SetAbilityEffectSoundById(aid: number, text: string): number;
declare function SetAbilityEnabled(abil: HAbility | null, flag: boolean): number;
declare function SetAbilityEnabledEx(abil: HAbility | null, flag: boolean): number;
declare function SetAbilityGlobalMessage(abil: HAbility | null, text: string): number;
declare function SetAbilityGlobalMessageById(aid: number, text: string): number;
declare function SetAbilityGlobalSound(abil: HAbility | null, text: string): number;
declare function SetAbilityGlobalSoundById(aid: number, text: string): number;
declare function SetAbilityHotkey(abil: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityHotkeyById(aid: number, whichKey: HOsKeyType | null): void;
declare function SetAbilityHotkeyByIdEx(aid: number, whichKey: HOsKeyType | null): void;
declare function SetAbilityHotkeyEx(abil: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityIsMissileHoming(abil: HAbility | null, ishoming: boolean): number;
declare function SetAbilityIsMissileHomingById(aid: number, ishoming: boolean): number;
declare function SetAbilityMissileArc(abil: HAbility | null, missileArc: number): number;
declare function SetAbilityMissileArcById(aid: number, missileArc: number): number;
declare function SetAbilityMissileSpeed(abil: HAbility | null, missileSpeed: number): number;
declare function SetAbilityMissileSpeedById(aid: number, missileSpeed: number): number;
declare function SetAbilityResearchButtonX(abil: HAbility | null, positionX: number): number;
declare function SetAbilityResearchButtonXById(aid: number, positionX: number): number;
declare function SetAbilityResearchButtonY(abil: HAbility | null, positionY: number): number;
declare function SetAbilityResearchButtonYById(aid: number, positionY: number): number;
declare function SetAbilityResearchHotkey(abil: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityResearchHotkeyById(aid: number, whichKey: HOsKeyType | null): void;
declare function SetAbilityUnButtonX(abil: HAbility | null, positionX: number): number;
declare function SetAbilityUnButtonXById(aid: number, positionX: number): number;
declare function SetAbilityUnButtonY(abil: HAbility | null, positionY: number): number;
declare function SetAbilityUnButtonYById(aid: number, positionY: number): number;
declare function SetAbilityUnHotkey(abil: HAbility | null, whichKey: HOsKeyType | null): void;
declare function SetAbilityUnHotkeyById(aid: number, whichKey: HOsKeyType | null): void;
declare function SetBuffRemainingDuration(whichBuff: HBuff | null, duration: number): boolean;
declare function SetEventAttackType(attackType: HAttackType | null): boolean;
declare function SetEventDamage(damage: number): void;
declare function SetEventDamageFlags(flags: number): boolean;
declare function SetEventDamageType(damageType: HDamageType | null): boolean;
declare function SetEventDamageTypeFlags(damageFlags: number): boolean;
declare function SetEventWeaponType(weaponType: HWeaponType | null): boolean;
declare function SetFrameAbsolutePoint(whichFrame: HFrameHandle | null, point: HFramePointType | null, x: number, y: number): void;
declare function SetFrameAllPoints(whichFrame: HFrameHandle | null, relativeFrame: HFrameHandle | null): void;
declare function SetFrameAlpha(whichFrame: HFrameHandle | null, alpha: number): void;
declare function SetFrameEnabled(whichFrame: HFrameHandle | null, enabled: boolean): void;
declare function SetFrameFocus(whichFrame: HFrameHandle | null, isFocus: boolean): void;
declare function SetFrameFont(whichFrame: HFrameHandle | null, fontName: string, size: number, flags: number): void;
declare function SetFrameMinMaxValues(whichFrame: HFrameHandle | null, minVal: number, maxVal: number): void;
declare function SetFrameModel(whichFrame: HFrameHandle | null, model: string, cameraIndex: number): void;
declare function SetFrameMouseCaged(whichFrame: HFrameHandle | null, enable: boolean): void;
declare function SetFrameParent(whichFrame: HFrameHandle | null, whichParent: HFrameHandle | null): void;
declare function SetFramePriority(whichFrame: HFrameHandle | null, priority: number): void;
declare function SetFrameRelativePoint(whichFrame: HFrameHandle | null, point: HFramePointType | null, relativeFrame: HFrameHandle | null, relativePoint: HFramePointType | null, x: number, y: number): void;
declare function SetFrameScale(whichFrame: HFrameHandle | null, scale: number): void;
declare function SetFrameSize(whichFrame: HFrameHandle | null, width: number, height: number): void;
declare function SetFrameStepSize(whichFrame: HFrameHandle | null, stepSize: number): void;
declare function SetFrameText(whichFrame: HFrameHandle | null, text: string): void;
declare function SetFrameTextAlignment(whichFrame: HFrameHandle | null, verticalAlign: HTextAlignType | null, horizontalAlign: HTextAlignType | null): void;
declare function SetFrameTextColour(whichFrame: HFrameHandle | null, colour: number): void;
declare function SetFrameTextSizeLimit(whichFrame: HFrameHandle | null, textSize: number): void;
declare function SetFrameTexture(whichFrame: HFrameHandle | null, textureFile: string, flag: number, blend: boolean): void;
declare function SetFrameTooltip(whichFrame: HFrameHandle | null, tooltipFrame: HFrameHandle | null): void;
declare function SetFrameValue(whichFrame: HFrameHandle | null, value: number): void;
declare function SetFrameVertexColour(whichFrame: HFrameHandle | null, colour: number): void;
declare function SetFrameVertexColourEx(whichFrame: HFrameHandle | null, alpha: number, red: number, blue: number, green: number): void;
declare function SetHeroBasePrimaryStat(whichUnit: HUnit | null, statIndex: number): void;
declare function SetHeroBaseProperName(whichUnit: HUnit | null, nameIndex: number, properName: string): void;
declare function SetItemAnimation(whichItem: HItem | null, animation: string): void;
declare function SetItemAnimationByIndex(whichItem: HItem | null, animIndex: number): void;
declare function SetItemAnimationWithRarity(whichItem: HItem | null, animation: string, rarity: number): void;
declare function SetItemAnimationWithRarityByIndex(whichItem: HItem | null, animIndex: number, rarity: number): void;
declare function SetItemBaseCharges(whichItem: HItem | null, charges: number): void;
declare function SetItemBaseChargesById(itemId: number, charges: number): void;
declare function SetItemBaseClassification(whichItem: HItem | null, classifictaionId: number): void;
declare function SetItemBaseClassificationById(itemId: number, classifictaionId: number): void;
declare function SetItemBaseCooldownId(whichItem: HItem | null, cooldownId: number): void;
declare function SetItemBaseCooldownIdById(itemId: number, cooldownId: number): void;
declare function SetItemBaseGoldCost(whichItem: HItem | null, goldcost: number): void;
declare function SetItemBaseGoldCostById(itemId: number, goldcost: number): void;
declare function SetItemBaseHotkey(whichItem: HItem | null, whichKey: HOsKeyType | null): void;
declare function SetItemBaseHotkeyById(itemId: number, whichKey: HOsKeyType | null): void;
declare function SetItemBaseIconPath(whichItem: HItem | null, path: string): void;
declare function SetItemBaseIconPathById(itemId: number, path: string): void;
declare function SetItemBaseIsDroppable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsDroppableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsDroppableOnDeath(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsDroppableOnDeathById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsIgnoreCooldown(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsIgnoreCooldownById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsMorph(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsMorphById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPawnable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPawnableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPerishable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPerishableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPickRandom(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPickRandomById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsPowerUp(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsPowerUpById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsSellable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsSellableById(itemId: number, flag: boolean): void;
declare function SetItemBaseIsUsable(whichItem: HItem | null, flag: boolean): void;
declare function SetItemBaseIsUsableById(itemId: number, flag: boolean): void;
declare function SetItemBaseLevel(whichItem: HItem | null, level: number): void;
declare function SetItemBaseLevelById(itemId: number, level: number): void;
declare function SetItemBaseLumberCost(whichItem: HItem | null, lumbercost: number): void;
declare function SetItemBaseLumberCostById(itemId: number, lumbercost: number): void;
declare function SetItemBaseName(whichItem: HItem | null, name: string): void;
declare function SetItemBaseNameById(itemId: number, name: string): void;
declare function SetItemBaseOldLevel(whichItem: HItem | null, oldlevel: number): void;
declare function SetItemBaseOldLevelById(itemId: number, oldlevel: number): void;
declare function SetItemBasePriority(whichItem: HItem | null, priority: number): void;
declare function SetItemBasePriorityById(itemId: number, priority: number): void;
declare function SetItemBaseStockMaximum(whichItem: HItem | null, stockMax: number): void;
declare function SetItemBaseStockMaximumById(itemId: number, stockMax: number): void;
declare function SetItemBaseStockReplenishInterval(whichItem: HItem | null, replenishInterval: number): void;
declare function SetItemBaseStockReplenishIntervalById(itemId: number, replenishInterval: number): void;
declare function SetItemBaseStockStartDelay(whichItem: HItem | null, stockStartDelay: number): void;
declare function SetItemBaseStockStartDelayById(itemId: number, stockStartDelay: number): void;
declare function SetItemBaseTip(whichItem: HItem | null, tip: string): void;
declare function SetItemBaseTipById(itemId: number, tip: string): void;
declare function SetItemBaseUberTip(whichItem: HItem | null, tip: string): void;
declare function SetItemBaseUberTipById(itemId: number, tip: string): void;
declare function SetItemCooldown(whichItem: HItem | null, cooldown: number): void;
declare function SetItemFacing(whichItem: HItem | null, facing: number, isInstant: boolean): void;
declare function SetItemLife(whichItem: HItem | null, life: number): void;
declare function SetItemMaxLife(whichItem: HItem | null, maxLife: number): void;
declare function SetItemModel(whichItem: HItem | null, modelFile: string): void;
declare function SetItemOrientation(whichItem: HItem | null, yaw: number, pitch: number, roll: number): void;
declare function SetItemPitch(whichItem: HItem | null, pitch: number): void;
declare function SetItemRemainingCooldown(whichItem: HItem | null, cooldown: number): void;
declare function SetItemRoll(whichItem: HItem | null, roll: number): void;
declare function SetItemScale(whichItem: HItem | null, scale: number): void;
declare function SetItemSpaceRotation(whichItem: HItem | null, yaw: number, pitch: number, roll: number, eulerOrder: number): void;
declare function SetItemTimeScale(whichItem: HItem | null, timeScale: number): void;
declare function SetItemVertexColour(whichItem: HItem | null, red: number, green: number, blue: number, alpha: number): void;
declare function SetItemYaw(whichItem: HItem | null, yaw: number): void;
declare function SetSpecialEffectAlpha(whichEffect: HEffect | null, alpha: number): boolean;
declare function SetSpecialEffectAnimation(whichEffect: HEffect | null, animation: string): void;
declare function SetSpecialEffectAnimationByIndex(whichEffect: HEffect | null, animIndex: number): void;
declare function SetSpecialEffectAnimationWithRarity(whichEffect: HEffect | null, animation: string, rarity: number): void;
declare function SetSpecialEffectAnimationWithRarityByIndex(whichEffect: HEffect | null, animIndex: number, rarity: number): void;
declare function SetSpecialEffectColour(whichEffect: HEffect | null, colour: number): boolean;
declare function SetSpecialEffectFacing(whichEffect: HEffect | null, facing: number): boolean;
declare function SetSpecialEffectHeight(whichEffect: HEffect | null, height: number): void;
declare function SetSpecialEffectModel(whichEffect: HEffect | null, modelName: string): void;
declare function SetSpecialEffectModelEx(whichEffect: HEffect | null, modelName: string, playerColour: number): void;
declare function SetSpecialEffectOrientation(whichEffect: HEffect | null, yaw: number, pitch: number, roll: number): void;
declare function SetSpecialEffectOrientationEx(whichEffect: HEffect | null, yaw: number, pitch: number, roll: number, eulerOrder: number): boolean;
declare function SetSpecialEffectPitch(whichEffect: HEffect | null, pitch: number): boolean;
declare function SetSpecialEffectPosition(whichEffect: HEffect | null, x: number, y: number): void;
declare function SetSpecialEffectPositionEx(whichEffect: HEffect | null, x: number, y: number, z: number): void;
declare function SetSpecialEffectPositionLocation(whichEffect: HEffect | null, loc: HLocation | null): void;
declare function SetSpecialEffectRoll(whichEffect: HEffect | null, roll: number): boolean;
declare function SetSpecialEffectScale(whichEffect: HEffect | null, scale: number): void;
declare function SetSpecialEffectTimeScale(whichEffect: HEffect | null, timescale: number): void;
declare function SetSpecialEffectVertexColour(whichEffect: HEffect | null, red: number, green: number, blue: number, alpha: number): boolean;
declare function SetSpecialEffectVisibility(whichEffect: HEffect | null, visibility: boolean): void;
declare function SetSpecialEffectX(whichEffect: HEffect | null, x: number): void;
declare function SetSpecialEffectY(whichEffect: HEffect | null, y: number): void;
declare function SetSpecialEffectYaw(whichEffect: HEffect | null, yaw: number): boolean;
declare function SetSpecialEffectZ(whichEffect: HEffect | null, z: number): void;
declare function SetTrackableAlpha(whichTrackable: HTrackable | null, alpha: number): boolean;
declare function SetTrackableAnimation(whichTrackable: HTrackable | null, animation: string): void;
declare function SetTrackableAnimationByIndex(whichTrackable: HTrackable | null, animIndex: number): void;
declare function SetTrackableAnimationWithRarity(whichTrackable: HTrackable | null, animation: string, rarity: number): void;
declare function SetTrackableAnimationWithRarityByIndex(whichTrackable: HTrackable | null, animIndex: number, rarity: number): void;
declare function SetTrackableColour(whichTrackable: HTrackable | null, colour: number): boolean;
declare function SetTrackableFacing(whichTrackable: HTrackable | null, facing: number): boolean;
declare function SetTrackableHeight(whichTrackable: HTrackable | null, height: number): void;
declare function SetTrackableModel(whichTrackable: HTrackable | null, modelName: string): void;
declare function SetTrackableModelEx(whichTrackable: HTrackable | null, modelName: string, playerColour: number): void;
declare function SetTrackableOrientation(whichTrackable: HTrackable | null, yaw: number, pitch: number, roll: number): void;
declare function SetTrackableOrientationEx(whichTrackable: HTrackable | null, yaw: number, pitch: number, roll: number, eulerOrder: number): boolean;
declare function SetTrackablePitch(whichTrackable: HTrackable | null, pitch: number): boolean;
declare function SetTrackablePosition(whichTrackable: HTrackable | null, x: number, y: number): void;
declare function SetTrackablePositionEx(whichTrackable: HTrackable | null, x: number, y: number, z: number): void;
declare function SetTrackablePositionLocation(whichTrackable: HTrackable | null, loc: HLocation | null): void;
declare function SetTrackableRoll(whichTrackable: HTrackable | null, roll: number): boolean;
declare function SetTrackableScale(whichTrackable: HTrackable | null, scale: number): void;
declare function SetTrackableTimeScale(whichTrackable: HTrackable | null, timescale: number): void;
declare function SetTrackableVertexColour(whichTrackable: HTrackable | null, red: number, green: number, blue: number, alpha: number): boolean;
declare function SetTrackableVisibility(whichTrackable: HTrackable | null, visibility: boolean): void;
declare function SetTrackableX(whichTrackable: HTrackable | null, x: number): void;
declare function SetTrackableY(whichTrackable: HTrackable | null, y: number): void;
declare function SetTrackableYaw(whichTrackable: HTrackable | null, yaw: number): boolean;
declare function SetTrackableZ(whichTrackable: HTrackable | null, z: number): void;
declare function SetUnitArmour(whichUnit: HUnit | null, armour: number): void;
declare function SetUnitArmourType(whichUnit: HUnit | null, armourType: number): void;
declare function SetUnitAttackCooldownByIndex(whichUnit: HUnit | null, atttackIndex: number, attackCooldown: number): void;
declare function SetUnitAttackRangeByIndex(whichUnit: HUnit | null, atttackIndex: number, range: number): void;
declare function SetUnitAttackSpeed(whichUnit: HUnit | null, attackSpeed: number): void;
declare function SetUnitAttackState(whichUnit: HUnit | null, atttackIndex: number, attackState: number): number;
declare function SetUnitAttackTypeByIndex(whichUnit: HUnit | null, atttackIndex: number, attackType: number): void;
declare function SetUnitBackswingPointByIndex(whichUnit: HUnit | null, atttackIndex: number, backswing: number): void;
declare function SetUnitBaseAwakenTip(whichUnit: HUnit | null, awakenTip: string): void;
declare function SetUnitBaseAwakenTipById(unitTypeId: number, awakenTip: string): void;
declare function SetUnitBaseColour(whichUnit: HUnit | null, colour: number): void;
declare function SetUnitBaseColourA(whichUnit: HUnit | null, alpha: number): void;
declare function SetUnitBaseColourAById(unitTypeId: number, colourA: number): void;
declare function SetUnitBaseColourB(whichUnit: HUnit | null, blue: number): void;
declare function SetUnitBaseColourBById(unitTypeId: number, colourB: number): void;
declare function SetUnitBaseColourById(unitTypeId: number, colour: number): void;
declare function SetUnitBaseColourG(whichUnit: HUnit | null, green: number): void;
declare function SetUnitBaseColourGById(unitTypeId: number, colourG: number): void;
declare function SetUnitBaseColourR(whichUnit: HUnit | null, red: number): void;
declare function SetUnitBaseColourRById(unitTypeId: number, colourR: number): void;
declare function SetUnitBaseDamageByIndex(whichUnit: HUnit | null, atttackIndex: number, damage: number): void;
declare function SetUnitBaseDaySight(whichUnit: HUnit | null, dsight: number): void;
declare function SetUnitBaseDaySightById(unitTypeId: number, daySight: number): void;
declare function SetUnitBaseGoldCost(whichUnit: HUnit | null, goldCost: number): void;
declare function SetUnitBaseGoldCostById(unitTypeId: number, goldCost: number): void;
declare function SetUnitBaseHotkey(whichUnit: HUnit | null, whichKey: HOsKeyType | null): void;
declare function SetUnitBaseHotkeyById(unitTypeId: number, whichKey: HOsKeyType | null): void;
declare function SetUnitBaseMissileArcById(unitTypeId: number, attackIndex: number, realValue: number): void;
declare function SetUnitBaseMissileArt(whichUnit: HUnit | null, attackIndex: number, missleArt: string): void;
declare function SetUnitBaseMissileArtById(unitTypeId: number, attackIndex: number, missleArt: string): void;
declare function SetUnitBaseMissileSpeed(whichUnit: HUnit | null, attackIndex: number, missleSpeed: number): void;
declare function SetUnitBaseMissileSpeedById(unitTypeId: number, attackIndex: number, realValue: number): void;
declare function SetUnitBaseModel(whichUnit: HUnit | null, model: string): void;
declare function SetUnitBaseModelById(unitTypeId: number, modelName: string): void;
declare function SetUnitBaseName(whichUnit: HUnit | null, name: string): void;
declare function SetUnitBaseNameById(unitTypeId: number, name: string): void;
declare function SetUnitBaseNightSight(whichUnit: HUnit | null, nsight: number): void;
declare function SetUnitBaseNightSightById(unitTypeId: number, nightSight: number): void;
declare function SetUnitBasePortrait(whichUnit: HUnit | null, portrait: string): void;
declare function SetUnitBasePortraitById(unitTypeId: number, portraitName: string): void;
declare function SetUnitBasePrimaryStatById(unitTypeId: number, statIndex: number): void;
declare function SetUnitBaseProperNameById(unitTypeId: number, properName: string, properNameIndex: number): void;
declare function SetUnitBaseReviveTip(whichUnit: HUnit | null, revivetip: string): void;
declare function SetUnitBaseReviveTipById(unitTypeId: number, reviveTip: string): void;
declare function SetUnitBaseSelectionScale(whichUnit: HUnit | null, selectionScale: number): void;
declare function SetUnitBaseSelectionScaleById(unitTypeId: number, realValue: number): void;
declare function SetUnitBaseShadowTex(whichUnit: HUnit | null, shadowTexture: string): void;
declare function SetUnitBaseShadowTexById(unitTypeId: number, shadowTexture: string): void;
declare function SetUnitBaseTip(whichUnit: HUnit | null, tip: string): void;
declare function SetUnitBaseTipById(unitTypeId: number, tip: string): void;
declare function SetUnitBaseUberTip(whichUnit: HUnit | null, ubertip: string): void;
declare function SetUnitBaseUberTipById(unitTypeId: number, uberTip: string): void;
declare function SetUnitBonusDamageByIndex(whichUnit: HUnit | null, atttackIndex: number, bonusDamage: number): void;
declare function SetUnitBonusMoveSpeedPercent(whichUnit: HUnit | null, bonusMoveSpeedPercent: number): void;
declare function SetUnitControl(whichUnit: HUnit | null, flagValue: number, isSetFlagValue: boolean, ismove: boolean, isattack: boolean, isinventory: boolean): void;
declare function SetUnitCurrentLife(whichUnit: HUnit | null, life: number): void;
declare function SetUnitCurrentMana(whichUnit: HUnit | null, mana: number): void;
declare function SetUnitCurrentSight(whichUnit: HUnit | null, realValue: number): void;
declare function SetUnitDamageDicesByIndex(whichUnit: HUnit | null, atttackIndex: number, dices: number): void;
declare function SetUnitDamageDicesSideByIndex(whichUnit: HUnit | null, atttackIndex: number, dicesSides: number): void;
declare function SetUnitDamagePointByIndex(whichUnit: HUnit | null, atttackIndex: number, damagePoint: number): void;
declare function SetUnitFacingEx(whichUnit: HUnit | null, facing: number, isInstant: boolean): void;
declare function SetUnitFacingInstant(whichUnit: HUnit | null, facing: number): void;
declare function SetUnitItemSlots(whichUnit: HUnit | null, itemSlots: number): void;
declare function SetUnitLifeRegen(whichUnit: HUnit | null, lifeRegen: number): void;
declare function SetUnitLocustFlag(whichUnit: HUnit | null, flag: number, mode: number): void;
declare function SetUnitManaRegen(whichUnit: HUnit | null, manaRegen: number): void;
declare function SetUnitMaxLife(whichUnit: HUnit | null, maxLife: number): void;
declare function SetUnitMaxMana(whichUnit: HUnit | null, maxMana: number): void;
declare function SetUnitModel(whichUnit: HUnit | null, modelName: string): void;
declare function SetUnitMoveAIType(whichUnit: HUnit | null, moveAIType: number): void;
declare function SetUnitMoveType(whichUnit: HUnit | null, moveType: number): void;
declare function SetUnitMoveTypeByIndex(whichUnit: HUnit | null, moveIndex: number): void;
declare function SetUnitNextAttackTimeStampByIndex(whichUnit: HUnit | null, attackIndex: number, time: number): void;
declare function SetUnitPrimaryStat(whichUnit: HUnit | null, primaryStatIndex: number): void;
declare function SetUnitReplaceableTexture(whichUnit: HUnit | null, textureName: string, textureIndex: number): void;
declare function SetUnitSelectable(whichUnit: HUnit | null, selectable: boolean): void;
declare function SetUnitStunCounter(whichUnit: HUnit | null, stunCounter: number): void;
declare function SetUnitStunned(whichUnit: HUnit | null, state: boolean): void;
declare function SetUnitTruesightImmuneState(whichUnit: HUnit | null, state: boolean): void;
declare function SetUnitTypeId(whichUnit: HUnit | null, newId: number): void;
declare function SetUnitUnitBaseMoveSpeed(whichUnit: HUnit | null, baseMoveSpeed: number): void;
declare function SetUnitWeaponSoundByIndex(whichUnit: HUnit | null, atttackIndex: number, weaponSound: number): void;
declare function SetUnitWeaponTypeByIndex(whichUnit: HUnit | null, atttackIndex: number, weaponType: number): void;
declare function ShowAbility(abil: HAbility | null, flag: boolean): number;
declare function ShowFrame(whichFrame: HFrameHandle | null, isShow: boolean): void;
declare function SilenceAbility(abil: HAbility | null, flag1: boolean, flag2: boolean): number;
declare function StartAbilityCooldown(abil: HAbility | null, cooldown: number): boolean;
declare function StartItemCooldown(whichUnit: HUnit | null, whichItem: HItem | null, cooldown: number): void;
declare function TriggerRegisterFrameEvent(whichTrigger: HTrigger | null, whichFrame: HFrameHandle | null, frameEvent: HFrameEventType | null): HEvent;
declare function UnitAddAbilityEx(whichUnit: HUnit | null, abilityId: number, checkForDuplicates: boolean): boolean;
declare function UnitAddExtraAttackByIndex(whichUnit: HUnit | null, atttackIndex: number): boolean;
declare function UnitApplySilence(whichUnit: HUnit | null, state: boolean): void;
declare function UnitApplyUpdates(whichUnit: HUnit | null): number;
declare function UnitCancelCurrentAttackByIndex(whichUnit: HUnit | null, atttackIndex: number): number;
declare function UnitDisableAbilities(whichUnit: HUnit | null, state: boolean): void;
declare function UnitRemoveAbilityEx(whichUnit: HUnit | null, abilityId: number, removeDuplicates: boolean): boolean;
declare function UnitResetAttackCooldownByIndex(whichUnit: HUnit | null, atttackIndex: number): boolean;
declare function UnitUnapplyUpdates(whichUnit: HUnit | null): number;
declare function UnsilenceAbility(abil: HAbility | null, flag1: boolean, flag2: boolean): number;
declare function UpdateUnitInfoBar(whichUnit: HUnit | null): number;
