/** @noSelfInFile **/

declare function AbortCinematicFadeBJ(): void;
declare function AcosBJ(degrees: number): number;
declare function AddHeroXPSwapped(xpToAdd: number, whichHero: HUnit | null, showEyeCandy: boolean): void;
declare function AddItemToStockBJ(itemId: number, whichUnit: HUnit | null, currentStock: number, stockMax: number): void;
declare function AddLightningLoc(codeName: string, where1: HLocation | null, where2: HLocation | null): HLightning;
declare function AddResourceAmountBJ(delta: number, whichUnit: HUnit | null): void;
declare function AddSpecialEffectLocBJ(where: HLocation | null, modelName: string): HEffect;
declare function AddSpecialEffectTargetUnitBJ(attachPointName: string, targetWidget: HWidget | null, modelName: string): HEffect;
declare function AddUnitAnimationPropertiesBJ(add: boolean, animProperties: string, whichUnit: HUnit | null): void;
declare function AddUnitToStockBJ(unitId: number, whichUnit: HUnit | null, currentStock: number, stockMax: number): void;
declare function AddWeatherEffectSaveLast(where: HRect | null, effectID: number): HWeatherEffect;
declare function AdjustCameraBoundsBJ(adjustMethod: number, dxWest: number, dxEast: number, dyNorth: number, dySouth: number): void;
declare function AdjustCameraBoundsForPlayerBJ(adjustMethod: number, whichPlayer: HPlayer | null, dxWest: number, dxEast: number, dyNorth: number, dySouth: number): void;
declare function AdjustPlayerStateBJ(delta: number, whichPlayer: HPlayer | null, whichPlayerState: HPlayerState | null): void;
declare function AdjustPlayerStateSimpleBJ(whichPlayer: HPlayer | null, whichPlayerState: HPlayerState | null, delta: number): void;
declare function AllowVictoryDefeat(gameResult: HPlayerGameResult | null): boolean;
declare function AngleBetweenPoints(locA: HLocation | null, locB: HLocation | null): number;
declare function AsinBJ(degrees: number): number;
declare function Atan2BJ(y: number, x: number): number;
declare function AtanBJ(degrees: number): number;
declare function AttachSoundToUnitBJ(soundHandle: HSound | null, whichUnit: HUnit | null): void;
declare function BJDebugMsg(msg: string): void;
declare function BlightGoldMineForPlayer(goldMine: HUnit | null, whichPlayer: HPlayer | null): HUnit;
declare function BlightGoldMineForPlayerBJ(goldMine: HUnit | null, whichPlayer: HPlayer | null): HUnit;
declare function CameraClearNoiseForPlayer(whichPlayer: HPlayer | null): void;
declare function CameraResetSmoothingFactorBJ(): void;
declare function CameraSetEQNoiseForPlayer(whichPlayer: HPlayer | null, magnitude: number): void;
declare function CameraSetSmoothingFactorBJ(factor: number): void;
declare function CameraSetSourceNoiseForPlayer(whichPlayer: HPlayer | null, magnitude: number, velocity: number): void;
declare function CameraSetTargetNoiseForPlayer(whichPlayer: HPlayer | null, magnitude: number, velocity: number): void;
declare function CameraSetupApplyForPlayer(doPan: boolean, whichSetup: HCameraSetup | null, whichPlayer: HPlayer | null, duration: number): void;
declare function CameraSetupGetFieldSwap(whichField: HCameraField | null, whichSetup: HCameraSetup | null): number;
declare function CancelCineSceneBJ(): void;
declare function ChangeElevatorHeight(d: HDestructable | null, newHeight: number): void;
declare function ChangeElevatorWallBlocker(x: number, y: number, facing: number, open: boolean): void;
declare function ChangeElevatorWalls(open: boolean, walls: number, d: HDestructable | null): void;
declare function CheckInitPlayerSlotAvailability(): void;
declare function CheckItemStatus(whichItem: HItem | null, status: number): boolean;
declare function CheckItemcodeStatus(itemId: number, status: number): boolean;
declare function ChooseRandomCreepBJ(level: number): number;
declare function ChooseRandomItemBJ(level: number): number;
declare function ChooseRandomItemExBJ(level: number, whichType: HItemType | null): number;
declare function ChooseRandomNPBuildingBJ(): number;
declare function CinematicFadeBJ(fadetype: number, duration: number, tex: string, red: number, green: number, blue: number, trans: number): void;
declare function CinematicFadeCommonBJ(red: number, green: number, blue: number, duration: number, tex: string, startTrans: number, endTrans: number): void;
declare function CinematicFilterGenericBJ(duration: number, bmode: HBlendMode | null, tex: string, red0: number, green0: number, blue0: number, trans0: number, red1: number, green1: number, blue1: number, trans1: number): void;
declare function CinematicModeBJ(cineMode: boolean, forForce: HForce | null): void;
declare function CinematicModeExBJ(cineMode: boolean, forForce: HForce | null, interfaceFadeTime: number): void;
declare function ClearMapMusicBJ(): void;
declare function ClearSelectionForPlayer(whichPlayer: HPlayer | null): void;
declare function ClearTextMessagesBJ(toForce: HForce | null): void;
declare function CommentString(commentString: string): void;
declare function CompareLocationsBJ(A: HLocation | null, B: HLocation | null): boolean;
declare function CompareRectsBJ(A: HRect | null, B: HRect | null): boolean;
declare function ConditionalTriggerExecute(trig: HTrigger | null): void;
declare function ConfigureNeutralVictim(): void;
declare function ContinueCinematicFadeAfterBJ(duration: number, red: number, green: number, blue: number, trans: number, tex: string): void;
declare function ContinueCinematicFadeBJ(): void;
declare function ConvertedPlayer(convertedPlayerId: number): HPlayer;
declare function CopySaveGameBJ(sourceSaveName: string, destSaveName: string): boolean;
declare function CosBJ(degrees: number): number;
declare function CountLivingPlayerUnitsOfTypeId(unitId: number, whichPlayer: HPlayer | null): number;
declare function CountPlayersInForceBJ(f: HForce | null): number;
declare function CountPlayersInForceEnum(): void;
declare function CountUnitsInGroup(g: HGroup | null): number;
declare function CountUnitsInGroupEnum(): void;
declare function CreateCorpseLocBJ(unitid: number, whichPlayer: HPlayer | null, loc: HLocation | null): HUnit;
declare function CreateDeadDestructableLocBJ(objectid: number, loc: HLocation | null, facing: number, scale: number, variation: number): HDestructable;
declare function CreateDefeatConditionBJ(description: string): HDefeatCondition;
declare function CreateDestructableLoc(objectid: number, loc: HLocation | null, facing: number, scale: number, variation: number): HDestructable;
declare function CreateFogModifierRadiusLocBJ(enabled: boolean, whichPlayer: HPlayer | null, whichFogState: HFogState | null, center: HLocation | null, radius: number): HFogModifier;
declare function CreateFogModifierRadiusLocSimple(whichPlayer: HPlayer | null, whichFogState: HFogState | null, center: HLocation | null, radius: number, afterUnits: boolean): HFogModifier;
declare function CreateFogModifierRectBJ(enabled: boolean, whichPlayer: HPlayer | null, whichFogState: HFogState | null, r: HRect | null): HFogModifier;
declare function CreateFogModifierRectSimple(whichPlayer: HPlayer | null, whichFogState: HFogState | null, r: HRect | null, afterUnits: boolean): HFogModifier;
declare function CreateImageBJ(file: string, size: number, where: HLocation | null, zOffset: number, imageType: number): HImage;
declare function CreateItemLoc(itemId: number, loc: HLocation | null): HItem;
declare function CreateLeaderboardBJ(toForce: HForce | null, label: string): HLeaderBoard;
declare function CreateMultiboardBJ(cols: number, rows: number, title: string): HMultiBoard;
declare function CreateNUnitsAtLoc(count: number, unitId: number, whichPlayer: HPlayer | null, loc: HLocation | null, face: number): HGroup;
declare function CreateNUnitsAtLocFacingLocBJ(count: number, unitId: number, whichPlayer: HPlayer | null, loc: HLocation | null, lookAt: HLocation | null): HGroup;
declare function CreatePermanentCorpseLocBJ(style: number, unitid: number, whichPlayer: HPlayer | null, loc: HLocation | null, facing: number): HUnit;
declare function CreateQuestBJ(questType: number, title: string, description: string, iconPath: string): HQuest;
declare function CreateQuestItemBJ(whichQuest: HQuest | null, description: string): HQuestItem;
declare function CreateTextTagLocBJ(s: string, loc: HLocation | null, zOffset: number, size: number, red: number, green: number, blue: number, transparency: number): HTextTag;
declare function CreateTextTagUnitBJ(s: string, whichUnit: HUnit | null, zOffset: number, size: number, red: number, green: number, blue: number, transparency: number): HTextTag;
declare function CreateTimerBJ(periodic: boolean, timeout: number): HTimer;
declare function CreateTimerDialogBJ(t: HTimer | null, title: string): HTimerDialog;
declare function CreateUbersplatBJ(where: HLocation | null, name: string, red: number, green: number, blue: number, alpha: number, forcePaused: boolean, noBirthTime: boolean): HUberSplat;
declare function CreateUnitAtLocSaveLast(id: HPlayer | null, unitid: number, loc: HLocation | null, face: number): HUnit;
declare function CustomDefeatBJ(whichPlayer: HPlayer | null, message: string): void;
declare function CustomDefeatDialogBJ(whichPlayer: HPlayer | null, message: string): void;
declare function CustomDefeatLoadBJ(): void;
declare function CustomDefeatQuitBJ(): void;
declare function CustomDefeatReduceDifficultyBJ(): void;
declare function CustomDefeatRestartBJ(): void;
declare function CustomVictoryBJ(whichPlayer: HPlayer | null, showDialog: boolean, showScores: boolean): void;
declare function CustomVictoryDialogBJ(whichPlayer: HPlayer | null): void;
declare function CustomVictoryOkBJ(): void;
declare function CustomVictoryQuitBJ(): void;
declare function CustomVictorySkipBJ(whichPlayer: HPlayer | null): void;
declare function DecUnitAbilityLevelSwapped(abilcode: number, whichUnit: HUnit | null): number;
declare function DefeatConditionSetDescriptionBJ(whichCondition: HDefeatCondition | null, description: string): void;
declare function DelayedSuspendDecay(): void;
declare function DelayedSuspendDecayBoneEnum(): void;
declare function DelayedSuspendDecayCreate(): void;
declare function DelayedSuspendDecayFleshEnum(): void;
declare function DelayedSuspendDecayStopAnimEnum(): void;
declare function DestroyDefeatConditionBJ(whichCondition: HDefeatCondition | null): void;
declare function DestroyEffectBJ(whichEffect: HEffect | null): void;
declare function DestroyLeaderboardBJ(lb: HLeaderBoard | null): void;
declare function DestroyLightningBJ(whichBolt: HLightning | null): boolean;
declare function DestroyMultiboardBJ(mb: HMultiBoard | null): void;
declare function DestroyQuestBJ(whichQuest: HQuest | null): void;
declare function DestroyTextTagBJ(tt: HTextTag | null): void;
declare function DestroyTimerBJ(whichTimer: HTimer | null): void;
declare function DestroyTimerDialogBJ(td: HTimerDialog | null): void;
declare function DestructableAddIndicatorBJ(whichDestructable: HDestructable | null, red: number, green: number, blue: number, transparency: number): void;
declare function DetectGameStarted(): void;
declare function DialogAddButtonBJ(whichDialog: HDialog | null, buttonText: string): HButton;
declare function DialogAddButtonWithHotkeyBJ(whichDialog: HDialog | null, buttonText: string, hotkey: number): HButton;
declare function DialogClearBJ(whichDialog: HDialog | null): void;
declare function DialogDisplayBJ(flag: boolean, whichDialog: HDialog | null, whichPlayer: HPlayer | null): void;
declare function DialogSetMessageBJ(whichDialog: HDialog | null, message: string): void;
declare function DisplayCineFilterBJ(flag: boolean): void;
declare function DisplayTextToForce(toForce: HForce | null, message: string): void;
declare function DisplayTimedTextToForce(toForce: HForce | null, duration: number, message: string): void;
declare function DistanceBetweenPoints(locA: HLocation | null, locB: HLocation | null): number;
declare function DoNothing(): void;
declare function DoTransmissionBasicsXYBJ(unitId: number, color: HPlayerColor | null, x: number, y: number, soundHandle: HSound | null, unitName: string, message: string, duration: number): void;
declare function DoesUnitGenerateAlarms(whichUnit: HUnit | null): boolean;
declare function EnableCreepSleepBJ(enable: boolean): void;
declare function EnableDawnDusk(flag: boolean): void;
declare function EnableOcclusionBJ(enable: boolean, f: HForce | null): void;
declare function EnableWorldFogBoundaryBJ(enable: boolean, f: HForce | null): void;
declare function EndGameBJ(): void;
declare function EndThematicMusicBJ(): void;
declare function EnumDestructablesInCircleBJ(radius: number, loc: HLocation | null, actionFunc: TCode): void;
declare function EnumDestructablesInCircleBJFilter(): boolean;
declare function EnumDestructablesInRectAll(r: HRect | null, actionFunc: TCode): void;
declare function EnumItemsInRectBJ(r: HRect | null, actionFunc: TCode): void;
declare function EnumUnitsSelected(whichPlayer: HPlayer | null, enumFilter: HBoolExpr | null, enumAction: TCode): void;
declare function ExplodeUnitBJ(whichUnit: HUnit | null): void;
declare function FFAInitPlayerSlots(): void;
declare function FindElevatorWallBlockerEnum(): void;
declare function FinishCinematicFadeAfterBJ(duration: number): void;
declare function FinishCinematicFadeBJ(): void;
declare function FlashQuestDialogButtonBJ(): void;
declare function FlushChildHashtableBJ(missionKey: number, table: HHashTable | null): void;
declare function FlushGameCacheBJ(cache: HGameCache | null): void;
declare function FlushParentHashtableBJ(table: HHashTable | null): void;
declare function FlushStoredMissionBJ(missionKey: string, cache: HGameCache | null): void;
declare function FogEnableOff(): void;
declare function FogEnableOn(): void;
declare function FogMaskEnableOff(): void;
declare function FogMaskEnableOn(): void;
declare function ForGroupBJ(whichGroup: HGroup | null, callback: TCode): void;
declare function ForceAddPlayerSimple(whichPlayer: HPlayer | null, whichForce: HForce | null): void;
declare function ForceCinematicSubtitlesBJ(flag: boolean): void;
declare function ForcePickRandomPlayer(whichForce: HForce | null): HPlayer;
declare function ForcePickRandomPlayerEnum(): void;
declare function ForceRemovePlayerSimple(whichPlayer: HPlayer | null, whichForce: HForce | null): void;
declare function ForceSetLeaderboardBJ(lb: HLeaderBoard | null, toForce: HForce | null): void;
declare function ForceUICancelBJ(whichPlayer: HPlayer | null): void;
declare function ForceUIKeyBJ(whichPlayer: HPlayer | null, key: string): void;
declare function GameOverDialogBJ(whichPlayer: HPlayer | null, leftGame: boolean): void;
declare function GetAbilityEffectBJ(abilcode: number, t: HEffectType | null, index: number): string;
declare function GetAbilityName(abilcode: number): string;
declare function GetAbilitySoundBJ(abilcode: number, t: HSoundType | null): string;
declare function GetAttackedUnitBJ(): HUnit;
declare function GetBooleanAnd(valueA: boolean, valueB: boolean): boolean;
declare function GetBooleanOr(valueA: boolean, valueB: boolean): boolean;
declare function GetCameraBoundsMapRect(): HRect;
declare function GetClickedButtonBJ(): HButton;
declare function GetClickedDialogBJ(): HDialog;
declare function GetConvertedPlayerId(whichPlayer: HPlayer | null): number;
declare function GetCurrentCameraBoundsMapRectBJ(): HRect;
declare function GetCurrentCameraSetup(): HCameraSetup;
declare function GetDestructableLoc(whichDestructable: HDestructable | null): HLocation;
declare function GetDyingDestructable(): HDestructable;
declare function GetElevatorHeight(d: HDestructable | null): number;
declare function GetEntireMapRect(): HRect;
declare function GetFadeFromSeconds(seconds: number): number;
declare function GetFadeFromSecondsAsReal(seconds: number): number;
declare function GetForLoopIndexA(): number;
declare function GetForLoopIndexB(): number;
declare function GetForceOfPlayer(whichPlayer: HPlayer | null): HForce;
declare function GetHandleIdBJ(h: HHandle | null): number;
declare function GetHeroStatBJ(whichStat: number, whichHero: HUnit | null, includeBonuses: boolean): number;
declare function GetInventoryIndexOfItemTypeBJ(whichUnit: HUnit | null, itemId: number): number;
declare function GetIssuedOrderIdBJ(): number;
declare function GetItemLifeBJ(whichWidget: HWidget | null): number;
declare function GetItemLoc(whichItem: HItem | null): HLocation;
declare function GetItemOfTypeFromUnitBJ(whichUnit: HUnit | null, itemId: number): HItem;
declare function GetKillingUnitBJ(): HUnit;
declare function GetLastCreatedButtonBJ(): HButton;
declare function GetLastCreatedDefeatConditionBJ(): HDefeatCondition;
declare function GetLastCreatedDestructable(): HDestructable;
declare function GetLastCreatedEffectBJ(): HEffect;
declare function GetLastCreatedFogModifier(): HFogModifier;
declare function GetLastCreatedGameCacheBJ(): HGameCache;
declare function GetLastCreatedGroup(): HGroup;
declare function GetLastCreatedGroupEnum(): void;
declare function GetLastCreatedHashtableBJ(): HHashTable;
declare function GetLastCreatedImage(): HImage;
declare function GetLastCreatedItem(): HItem;
declare function GetLastCreatedLeaderboard(): HLeaderBoard;
declare function GetLastCreatedLightningBJ(): HLightning;
declare function GetLastCreatedMultiboard(): HMultiBoard;
declare function GetLastCreatedQuestBJ(): HQuest;
declare function GetLastCreatedQuestItemBJ(): HQuestItem;
declare function GetLastCreatedTerrainDeformation(): HTerrainDeformation;
declare function GetLastCreatedTextTag(): HTextTag;
declare function GetLastCreatedTimerBJ(): HTimer;
declare function GetLastCreatedTimerDialogBJ(): HTimerDialog;
declare function GetLastCreatedUbersplat(): HUberSplat;
declare function GetLastCreatedUnit(): HUnit;
declare function GetLastCreatedWeatherEffect(): HWeatherEffect;
declare function GetLastHauntedGoldMine(): HUnit;
declare function GetLastPlayedMusic(): string;
declare function GetLastPlayedSound(): HSound;
declare function GetLastRemovedItem(): HItem;
declare function GetLastReplacedUnitBJ(): HUnit;
declare function GetLastRestoredUnitBJ(): HUnit;
declare function GetLastTransmissionDurationBJ(): number;
declare function GetLearnedSkillBJ(): number;
declare function GetLightningColorABJ(whichBolt: HLightning | null): number;
declare function GetLightningColorBBJ(whichBolt: HLightning | null): number;
declare function GetLightningColorGBJ(whichBolt: HLightning | null): number;
declare function GetLightningColorRBJ(whichBolt: HLightning | null): number;
declare function GetLoadedUnitBJ(): HUnit;
declare function GetPlayableMapRect(): HRect;
declare function GetPlayerHandicapBJ(whichPlayer: HPlayer | null): number;
declare function GetPlayerHandicapXPBJ(whichPlayer: HPlayer | null): number;
declare function GetPlayerStartLocationLoc(whichPlayer: HPlayer | null): HLocation;
declare function GetPlayerStartLocationX(whichPlayer: HPlayer | null): number;
declare function GetPlayerStartLocationY(whichPlayer: HPlayer | null): number;
declare function GetPlayerTaxRateBJ(whichResource: HPlayerState | null, sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null): number;
declare function GetPlayerTechCountSimple(techid: number, whichPlayer: HPlayer | null): number;
declare function GetPlayerTechMaxAllowedSwap(techid: number, whichPlayer: HPlayer | null): number;
declare function GetPlayersAll(): HForce;
declare function GetPlayersAllies(whichPlayer: HPlayer | null): HForce;
declare function GetPlayersByMapControl(whichControl: HMapControl | null): HForce;
declare function GetPlayersEnemies(whichPlayer: HPlayer | null): HForce;
declare function GetPlayersMatching(filter: HBoolExpr | null): HForce;
declare function GetRandomDirectionDeg(): number;
declare function GetRandomLocInRect(whichRect: HRect | null): HLocation;
declare function GetRandomPercentageBJ(): number;
declare function GetRandomSubGroup(count: number, sourceGroup: HGroup | null): HGroup;
declare function GetRandomSubGroupEnum(): void;
declare function GetRectCenter(whichRect: HRect | null): HLocation;
declare function GetRectFromCircleBJ(center: HLocation | null, radius: number): HRect;
declare function GetRectHeightBJ(r: HRect | null): number;
declare function GetRectWidthBJ(r: HRect | null): number;
declare function GetSoundDurationBJ(soundHandle: HSound | null): number;
declare function GetSoundFileDurationBJ(musicFileName: string): number;
declare function GetSoundIsPlayingBJ(soundHandle: HSound | null): boolean;
declare function GetStoredBooleanBJ(key: string, missionKey: string, cache: HGameCache | null): boolean;
declare function GetStoredIntegerBJ(key: string, missionKey: string, cache: HGameCache | null): number;
declare function GetStoredRealBJ(key: string, missionKey: string, cache: HGameCache | null): number;
declare function GetStoredStringBJ(key: string, missionKey: string, cache: HGameCache | null): string;
declare function GetTerrainCliffLevelBJ(where: HLocation | null): number;
declare function GetTerrainTypeBJ(where: HLocation | null): number;
declare function GetTerrainVarianceBJ(where: HLocation | null): number;
declare function GetTimeOfDay(): number;
declare function GetTimeOfDayScalePercentBJ(): number;
declare function GetTransmissionDuration(soundHandle: HSound | null, timeType: number, timeVal: number): number;
declare function GetTransportUnitBJ(): HUnit;
declare function GetUnitAbilityLevelSwapped(abilcode: number, whichUnit: HUnit | null): number;
declare function GetUnitDefaultPropWindowBJ(whichUnit: HUnit | null): number;
declare function GetUnitLifePercent(whichUnit: HUnit | null): number;
declare function GetUnitManaPercent(whichUnit: HUnit | null): number;
declare function GetUnitPropWindowBJ(whichUnit: HUnit | null): number;
declare function GetUnitStatePercent(whichUnit: HUnit | null, whichState: HUnitState | null, whichMaxState: HUnitState | null): number;
declare function GetUnitStateSwap(whichState: HUnitState | null, whichUnit: HUnit | null): number;
declare function GetUnitsInRangeOfLocAll(radius: number, whichLocation: HLocation | null): HGroup;
declare function GetUnitsInRangeOfLocMatching(radius: number, whichLocation: HLocation | null, filter: HBoolExpr | null): HGroup;
declare function GetUnitsInRectAll(r: HRect | null): HGroup;
declare function GetUnitsInRectMatching(r: HRect | null, filter: HBoolExpr | null): HGroup;
declare function GetUnitsInRectOfPlayer(r: HRect | null, whichPlayer: HPlayer | null): HGroup;
declare function GetUnitsInRectOfPlayerFilter(): boolean;
declare function GetUnitsOfPlayerAll(whichPlayer: HPlayer | null): HGroup;
declare function GetUnitsOfPlayerAndTypeId(whichPlayer: HPlayer | null, unitid: number): HGroup;
declare function GetUnitsOfPlayerAndTypeIdFilter(): boolean;
declare function GetUnitsOfPlayerMatching(whichPlayer: HPlayer | null, filter: HBoolExpr | null): HGroup;
declare function GetUnitsOfTypeIdAll(unitid: number): HGroup;
declare function GetUnitsOfTypeIdAllFilter(): boolean;
declare function GetUnitsSelectedAll(whichPlayer: HPlayer | null): HGroup;
declare function GroupAddGroup(sourceGroup: HGroup | null, destGroup: HGroup | null): void;
declare function GroupAddGroupEnum(): void;
declare function GroupAddUnitSimple(whichUnit: HUnit | null, whichGroup: HGroup | null): void;
declare function GroupImmediateOrderBJ(whichGroup: HGroup | null, order: string): boolean;
declare function GroupPickRandomUnit(whichGroup: HGroup | null): HUnit;
declare function GroupPickRandomUnitEnum(): void;
declare function GroupPointOrderLocBJ(whichGroup: HGroup | null, order: string, whichLocation: HLocation | null): boolean;
declare function GroupRemoveGroup(sourceGroup: HGroup | null, destGroup: HGroup | null): void;
declare function GroupRemoveGroupEnum(): void;
declare function GroupRemoveUnitSimple(whichUnit: HUnit | null, whichGroup: HGroup | null): void;
declare function GroupTargetDestructableOrder(whichGroup: HGroup | null, order: string, targetWidget: HWidget | null): boolean;
declare function GroupTargetItemOrder(whichGroup: HGroup | null, order: string, targetWidget: HWidget | null): boolean;
declare function GroupTargetOrderBJ(whichGroup: HGroup | null, order: string, targetWidget: HWidget | null): boolean;
declare function GroupTrainOrderByIdBJ(g: HGroup | null, unitId: number): boolean;
declare function HaveSavedValue(key: number, valueType: number, missionKey: number, table: HHashTable | null): boolean;
declare function HaveStoredValue(key: string, valueType: number, missionKey: string, cache: HGameCache | null): boolean;
declare function IAbsBJ(a: number): number;
declare function IMaxBJ(a: number, b: number): number;
declare function IMinBJ(a: number, b: number): number;
declare function ISignBJ(a: number): number;
declare function IncUnitAbilityLevelSwapped(abilcode: number, whichUnit: HUnit | null): number;
declare function InitBlizzard(): void;
declare function InitBlizzardGlobals(): void;
declare function InitDNCSounds(): void;
declare function InitGameCacheBJ(campaignFile: string): HGameCache;
declare function InitGenericPlayerSlots(): void;
declare function InitHashtableBJ(): HHashTable;
declare function InitMapRects(): void;
declare function InitNeutralBuildings(): void;
declare function InitQueuedTriggers(): void;
declare function InitRescuableBehaviorBJ(): void;
declare function InitSummonableCaps(): void;
declare function IntegerTertiaryOp(flag: boolean, valueA: number, valueB: number): number;
declare function IsCustomCampaignButtonVisibile(whichButton: number): boolean;
declare function IsDawnDuskEnabled(): boolean;
declare function IsDestructableAliveBJ(d: HDestructable | null): boolean;
declare function IsDestructableDeadBJ(d: HDestructable | null): boolean;
declare function IsDestructableInvulnerableBJ(d: HDestructable | null): boolean;
declare function IsItemHiddenBJ(whichItem: HItem | null): boolean;
declare function IsPlayerFlagSetBJ(whichPlayerFlag: HPlayerState | null, whichPlayer: HPlayer | null): boolean;
declare function IsPlayerSlotState(whichPlayer: HPlayer | null, whichState: HPlayerSlotState | null): boolean;
declare function IsPointBlightedBJ(where: HLocation | null): boolean;
declare function IsTerrainPathableBJ(where: HLocation | null, t: HPathingType | null): boolean;
declare function IsTriggerQueueEmptyBJ(): boolean;
declare function IsTriggerQueuedBJ(trig: HTrigger | null): boolean;
declare function IsUnitAliveBJ(whichUnit: HUnit | null): boolean;
declare function IsUnitDeadBJ(whichUnit: HUnit | null): boolean;
declare function IsUnitGroupDeadBJ(g: HGroup | null): boolean;
declare function IsUnitGroupDeadBJEnum(): void;
declare function IsUnitGroupEmptyBJ(g: HGroup | null): boolean;
declare function IsUnitGroupEmptyBJEnum(): void;
declare function IsUnitGroupInRectBJ(g: HGroup | null, r: HRect | null): boolean;
declare function IsUnitGroupInRectBJEnum(): void;
declare function IsUnitHiddenBJ(whichUnit: HUnit | null): boolean;
declare function IsUnitIllusionBJ(whichUnit: HUnit | null): boolean;
declare function IsUnitInTransportBJ(whichUnit: HUnit | null, whichTransport: HUnit | null): boolean;
declare function IsUnitLoadedBJ(whichUnit: HUnit | null): boolean;
declare function IsUnitPausedBJ(whichUnit: HUnit | null): boolean;
declare function IssueBuildOrderByIdLocBJ(whichPeon: HUnit | null, unitId: number, loc: HLocation | null): boolean;
declare function IssueHauntOrderAtLocBJ(whichPeon: HUnit | null, loc: HLocation | null): boolean;
declare function IssueHauntOrderAtLocBJFilter(): boolean;
declare function IssueImmediateOrderBJ(whichUnit: HUnit | null, order: string): boolean;
declare function IssuePointOrderLocBJ(whichUnit: HUnit | null, order: string, whichLocation: HLocation | null): boolean;
declare function IssueTargetDestructableOrder(whichUnit: HUnit | null, order: string, targetWidget: HWidget | null): boolean;
declare function IssueTargetItemOrder(whichUnit: HUnit | null, order: string, targetWidget: HWidget | null): boolean;
declare function IssueTargetOrderBJ(whichUnit: HUnit | null, order: string, targetWidget: HWidget | null): boolean;
declare function IssueTrainOrderByIdBJ(whichUnit: HUnit | null, unitId: number): boolean;
declare function IssueUpgradeOrderByIdBJ(whichUnit: HUnit | null, techId: number): boolean;
declare function ItemAddIndicatorBJ(whichItem: HItem | null, red: number, green: number, blue: number, transparency: number): void;
declare function KillSoundWhenDoneBJ(soundHandle: HSound | null): void;
declare function LeaderboardAddItemBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null, label: string, value: number): void;
declare function LeaderboardDisplayBJ(show: boolean, lb: HLeaderBoard | null): void;
declare function LeaderboardGetIndexedPlayerBJ(position: number, lb: HLeaderBoard | null): HPlayer;
declare function LeaderboardGetItemCountBJ(lb: HLeaderBoard | null): number;
declare function LeaderboardGetPlayerIndexBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null): number;
declare function LeaderboardHasPlayerItemBJ(lb: HLeaderBoard | null, whichPlayer: HPlayer | null): boolean;
declare function LeaderboardRemovePlayerItemBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null): void;
declare function LeaderboardResizeBJ(lb: HLeaderBoard | null): void;
declare function LeaderboardSetLabelBJ(lb: HLeaderBoard | null, label: string): void;
declare function LeaderboardSetLabelColorBJ(lb: HLeaderBoard | null, red: number, green: number, blue: number, transparency: number): void;
declare function LeaderboardSetPlayerItemLabelBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null, val: string): void;
declare function LeaderboardSetPlayerItemLabelColorBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null, red: number, green: number, blue: number, transparency: number): void;
declare function LeaderboardSetPlayerItemStyleBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null, showLabel: boolean, showValue: boolean, showIcon: boolean): void;
declare function LeaderboardSetPlayerItemValueBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null, val: number): void;
declare function LeaderboardSetPlayerItemValueColorBJ(whichPlayer: HPlayer | null, lb: HLeaderBoard | null, red: number, green: number, blue: number, transparency: number): void;
declare function LeaderboardSetStyleBJ(lb: HLeaderBoard | null, showLabel: boolean, showNames: boolean, showValues: boolean, showIcons: boolean): void;
declare function LeaderboardSetValueColorBJ(lb: HLeaderBoard | null, red: number, green: number, blue: number, transparency: number): void;
declare function LeaderboardSortItemsBJ(lb: HLeaderBoard | null, sortType: number, ascending: boolean): void;
declare function LeaderboardSortItemsByLabelBJ(lb: HLeaderBoard | null, ascending: boolean): void;
declare function LeaderboardSortItemsByPlayerBJ(lb: HLeaderBoard | null, ascending: boolean): void;
declare function LivingPlayerUnitsOfTypeIdFilter(): boolean;
declare function LoadAbilityHandleBJ(key: number, missionKey: number, table: HHashTable | null): HAbility;
declare function LoadBooleanBJ(key: number, missionKey: number, table: HHashTable | null): boolean;
declare function LoadBooleanExprHandleBJ(key: number, missionKey: number, table: HHashTable | null): HBoolExpr;
declare function LoadButtonHandleBJ(key: number, missionKey: number, table: HHashTable | null): HButton;
declare function LoadDefeatConditionHandleBJ(key: number, missionKey: number, table: HHashTable | null): HDefeatCondition;
declare function LoadDestructableHandleBJ(key: number, missionKey: number, table: HHashTable | null): HDestructable;
declare function LoadDialogHandleBJ(key: number, missionKey: number, table: HHashTable | null): HDialog;
declare function LoadEffectHandleBJ(key: number, missionKey: number, table: HHashTable | null): HEffect;
declare function LoadFogModifierHandleBJ(key: number, missionKey: number, table: HHashTable | null): HFogModifier;
declare function LoadFogStateHandleBJ(key: number, missionKey: number, table: HHashTable | null): HFogState;
declare function LoadForceHandleBJ(key: number, missionKey: number, table: HHashTable | null): HForce;
declare function LoadGameBJ(loadFileName: string, doScoreScreen: boolean): void;
declare function LoadGroupHandleBJ(key: number, missionKey: number, table: HHashTable | null): HGroup;
declare function LoadHashtableHandleBJ(key: number, missionKey: number, table: HHashTable | null): HHashTable;
declare function LoadImageHandleBJ(key: number, missionKey: number, table: HHashTable | null): HImage;
declare function LoadIntegerBJ(key: number, missionKey: number, table: HHashTable | null): number;
declare function LoadItemHandleBJ(key: number, missionKey: number, table: HHashTable | null): HItem;
declare function LoadItemPoolHandleBJ(key: number, missionKey: number, table: HHashTable | null): HItemPool;
declare function LoadLeaderboardHandleBJ(key: number, missionKey: number, table: HHashTable | null): HLeaderBoard;
declare function LoadLightningHandleBJ(key: number, missionKey: number, table: HHashTable | null): HLightning;
declare function LoadLocationHandleBJ(key: number, missionKey: number, table: HHashTable | null): HLocation;
declare function LoadMultiboardHandleBJ(key: number, missionKey: number, table: HHashTable | null): HMultiBoard;
declare function LoadMultiboardItemHandleBJ(key: number, missionKey: number, table: HHashTable | null): HMultiBoardItem;
declare function LoadPlayerHandleBJ(key: number, missionKey: number, table: HHashTable | null): HPlayer;
declare function LoadQuestHandleBJ(key: number, missionKey: number, table: HHashTable | null): HQuest;
declare function LoadQuestItemHandleBJ(key: number, missionKey: number, table: HHashTable | null): HQuestItem;
declare function LoadRealBJ(key: number, missionKey: number, table: HHashTable | null): number;
declare function LoadRectHandleBJ(key: number, missionKey: number, table: HHashTable | null): HRect;
declare function LoadRegionHandleBJ(key: number, missionKey: number, table: HHashTable | null): HRegion;
declare function LoadSoundHandleBJ(key: number, missionKey: number, table: HHashTable | null): HSound;
declare function LoadStringBJ(key: number, missionKey: number, table: HHashTable | null): string;
declare function LoadTextTagHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTextTag;
declare function LoadTimerDialogHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTimerDialog;
declare function LoadTimerHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTimer;
declare function LoadTrackableHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTrackable;
declare function LoadTriggerActionHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTriggerAction;
declare function LoadTriggerConditionHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTriggerCondition;
declare function LoadTriggerEventHandleBJ(key: number, missionKey: number, table: HHashTable | null): HEvent;
declare function LoadTriggerHandleBJ(key: number, missionKey: number, table: HHashTable | null): HTrigger;
declare function LoadUbersplatHandleBJ(key: number, missionKey: number, table: HHashTable | null): HUberSplat;
declare function LoadUnitHandleBJ(key: number, missionKey: number, table: HHashTable | null): HUnit;
declare function LoadUnitPoolHandleBJ(key: number, missionKey: number, table: HHashTable | null): HUnitPool;
declare function LoadWidgetHandleBJ(key: number, missionKey: number, table: HHashTable | null): HWidget;
declare function LockGameSpeedBJ(): void;
declare function LockGuardPosition(targ: HUnit | null): void;
declare function MakeUnitRescuableToForceBJ(whichUnit: HUnit | null, isRescuable: boolean, whichForce: HForce | null): void;
declare function MakeUnitRescuableToForceBJEnum(): void;
declare function MakeUnitsPassiveForPlayer(whichPlayer: HPlayer | null): void;
declare function MakeUnitsPassiveForPlayerEnum(): void;
declare function MakeUnitsPassiveForTeam(whichPlayer: HPlayer | null): void;
declare function MarkGameStarted(): void;
declare function MeleeCheckAddedUnit(addedUnit: HUnit | null): void;
declare function MeleeCheckForCrippledPlayers(): void;
declare function MeleeCheckForLosersAndVictors(): void;
declare function MeleeCheckForVictors(): HForce;
declare function MeleeCheckLostUnit(lostUnit: HUnit | null): void;
declare function MeleeClearExcessUnit(): void;
declare function MeleeClearExcessUnits(): void;
declare function MeleeClearNearbyUnits(x: number, y: number, range: number): void;
declare function MeleeCrippledPlayerTimeout(): void;
declare function MeleeDefeatDialogBJ(whichPlayer: HPlayer | null, leftGame: boolean): void;
declare function MeleeDoDefeat(whichPlayer: HPlayer | null): void;
declare function MeleeDoDefeatEnum(): void;
declare function MeleeDoDrawEnum(): void;
declare function MeleeDoLeave(whichPlayer: HPlayer | null): void;
declare function MeleeDoVictoryEnum(): void;
declare function MeleeEnumFindNearestMine(): void;
declare function MeleeExposeAllPlayers(): void;
declare function MeleeExposePlayer(whichPlayer: HPlayer | null, expose: boolean): void;
declare function MeleeFindNearestMine(src: HLocation | null, range: number): HUnit;
declare function MeleeGetAllyCount(whichPlayer: HPlayer | null): number;
declare function MeleeGetAllyKeyStructureCount(whichPlayer: HPlayer | null): number;
declare function MeleeGetAllyStructureCount(whichPlayer: HPlayer | null): number;
declare function MeleeGetCrippledRevealedMessage(whichPlayer: HPlayer | null): string;
declare function MeleeGetCrippledTimerMessage(whichPlayer: HPlayer | null): string;
declare function MeleeGetCrippledWarningMessage(whichPlayer: HPlayer | null): string;
declare function MeleeGetLocWithinRect(src: HLocation | null, r: HRect | null): HLocation;
declare function MeleeGetNearestValueWithin(val: number, minVal: number, maxVal: number): number;
declare function MeleeGetProjectedLoc(src: HLocation | null, targ: HLocation | null, distance: number, deltaAngle: number): HLocation;
declare function MeleeGrantHeroItems(): void;
declare function MeleeGrantItemsToHero(whichUnit: HUnit | null): void;
declare function MeleeGrantItemsToHiredHero(): void;
declare function MeleeGrantItemsToTrainedHero(): void;
declare function MeleeInitPlayerSlots(): void;
declare function MeleeInitVictoryDefeat(): void;
declare function MeleePlayerIsCrippled(whichPlayer: HPlayer | null): boolean;
declare function MeleePlayerIsOpponent(playerIndex: number, opponentIndex: number): boolean;
declare function MeleeRandomHeroLoc(p: HPlayer | null, id1: number, id2: number, id3: number, id4: number, loc: HLocation | null): HUnit;
declare function MeleeRemoveObservers(): void;
declare function MeleeStartingAI(): void;
declare function MeleeStartingHeroLimit(): void;
declare function MeleeStartingResources(): void;
declare function MeleeStartingUnits(): void;
declare function MeleeStartingUnitsForPlayer(whichRace: HRace | null, whichPlayer: HPlayer | null, loc: HLocation | null, doHeroes: boolean): void;
declare function MeleeStartingUnitsHuman(whichPlayer: HPlayer | null, startLoc: HLocation | null, doHeroes: boolean, doCamera: boolean, doPreload: boolean): void;
declare function MeleeStartingUnitsNightElf(whichPlayer: HPlayer | null, startLoc: HLocation | null, doHeroes: boolean, doCamera: boolean, doPreload: boolean): void;
declare function MeleeStartingUnitsOrc(whichPlayer: HPlayer | null, startLoc: HLocation | null, doHeroes: boolean, doCamera: boolean, doPreload: boolean): void;
declare function MeleeStartingUnitsUndead(whichPlayer: HPlayer | null, startLoc: HLocation | null, doHeroes: boolean, doCamera: boolean, doPreload: boolean): void;
declare function MeleeStartingUnitsUnknownRace(whichPlayer: HPlayer | null, startLoc: HLocation | null, doHeroes: boolean, doCamera: boolean, doPreload: boolean): void;
declare function MeleeStartingVisibility(): void;
declare function MeleeTournamentFinishNowRuleA(multiplier: number): void;
declare function MeleeTrainedUnitIsHeroBJFilter(): boolean;
declare function MeleeTriggerActionAllianceChange(): void;
declare function MeleeTriggerActionConstructCancel(): void;
declare function MeleeTriggerActionPlayerDefeated(): void;
declare function MeleeTriggerActionPlayerLeft(): void;
declare function MeleeTriggerActionUnitConstructionStart(): void;
declare function MeleeTriggerActionUnitDeath(): void;
declare function MeleeTriggerTournamentFinishNow(): void;
declare function MeleeTriggerTournamentFinishSoon(): void;
declare function MeleeVictoryDialogBJ(whichPlayer: HPlayer | null, leftGame: boolean): void;
declare function MeleeWasUserPlayer(whichPlayer: HPlayer | null): boolean;
declare function ModifyGateBJ(gateOperation: number, d: HDestructable | null): void;
declare function ModifyHeroSkillPoints(whichHero: HUnit | null, modifyMethod: number, value: number): boolean;
declare function ModifyHeroStat(whichStat: number, whichHero: HUnit | null, modifyMethod: number, value: number): void;
declare function ModuloInteger(dividend: number, divisor: number): number;
declare function ModuloReal(dividend: number, divisor: number): number;
declare function MoveLightningLoc(whichBolt: HLightning | null, where1: HLocation | null, where2: HLocation | null): boolean;
declare function MultiboardAllowDisplayBJ(flag: boolean): void;
declare function MultiboardDisplayBJ(show: boolean, mb: HMultiBoard | null): void;
declare function MultiboardMinimizeBJ(minimize: boolean, mb: HMultiBoard | null): void;
declare function MultiboardSetItemColorBJ(mb: HMultiBoard | null, col: number, row: number, red: number, green: number, blue: number, transparency: number): void;
declare function MultiboardSetItemIconBJ(mb: HMultiBoard | null, col: number, row: number, iconFileName: string): void;
declare function MultiboardSetItemStyleBJ(mb: HMultiBoard | null, col: number, row: number, showValue: boolean, showIcon: boolean): void;
declare function MultiboardSetItemValueBJ(mb: HMultiBoard | null, col: number, row: number, val: string): void;
declare function MultiboardSetItemWidthBJ(mb: HMultiBoard | null, col: number, row: number, width: number): void;
declare function MultiboardSetTitleTextColorBJ(mb: HMultiBoard | null, red: number, green: number, blue: number, transparency: number): void;
declare function NearbyElevatorExists(x: number, y: number): boolean;
declare function NearbyElevatorExistsEnum(): void;
declare function NudgeItemsInRectEnum(): void;
declare function NudgeObjectsInRect(nudgeArea: HRect | null): void;
declare function NudgeUnitsInRectEnum(): void;
declare function OffsetLocation(loc: HLocation | null, dx: number, dy: number): HLocation;
declare function OffsetRectBJ(r: HRect | null, dx: number, dy: number): HRect;
declare function OneOnOneInitPlayerSlots(): void;
declare function OrderId2StringBJ(orderId: number): string;
declare function PanCameraToForPlayer(whichPlayer: HPlayer | null, x: number, y: number): void;
declare function PanCameraToLocForPlayer(whichPlayer: HPlayer | null, loc: HLocation | null): void;
declare function PanCameraToTimedForPlayer(whichPlayer: HPlayer | null, x: number, y: number, duration: number): void;
declare function PanCameraToTimedLocForPlayer(whichPlayer: HPlayer | null, loc: HLocation | null, duration: number): void;
declare function PanCameraToTimedLocWithZForPlayer(whichPlayer: HPlayer | null, loc: HLocation | null, zOffset: number, duration: number): void;
declare function PauseAllUnitsBJ(pause: boolean): void;
declare function PauseAllUnitsBJEnum(): void;
declare function PauseGameOff(): void;
declare function PauseGameOn(): void;
declare function PauseTimerBJ(pause: boolean, whichTimer: HTimer | null): void;
declare function PauseUnitBJ(pause: boolean, whichUnit: HUnit | null): void;
declare function PercentTo255(percentage: number): number;
declare function PercentToInt(percentage: number, max: number): number;
declare function PerformStockUpdates(): void;
declare function PickMeleeAI(num: HPlayer | null, s1: string, s2: string, s3: string): void;
declare function PingMinimapForForce(whichForce: HForce | null, x: number, y: number, duration: number): void;
declare function PingMinimapForForceEx(whichForce: HForce | null, x: number, y: number, duration: number, style: number, red: number, green: number, blue: number): void;
declare function PingMinimapForPlayer(whichPlayer: HPlayer | null, x: number, y: number, duration: number): void;
declare function PingMinimapLocForForce(whichForce: HForce | null, loc: HLocation | null, duration: number): void;
declare function PingMinimapLocForForceEx(whichForce: HForce | null, loc: HLocation | null, duration: number, style: number, red: number, green: number, blue: number): void;
declare function PingMinimapLocForPlayer(whichPlayer: HPlayer | null, loc: HLocation | null, duration: number): void;
declare function PlayMusicBJ(musicFileName: string): void;
declare function PlayMusicExBJ(musicFileName: string, startingOffset: number, fadeInTime: number): void;
declare function PlaySound(soundName: string): void;
declare function PlaySoundAtPointBJ(soundHandle: HSound | null, volumePercent: number, loc: HLocation | null, z: number): void;
declare function PlaySoundBJ(soundHandle: HSound | null): void;
declare function PlaySoundFromOffsetBJ(soundHandle: HSound | null, volumePercent: number, startingOffset: number): void;
declare function PlaySoundOnUnitBJ(soundHandle: HSound | null, volumePercent: number, whichUnit: HUnit | null): void;
declare function PlayThematicMusicBJ(musicName: string): void;
declare function PlayThematicMusicExBJ(musicName: string, startingOffset: number): void;
declare function PlayerGetLeaderboardBJ(whichPlayer: HPlayer | null): HLeaderBoard;
declare function PlayersAreCoAllied(playerA: HPlayer | null, playerB: HPlayer | null): boolean;
declare function PolarProjectionBJ(source: HLocation | null, dist: number, angle: number): HLocation;
declare function PolledWait(duration: number): void;
declare function PostTriggerExecuteBJ(trig: HTrigger | null, checkConditions: boolean): boolean;
declare function QuestItemSetCompletedBJ(whichQuestItem: HQuestItem | null, completed: boolean): void;
declare function QuestItemSetDescriptionBJ(whichQuestItem: HQuestItem | null, description: string): void;
declare function QuestMessageBJ(f: HForce | null, messageType: number, message: string): void;
declare function QuestSetCompletedBJ(whichQuest: HQuest | null, completed: boolean): void;
declare function QuestSetDescriptionBJ(whichQuest: HQuest | null, description: string): void;
declare function QuestSetDiscoveredBJ(whichQuest: HQuest | null, discovered: boolean): void;
declare function QuestSetEnabledBJ(enabled: boolean, whichQuest: HQuest | null): void;
declare function QuestSetFailedBJ(whichQuest: HQuest | null, failed: boolean): void;
declare function QuestSetTitleBJ(whichQuest: HQuest | null, title: string): void;
declare function QueueDestructableAnimationBJ(d: HDestructable | null, whichAnimation: string): void;
declare function QueueUnitAnimationBJ(whichUnit: HUnit | null, whichAnimation: string): void;
declare function QueuedTriggerAddBJ(trig: HTrigger | null, checkConditions: boolean): boolean;
declare function QueuedTriggerAttemptExec(): boolean;
declare function QueuedTriggerCheck(): void;
declare function QueuedTriggerClearBJ(): void;
declare function QueuedTriggerClearInactiveBJ(): void;
declare function QueuedTriggerCountBJ(): number;
declare function QueuedTriggerDoneBJ(): void;
declare function QueuedTriggerGetIndex(trig: HTrigger | null): number;
declare function QueuedTriggerRemoveBJ(trig: HTrigger | null): void;
declare function QueuedTriggerRemoveByIndex(trigIndex: number): boolean;
declare function RAbsBJ(a: number): number;
declare function RMaxBJ(a: number, b: number): number;
declare function RMinBJ(a: number, b: number): number;
declare function RSignBJ(a: number): number;
declare function RandomDestructableInRectBJ(r: HRect | null, filter: HBoolExpr | null): HDestructable;
declare function RandomDestructableInRectBJEnum(): void;
declare function RandomDestructableInRectSimpleBJ(r: HRect | null): HDestructable;
declare function RandomDistAddItem(inID: number, inChance: number): void;
declare function RandomDistChoose(): number;
declare function RandomDistReset(): void;
declare function RandomItemInRectBJ(r: HRect | null, filter: HBoolExpr | null): HItem;
declare function RandomItemInRectBJEnum(): void;
declare function RandomItemInRectSimpleBJ(r: HRect | null): HItem;
declare function RectContainsCoords(r: HRect | null, x: number, y: number): boolean;
declare function RectContainsItem(whichItem: HItem | null, r: HRect | null): boolean;
declare function RectContainsLoc(r: HRect | null, loc: HLocation | null): boolean;
declare function RectContainsUnit(r: HRect | null, whichUnit: HUnit | null): boolean;
declare function RectFromCenterSizeBJ(center: HLocation | null, width: number, height: number): HRect;
declare function ReducePlayerTechMaxAllowed(whichPlayer: HPlayer | null, techId: number, limit: number): void;
declare function RegisterDestDeathInRegionEnum(): void;
declare function RemoveItemFromStockBJ(itemId: number, whichUnit: HUnit | null): void;
declare function RemovePlayerPreserveUnitsBJ(whichPlayer: HPlayer | null, gameResult: HPlayerGameResult | null, leftGame: boolean): void;
declare function RemovePurchasedItem(): void;
declare function RemoveSaveDirectoryBJ(sourceDirName: string): boolean;
declare function RemoveUnitFromStockBJ(unitId: number, whichUnit: HUnit | null): void;
declare function RemoveWeatherEffectBJ(whichWeatherEffect: HWeatherEffect | null): void;
declare function RenameSaveDirectoryBJ(sourceDirName: string, destDirName: string): boolean;
declare function ReplaceUnitBJ(whichUnit: HUnit | null, newUnitId: number, unitStateMethod: number): HUnit;
declare function RescueUnitBJ(whichUnit: HUnit | null, rescuer: HPlayer | null, changeColor: boolean): void;
declare function ResetTerrainFogBJ(): void;
declare function ResetToGameCameraForPlayer(whichPlayer: HPlayer | null, duration: number): void;
declare function ResetUnitAnimation(whichUnit: HUnit | null): void;
declare function RestoreUnitLocFacingAngleBJ(key: string, missionKey: string, cache: HGameCache | null, forWhichPlayer: HPlayer | null, loc: HLocation | null, facing: number): HUnit;
declare function RestoreUnitLocFacingPointBJ(key: string, missionKey: string, cache: HGameCache | null, forWhichPlayer: HPlayer | null, loc: HLocation | null, lookAt: HLocation | null): HUnit;
declare function ResumeMusicBJ(): void;
declare function RotateCameraAroundLocBJ(degrees: number, loc: HLocation | null, whichPlayer: HPlayer | null, duration: number): void;
declare function SaveAbilityHandleBJ(whichAbility: HAbility | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveAgentHandleBJ(whichAgent: HAgent | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveAndChangeLevelBJ(saveFileName: string, newLevel: string, doScoreScreen: boolean): void;
declare function SaveAndLoadGameBJ(saveFileName: string, loadFileName: string, doScoreScreen: boolean): void;
declare function SaveBooleanBJ(value: boolean, key: number, missionKey: number, table: HHashTable | null): void;
declare function SaveBooleanExprHandleBJ(whichBoolexpr: HBoolExpr | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveButtonHandleBJ(whichButton: HButton | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveDefeatConditionHandleBJ(whichDefeatcondition: HDefeatCondition | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveDestructableHandleBJ(whichDestructable: HDestructable | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveDialogHandleBJ(whichDialog: HDialog | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveDyingWidget(): void;
declare function SaveEffectHandleBJ(whichEffect: HEffect | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveFogModifierHandleBJ(whichFogModifier: HFogModifier | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveFogStateHandleBJ(whichFogState: HFogState | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveForceHandleBJ(whichForce: HForce | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveGameCacheBJ(cache: HGameCache | null): boolean;
declare function SaveGroupHandleBJ(whichGroup: HGroup | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveHashtableHandleBJ(whichHashtable: HHashTable | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveImageHandleBJ(whichImage: HImage | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveIntegerBJ(value: number, key: number, missionKey: number, table: HHashTable | null): void;
declare function SaveItemHandleBJ(whichItem: HItem | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveItemPoolHandleBJ(whichItempool: HItemPool | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveLeaderboardHandleBJ(whichLeaderboard: HLeaderBoard | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveLightningHandleBJ(whichLightning: HLightning | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveLocationHandleBJ(whichLocation: HLocation | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveMultiboardHandleBJ(whichMultiboard: HMultiBoard | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveMultiboardItemHandleBJ(whichMultiboarditem: HMultiBoardItem | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SavePlayerHandleBJ(whichPlayer: HPlayer | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveQuestHandleBJ(whichQuest: HQuest | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveQuestItemHandleBJ(whichQuestitem: HQuestItem | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveRealBJ(value: number, key: number, missionKey: number, table: HHashTable | null): void;
declare function SaveRectHandleBJ(whichRect: HRect | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveRegionHandleBJ(whichRegion: HRegion | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveSoundHandleBJ(whichSound: HSound | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveStringBJ(value: string, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTextTagHandleBJ(whichTexttag: HTextTag | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTimerDialogHandleBJ(whichTimerdialog: HTimerDialog | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTimerHandleBJ(whichTimer: HTimer | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTrackableHandleBJ(whichTrackable: HTrackable | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTriggerActionHandleBJ(whichTriggeraction: HTriggerAction | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTriggerConditionHandleBJ(whichTriggercondition: HTriggerCondition | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTriggerEventHandleBJ(whichEvent: HEvent | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveTriggerHandleBJ(whichTrigger: HTrigger | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveUbersplatHandleBJ(whichUbersplat: HUberSplat | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveUnitHandleBJ(whichUnit: HUnit | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveUnitPoolHandleBJ(whichUnitpool: HUnitPool | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SaveWidgetHandleBJ(whichWidget: HWidget | null, key: number, missionKey: number, table: HHashTable | null): boolean;
declare function SelectGroupBJ(g: HGroup | null): void;
declare function SelectGroupBJEnum(): void;
declare function SelectGroupForPlayerBJ(g: HGroup | null, whichPlayer: HPlayer | null): void;
declare function SelectUnitAdd(whichUnit: HUnit | null): void;
declare function SelectUnitAddForPlayer(whichUnit: HUnit | null, whichPlayer: HPlayer | null): void;
declare function SelectUnitForPlayerSingle(whichUnit: HUnit | null, whichPlayer: HPlayer | null): void;
declare function SelectUnitRemove(whichUnit: HUnit | null): void;
declare function SelectUnitRemoveForPlayer(whichUnit: HUnit | null, whichPlayer: HPlayer | null): void;
declare function SelectUnitSingle(whichUnit: HUnit | null): void;
declare function SetAmbientDaySound(inLabel: string): void;
declare function SetAmbientNightSound(inLabel: string): void;
declare function SetBlightRadiusLocBJ(addBlight: boolean, whichPlayer: HPlayer | null, loc: HLocation | null, radius: number): void;
declare function SetBlightRectBJ(addBlight: boolean, whichPlayer: HPlayer | null, r: HRect | null): void;
declare function SetCameraBoundsToRect(r: HRect | null): void;
declare function SetCameraBoundsToRectForPlayerBJ(whichPlayer: HPlayer | null, r: HRect | null): void;
declare function SetCameraFieldForPlayer(whichPlayer: HPlayer | null, whichField: HCameraField | null, value: number, duration: number): void;
declare function SetCameraOrientControllerForPlayerBJ(whichPlayer: HPlayer | null, whichUnit: HUnit | null, xoffset: number, yoffset: number): void;
declare function SetCameraPositionForPlayer(whichPlayer: HPlayer | null, x: number, y: number): void;
declare function SetCameraPositionLocForPlayer(whichPlayer: HPlayer | null, loc: HLocation | null): void;
declare function SetCameraQuickPositionForPlayer(whichPlayer: HPlayer | null, x: number, y: number): void;
declare function SetCameraQuickPositionLoc(loc: HLocation | null): void;
declare function SetCameraQuickPositionLocForPlayer(whichPlayer: HPlayer | null, loc: HLocation | null): void;
declare function SetCameraTargetControllerNoZForPlayer(whichPlayer: HPlayer | null, whichUnit: HUnit | null, xoffset: number, yoffset: number, inheritOrientation: boolean): void;
declare function SetCampaignAvailableBJ(available: boolean, campaignNumber: number): void;
declare function SetCampaignMenuRaceBJ(campaignNumber: number): void;
declare function SetCineModeVolumeGroupsBJ(): void;
declare function SetCineModeVolumeGroupsImmediateBJ(): void;
declare function SetCinematicAvailableBJ(available: boolean, cinematicIndex: number): void;
declare function SetCinematicCameraForPlayer(whichPlayer: HPlayer | null, cameraModelFile: string): void;
declare function SetCinematicSceneBJ(soundHandle: HSound | null, portraitUnitId: number, color: HPlayerColor | null, speakerTitle: string, text: string, sceneDuration: number, voiceoverDuration: number): void;
declare function SetDNCSoundsDawn(): void;
declare function SetDNCSoundsDay(): void;
declare function SetDNCSoundsDusk(): void;
declare function SetDNCSoundsNight(): void;
declare function SetDestAnimationSpeedPercent(d: HDestructable | null, percentScale: number): void;
declare function SetDestructableAnimationBJ(d: HDestructable | null, whichAnimation: string): void;
declare function SetDestructableInvulnerableBJ(d: HDestructable | null, flag: boolean): void;
declare function SetDestructableLifePercentBJ(d: HDestructable | null, percent: number): void;
declare function SetDestructableMaxLifeBJ(d: HDestructable | null, max: number): void;
declare function SetDoodadAnimationBJ(animName: string, doodadID: number, radius: number, center: HLocation | null): void;
declare function SetDoodadAnimationRectBJ(animName: string, doodadID: number, r: HRect | null): void;
declare function SetForLoopIndexA(newIndex: number): void;
declare function SetForLoopIndexB(newIndex: number): void;
declare function SetForceAllianceStateBJ(sourceForce: HForce | null, targetForce: HForce | null, allianceState: number): void;
declare function SetHeroLevelBJ(whichHero: HUnit | null, newLevel: number, showEyeCandy: boolean): void;
declare function SetHeroStat(whichHero: HUnit | null, whichStat: number, value: number): void;
declare function SetImageColorBJ(whichImage: HImage | null, red: number, green: number, blue: number, alpha: number): void;
declare function SetImagePositionBJ(whichImage: HImage | null, where: HLocation | null, zOffset: number): void;
declare function SetItemDropOnDeathBJ(whichItem: HItem | null, flag: boolean): void;
declare function SetItemDroppableBJ(whichItem: HItem | null, flag: boolean): void;
declare function SetItemInvulnerableBJ(whichItem: HItem | null, flag: boolean): void;
declare function SetItemLifeBJ(whichWidget: HWidget | null, life: number): void;
declare function SetItemPlayerBJ(whichItem: HItem | null, whichPlayer: HPlayer | null, changeColor: boolean): void;
declare function SetItemPositionLoc(whichItem: HItem | null, loc: HLocation | null): void;
declare function SetItemVisibleBJ(show: boolean, whichItem: HItem | null): void;
declare function SetLightningColorBJ(whichBolt: HLightning | null, r: number, g: number, b: number, a: number): boolean;
declare function SetMapMusicIndexedBJ(musicName: string, index: number): void;
declare function SetMapMusicRandomBJ(musicName: string): void;
declare function SetMissionAvailableBJ(available: boolean, missionIndex: number): void;
declare function SetMusicOffsetBJ(newOffset: number): void;
declare function SetMusicVolumeBJ(volumePercent: number): void;
declare function SetNextLevelBJ(nextLevel: string): void;
declare function SetPlayerAbilityAvailableBJ(avail: boolean, abilid: number, whichPlayer: HPlayer | null): void;
declare function SetPlayerAllianceBJ(sourcePlayer: HPlayer | null, whichAllianceSetting: HAllianceType | null, value: boolean, otherPlayer: HPlayer | null): void;
declare function SetPlayerAllianceStateAllyBJ(sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null, flag: boolean): void;
declare function SetPlayerAllianceStateBJ(sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null, allianceState: number): void;
declare function SetPlayerAllianceStateControlBJ(sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null, flag: boolean): void;
declare function SetPlayerAllianceStateFullControlBJ(sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null, flag: boolean): void;
declare function SetPlayerAllianceStateVisionBJ(sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null, flag: boolean): void;
declare function SetPlayerColorBJ(whichPlayer: HPlayer | null, color: HPlayerColor | null, changeExisting: boolean): void;
declare function SetPlayerColorBJEnum(): void;
declare function SetPlayerFlagBJ(whichPlayerFlag: HPlayerState | null, flag: boolean, whichPlayer: HPlayer | null): void;
declare function SetPlayerHandicapBJ(whichPlayer: HPlayer | null, handicapPercent: number): void;
declare function SetPlayerHandicapXPBJ(whichPlayer: HPlayer | null, handicapPercent: number): void;
declare function SetPlayerMaxHeroesAllowed(maximum: number, whichPlayer: HPlayer | null): void;
declare function SetPlayerOnScoreScreenBJ(flag: boolean, whichPlayer: HPlayer | null): void;
declare function SetPlayerSlotAvailable(whichPlayer: HPlayer | null, control: HMapControl | null): void;
declare function SetPlayerStateBJ(whichPlayer: HPlayer | null, whichPlayerState: HPlayerState | null, value: number): void;
declare function SetPlayerTaxRateBJ(rate: number, whichResource: HPlayerState | null, sourcePlayer: HPlayer | null, otherPlayer: HPlayer | null): void;
declare function SetPlayerTechMaxAllowedSwap(techid: number, maximum: number, whichPlayer: HPlayer | null): void;
declare function SetPlayerTechResearchedSwap(techid: number, levels: number, whichPlayer: HPlayer | null): void;
declare function SetPlayerUnitAvailableBJ(unitId: number, allowed: boolean, whichPlayer: HPlayer | null): void;
declare function SetRescueBuildingColorChangeBJ(changeColor: boolean): void;
declare function SetRescueUnitColorChangeBJ(changeColor: boolean): void;
declare function SetSoundConeAnglesBJ(soundHandle: HSound | null, inside: number, outside: number, outsideVolumePercent: number): void;
declare function SetSoundDistanceCutoffBJ(soundHandle: HSound | null, cutoff: number): void;
declare function SetSoundOffsetBJ(newOffset: number, soundHandle: HSound | null): void;
declare function SetSoundPitchBJ(soundHandle: HSound | null, pitch: number): void;
declare function SetSoundPositionLocBJ(soundHandle: HSound | null, loc: HLocation | null, z: number): void;
declare function SetSoundVolumeBJ(soundHandle: HSound | null, volumePercent: number): void;
declare function SetSpeechVolumeGroupsBJ(): void;
declare function SetSpeechVolumeGroupsImmediateBJ(): void;
declare function SetStackedSoundBJ(add: boolean, soundHandle: HSound | null, r: HRect | null): void;
declare function SetTerrainFogExBJ(style: number, zstart: number, zend: number, density: number, red: number, green: number, blue: number): void;
declare function SetTerrainPathableBJ(where: HLocation | null, t: HPathingType | null, flag: boolean): void;
declare function SetTerrainTypeBJ(where: HLocation | null, terrainType: number, variation: number, area: number, shape: number): void;
declare function SetTextTagAgeBJ(tt: HTextTag | null, age: number): void;
declare function SetTextTagColorBJ(tt: HTextTag | null, red: number, green: number, blue: number, transparency: number): void;
declare function SetTextTagFadepointBJ(tt: HTextTag | null, fadepoint: number): void;
declare function SetTextTagLifespanBJ(tt: HTextTag | null, lifespan: number): void;
declare function SetTextTagPermanentBJ(tt: HTextTag | null, flag: boolean): void;
declare function SetTextTagPosBJ(tt: HTextTag | null, loc: HLocation | null, zOffset: number): void;
declare function SetTextTagPosUnitBJ(tt: HTextTag | null, whichUnit: HUnit | null, zOffset: number): void;
declare function SetTextTagSuspendedBJ(tt: HTextTag | null, flag: boolean): void;
declare function SetTextTagTextBJ(tt: HTextTag | null, s: string, size: number): void;
declare function SetTextTagVelocityBJ(tt: HTextTag | null, speed: number, angle: number): void;
declare function SetThematicMusicOffsetBJ(newOffset: number): void;
declare function SetTimeOfDay(whatTime: number): void;
declare function SetTimeOfDayScalePercentBJ(scalePercent: number): void;
declare function SetUnitAbilityLevelSwapped(abilcode: number, whichUnit: HUnit | null, level: number): number;
declare function SetUnitAcquireRangeBJ(whichUnit: HUnit | null, acquireRange: number): void;
declare function SetUnitBlendTimeBJ(whichUnit: HUnit | null, blendTime: number): void;
declare function SetUnitExplodedBJ(whichUnit: HUnit | null, exploded: boolean): void;
declare function SetUnitFacingToFaceLocTimed(whichUnit: HUnit | null, target: HLocation | null, duration: number): void;
declare function SetUnitFacingToFaceUnitTimed(whichUnit: HUnit | null, target: HUnit | null, duration: number): void;
declare function SetUnitFlyHeightBJ(whichUnit: HUnit | null, newHeight: number, rate: number): void;
declare function SetUnitLifeBJ(whichUnit: HUnit | null, newValue: number): void;
declare function SetUnitLifePercentBJ(whichUnit: HUnit | null, percent: number): void;
declare function SetUnitManaBJ(whichUnit: HUnit | null, newValue: number): void;
declare function SetUnitManaPercentBJ(whichUnit: HUnit | null, percent: number): void;
declare function SetUnitPositionLocFacingBJ(whichUnit: HUnit | null, loc: HLocation | null, facing: number): void;
declare function SetUnitPositionLocFacingLocBJ(whichUnit: HUnit | null, loc: HLocation | null, lookAt: HLocation | null): void;
declare function SetUnitPropWindowBJ(whichUnit: HUnit | null, propWindow: number): void;
declare function SetUnitRallyDestructable(whichUnit: HUnit | null, targDest: HDestructable | null): void;
declare function SetUnitRallyPoint(whichUnit: HUnit | null, targPos: HLocation | null): void;
declare function SetUnitRallyUnit(whichUnit: HUnit | null, targUnit: HUnit | null): void;
declare function SetUnitScalePercent(whichUnit: HUnit | null, percentScaleX: number, percentScaleY: number, percentScaleZ: number): void;
declare function SetUnitTimeScalePercent(whichUnit: HUnit | null, percentScale: number): void;
declare function SetUnitTurnSpeedBJ(whichUnit: HUnit | null, turnSpeed: number): void;
declare function SetUnitUseFoodBJ(enable: boolean, whichUnit: HUnit | null): void;
declare function SetUnitVertexColorBJ(whichUnit: HUnit | null, red: number, green: number, blue: number, transparency: number): void;
declare function SetUserControlForceOff(whichForce: HForce | null): void;
declare function SetUserControlForceOn(whichForce: HForce | null): void;
declare function SetWaterBaseColorBJ(red: number, green: number, blue: number, transparency: number): void;
declare function ShareEverythingWithTeam(whichPlayer: HPlayer | null): void;
declare function ShareEverythingWithTeamAI(whichPlayer: HPlayer | null): void;
declare function ShowCustomCampaignButton(show: boolean, whichButton: number): void;
declare function ShowDestructableBJ(flag: boolean, d: HDestructable | null): void;
declare function ShowImageBJ(flag: boolean, whichImage: HImage | null): void;
declare function ShowInterfaceForceOff(whichForce: HForce | null, fadeDuration: number): void;
declare function ShowInterfaceForceOn(whichForce: HForce | null, fadeDuration: number): void;
declare function ShowTextTagForceBJ(show: boolean, tt: HTextTag | null, whichForce: HForce | null): void;
declare function ShowUbersplatBJ(flag: boolean, whichSplat: HUberSplat | null): void;
declare function ShowUnitHide(whichUnit: HUnit | null): void;
declare function ShowUnitShow(whichUnit: HUnit | null): void;
declare function SinBJ(degrees: number): number;
declare function SmartCameraPanBJ(whichPlayer: HPlayer | null, loc: HLocation | null, duration: number): void;
declare function StartSoundForPlayerBJ(whichPlayer: HPlayer | null, soundHandle: HSound | null): void;
declare function StartStockUpdates(): void;
declare function StartTimerBJ(t: HTimer | null, periodic: boolean, timeout: number): HTimer;
declare function StopCameraForPlayerBJ(whichPlayer: HPlayer | null): void;
declare function StopMusicBJ(fadeOut: boolean): void;
declare function StopSoundBJ(soundHandle: HSound | null, fadeOut: boolean): void;
declare function StoreBooleanBJ(value: boolean, key: string, missionKey: string, cache: HGameCache | null): void;
declare function StoreIntegerBJ(value: number, key: string, missionKey: string, cache: HGameCache | null): void;
declare function StoreRealBJ(value: number, key: string, missionKey: string, cache: HGameCache | null): void;
declare function StoreStringBJ(value: string, key: string, missionKey: string, cache: HGameCache | null): boolean;
declare function StoreUnitBJ(whichUnit: HUnit | null, key: string, missionKey: string, cache: HGameCache | null): boolean;
declare function String2OrderIdBJ(orderIdString: string): number;
declare function String2UnitIdBJ(unitIdString: string): number;
declare function StringHashBJ(s: string): number;
declare function StringIdentity(theString: string): string;
declare function SubStringBJ(source: string, start: number, end: number): string;
declare function SuspendHeroXPBJ(flag: boolean, whichHero: HUnit | null): void;
declare function TanBJ(degrees: number): number;
declare function TeamInitPlayerSlots(teamCount: number): void;
declare function TerrainDeformationCraterBJ(duration: number, permanent: boolean, where: HLocation | null, radius: number, depth: number): HTerrainDeformation;
declare function TerrainDeformationRandomBJ(duration: number, where: HLocation | null, radius: number, minDelta: number, maxDelta: number, updateInterval: number): HTerrainDeformation;
declare function TerrainDeformationRippleBJ(duration: number, limitNeg: boolean, where: HLocation | null, startRadius: number, endRadius: number, depth: number, wavePeriod: number, waveWidth: number): HTerrainDeformation;
declare function TerrainDeformationStopBJ(deformation: HTerrainDeformation | null, duration: number): void;
declare function TerrainDeformationWaveBJ(duration: number, source: HLocation | null, target: HLocation | null, radius: number, depth: number, trailDelay: number): HTerrainDeformation;
declare function TextTagSize2Height(size: number): number;
declare function TextTagSpeed2Velocity(speed: number): number;
declare function TimerDialogDisplayBJ(show: boolean, td: HTimerDialog | null): void;
declare function TimerDialogDisplayForPlayerBJ(show: boolean, td: HTimerDialog | null, whichPlayer: HPlayer | null): void;
declare function TimerDialogSetSpeedBJ(td: HTimerDialog | null, speedMultFactor: number): void;
declare function TimerDialogSetTimeColorBJ(td: HTimerDialog | null, red: number, green: number, blue: number, transparency: number): void;
declare function TimerDialogSetTitleBJ(td: HTimerDialog | null, title: string): void;
declare function TimerDialogSetTitleColorBJ(td: HTimerDialog | null, red: number, green: number, blue: number, transparency: number): void;
declare function TransmissionFromUnitTypeWithNameBJ(toForce: HForce | null, fromPlayer: HPlayer | null, unitId: number, unitName: string, loc: HLocation | null, soundHandle: HSound | null, message: string, timeType: number, timeVal: number, wait: boolean): void;
declare function TransmissionFromUnitWithNameBJ(toForce: HForce | null, whichUnit: HUnit | null, unitName: string, soundHandle: HSound | null, message: string, timeType: number, timeVal: number, wait: boolean): void;
declare function TriggerActionUnitRescuedBJ(): void;
declare function TriggerExecuteBJ(trig: HTrigger | null, checkConditions: boolean): boolean;
declare function TriggerRegisterAnyUnitEventBJ(trig: HTrigger | null, whichEvent: HPlayerunitEvent | null): void;
declare function TriggerRegisterBuildSubmenuEventBJ(trig: HTrigger | null): HEvent;
declare function TriggerRegisterDestDeathInRegionEvent(trig: HTrigger | null, r: HRect | null): void;
declare function TriggerRegisterDialogEventBJ(trig: HTrigger | null, whichDialog: HDialog | null): HEvent;
declare function TriggerRegisterDistanceBetweenUnits(trig: HTrigger | null, whichUnit: HUnit | null, condition: HBoolExpr | null, range: number): HEvent;
declare function TriggerRegisterEnterRectSimple(trig: HTrigger | null, r: HRect | null): HEvent;
declare function TriggerRegisterEnterRegionSimple(trig: HTrigger | null, whichRegion: HRegion | null): HEvent;
declare function TriggerRegisterGameLoadedEventBJ(trig: HTrigger | null): HEvent;
declare function TriggerRegisterGameSavedEventBJ(trig: HTrigger | null): HEvent;
declare function TriggerRegisterGameStateEventTimeOfDay(trig: HTrigger | null, opcode: HLimitop | null, limitval: number): HEvent;
declare function TriggerRegisterLeaveRectSimple(trig: HTrigger | null, r: HRect | null): HEvent;
declare function TriggerRegisterLeaveRegionSimple(trig: HTrigger | null, whichRegion: HRegion | null): HEvent;
declare function TriggerRegisterPlayerEventAllianceChanged(trig: HTrigger | null, whichPlayer: HPlayer | null): HEvent;
declare function TriggerRegisterPlayerEventDefeat(trig: HTrigger | null, whichPlayer: HPlayer | null): HEvent;
declare function TriggerRegisterPlayerEventEndCinematic(trig: HTrigger | null, whichPlayer: HPlayer | null): HEvent;
declare function TriggerRegisterPlayerEventLeave(trig: HTrigger | null, whichPlayer: HPlayer | null): HEvent;
declare function TriggerRegisterPlayerEventVictory(trig: HTrigger | null, whichPlayer: HPlayer | null): HEvent;
declare function TriggerRegisterPlayerKeyEventBJ(trig: HTrigger | null, whichPlayer: HPlayer | null, keType: number, keKey: number): HEvent;
declare function TriggerRegisterPlayerSelectionEventBJ(trig: HTrigger | null, whichPlayer: HPlayer | null, selected: boolean): HEvent;
declare function TriggerRegisterPlayerUnitEventSimple(trig: HTrigger | null, whichPlayer: HPlayer | null, whichEvent: HPlayerunitEvent | null): HEvent;
declare function TriggerRegisterShowSkillEventBJ(trig: HTrigger | null): HEvent;
declare function TriggerRegisterTimerEventPeriodic(trig: HTrigger | null, timeout: number): HEvent;
declare function TriggerRegisterTimerEventSingle(trig: HTrigger | null, timeout: number): HEvent;
declare function TriggerRegisterTimerExpireEventBJ(trig: HTrigger | null, t: HTimer | null): HEvent;
declare function TriggerRegisterUnitInRangeSimple(trig: HTrigger | null, range: number, whichUnit: HUnit | null): HEvent;
declare function TriggerRegisterUnitLifeEvent(trig: HTrigger | null, whichUnit: HUnit | null, opcode: HLimitop | null, limitval: number): HEvent;
declare function TriggerRegisterUnitManaEvent(trig: HTrigger | null, whichUnit: HUnit | null, opcode: HLimitop | null, limitval: number): HEvent;
declare function TryInitCinematicBehaviorBJ(): void;
declare function TryInitRescuableTriggersBJ(): void;
declare function UnitAddAbilityBJ(abilityId: number, whichUnit: HUnit | null): boolean;
declare function UnitAddIndicatorBJ(whichUnit: HUnit | null, red: number, green: number, blue: number, transparency: number): void;
declare function UnitAddItemByIdSwapped(itemId: number, whichHero: HUnit | null): HItem;
declare function UnitAddItemSwapped(whichItem: HItem | null, whichHero: HUnit | null): boolean;
declare function UnitAddTypeBJ(whichType: HUnitType | null, whichUnit: HUnit | null): boolean;
declare function UnitApplyTimedLifeBJ(duration: number, buffId: number, whichUnit: HUnit | null): void;
declare function UnitCanSleepBJ(whichUnit: HUnit | null): boolean;
declare function UnitCountBuffsExBJ(polarity: number, resist: number, whichUnit: HUnit | null, bTLife: boolean, bAura: boolean): number;
declare function UnitDamagePointLoc(whichUnit: HUnit | null, delay: number, radius: number, loc: HLocation | null, amount: number, whichAttack: HAttackType | null, whichDamage: HDamageType | null): boolean;
declare function UnitDamageTargetBJ(whichUnit: HUnit | null, target: HUnit | null, amount: number, whichAttack: HAttackType | null, whichDamage: HDamageType | null): boolean;
declare function UnitDropItem(inUnit: HUnit | null, inItemID: number): HItem;
declare function UnitDropItemPointBJ(whichUnit: HUnit | null, whichItem: HItem | null, x: number, y: number): boolean;
declare function UnitDropItemPointLoc(whichUnit: HUnit | null, whichItem: HItem | null, loc: HLocation | null): boolean;
declare function UnitDropItemSlotBJ(whichUnit: HUnit | null, whichItem: HItem | null, slot: number): boolean;
declare function UnitDropItemTargetBJ(whichUnit: HUnit | null, whichItem: HItem | null, target: HWidget | null): boolean;
declare function UnitGenerateAlarms(whichUnit: HUnit | null, generate: boolean): boolean;
declare function UnitHasBuffBJ(whichUnit: HUnit | null, buffcode: number): boolean;
declare function UnitHasItemOfTypeBJ(whichUnit: HUnit | null, itemId: number): boolean;
declare function UnitId2OrderIdBJ(unitId: number): number;
declare function UnitId2StringBJ(unitId: number): string;
declare function UnitInventoryCount(whichUnit: HUnit | null): number;
declare function UnitInventorySizeBJ(whichUnit: HUnit | null): number;
declare function UnitIsSleepingBJ(whichUnit: HUnit | null): boolean;
declare function UnitItemInSlotBJ(whichUnit: HUnit | null, itemSlot: number): HItem;
declare function UnitMakeAbilityPermanentBJ(permanent: boolean, abilityId: number, whichUnit: HUnit | null): boolean;
declare function UnitPauseTimedLifeBJ(flag: boolean, whichUnit: HUnit | null): void;
declare function UnitRemoveAbilityBJ(abilityId: number, whichUnit: HUnit | null): boolean;
declare function UnitRemoveBuffBJ(buffcode: number, whichUnit: HUnit | null): boolean;
declare function UnitRemoveBuffsBJ(buffType: number, whichUnit: HUnit | null): void;
declare function UnitRemoveBuffsExBJ(polarity: number, resist: number, whichUnit: HUnit | null, bTLife: boolean, bAura: boolean): void;
declare function UnitRemoveItemFromSlotSwapped(itemSlot: number, whichHero: HUnit | null): HItem;
declare function UnitRemoveItemSwapped(whichItem: HItem | null, whichHero: HUnit | null): void;
declare function UnitRemoveTypeBJ(whichType: HUnitType | null, whichUnit: HUnit | null): boolean;
declare function UnitSetCanSleepBJ(whichUnit: HUnit | null, canSleep: boolean): void;
declare function UnitSetUsesAltIconBJ(flag: boolean, whichUnit: HUnit | null): void;
declare function UnitShareVisionBJ(share: boolean, whichUnit: HUnit | null, whichPlayer: HPlayer | null): void;
declare function UnitSuspendDecayBJ(suspend: boolean, whichUnit: HUnit | null): void;
declare function UnitUseItemDestructable(whichUnit: HUnit | null, whichItem: HItem | null, target: HWidget | null): boolean;
declare function UnitUseItemPointLoc(whichUnit: HUnit | null, whichItem: HItem | null, loc: HLocation | null): boolean;
declare function UnitWakeUpBJ(whichUnit: HUnit | null): void;
declare function UnlockGameSpeedBJ(): void;
declare function UpdateEachStockBuilding(iType: HItemType | null, iLevel: number): void;
declare function UpdateEachStockBuildingEnum(): void;
declare function UpdateStockAvailability(whichItem: HItem | null): void;
declare function UseTimeOfDayBJ(flag: boolean): void;
declare function VolumeGroupResetBJ(): void;
declare function VolumeGroupResetImmediateBJ(): void;
declare function VolumeGroupSetVolumeBJ(vgroup: HVolumeGroup | null, percent: number): void;
declare function VolumeGroupSetVolumeForPlayerBJ(whichPlayer: HPlayer | null, vgroup: HVolumeGroup | null, scale: number): void;
declare function WaitForSoundBJ(soundHandle: HSound | null, offset: number): void;
declare function WaitTransmissionDuration(soundHandle: HSound | null, timeType: number, timeVal: number): void;
declare function WakePlayerUnits(whichPlayer: HPlayer | null): void;
declare function WakePlayerUnitsEnum(): void;
declare function WaygateActivateBJ(activate: boolean, waygate: HUnit | null): void;
declare function WaygateGetDestinationLocBJ(waygate: HUnit | null): HLocation;
declare function WaygateIsActiveBJ(waygate: HUnit | null): boolean;
declare function WaygateSetDestinationLocBJ(waygate: HUnit | null, loc: HLocation | null): void;
declare function WidgetDropItem(inWidget: HWidget | null, inItemID: number): HItem;
